### ISSUE TITLE
Warp prompt should detect context changes

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#1091]
### Describe the bug

```text
If I have 5 Warp tabs open all in the same repository, and if I switch to another branch in one of the tabs, rest of the tabs stay in the same branch.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by matzeso** [comment]
This also is true for switching branches from other places, e.g. when I change branches in VSCode and then open Warp, I am confused because it shows the wrong branch name. Typing any command will update the branch name and show correctly.
For me at least a good enough fix would be to whenever the window gets active (or when tabs are swtiched) all visible panes should check and update the branch name.

**Comment by dannyneira** [comment]
We will be tracking this request tracking this over at https://github.com/warpdotdev/Warp/issues/1091

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
