### ISSUE TITLE
(zsh) flickering and shell failure when `fzf` is used in command substitution 

### ISSUE THREAD

**Issue by zpv** [warpdotdev/Warp#1115]
### Describe the bug

```text
Running `cd $(ls | fzf)` within zsh results in flickering as shown in attached video
It works as expected in bash.
```

### To Reproduce

Steps to reproduce:
1. Start warp with zsh
2. Run `cd $(ls | fzf)`
3. Glitches out

### Expected behaviour

```text
Should not glitch out
```

### Screenshots

https://user-images.githubusercontent.com/12267041/163846596-d49a9c68-f12f-42a7-bf7c-947920324062.mov

### Operating System

MacOS

### OS Version

12.3.1

**Comment by jgnickerson** [comment]
I've also noticed this. I see that fzf incompatibility is listed as a known issue here: https://docs.warp.dev/help/known-issues . 
Is there any update on a timeline for improving support here? fzf is a big part of my workflow and lack of support is preventing me from using warp or recommending it to others in my org

**Comment by warpdotdev-dx** [comment]
No eta. My guess is that a native solution would eventually be built or creating an API that FZF can integrate with.

--- original message ---
On May 16, 2022, 6:37 PM EDT ***@***.*** wrote:



I've also noticed this. I see that fzf incompatibility is listed as a known issue here: https://docs.warp.dev/help/known-issues .

Is there any update on a timeline for improving support here? fzf is a big part of my workflow and lack of support is preventing me from using warp or recommending it to others in my org

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by zpv** [comment]
Hmm, I've re-installed Warp after a few months and looks like this issue is fixed!
