### ISSUE TITLE
New line starts with time

### ISSUE THREAD

**Issue by sahilg14** [warpdotdev/Warp#1125]
### Discord username (optional)

hitman#5149

### Describe the bug

```text
I have attached a video.
I would expect the new line to be empty, but there is all this information already filled in and I have to clear it before running any command.
```

### To Reproduce

Steps to reproduce:
1. Open warp
2. Press Enter

### Expected behaviour

```text
I would expect the new line to be empty, but there is all this information already filled in and I have to clear it before running any command.
```

### Screenshots

https://user-images.githubusercontent.com/19500549/164071071-9afe1307-dd2d-4907-8bd2-b96bed2f3b01.mov

### Operating System

MacOS

**Comment by ptim** [comment]
Looks like you're using powerline or similar PS1 helper... I had this issue with git-prompt, and worked around the issue (at the expense of not using git-prompt in warp) by [conditionally sourcing git-prompt in .bash_profile](https://github.com/warpdotdev/Warp/discussions/422#discussioncomment-2598416). HTH!

**Comment by elviskahoro** [comment]
Check out these docs:
https://docs.warp.dev/help/known-issues

This is the issue we're using to track this: #936

**Comment by warpdotdev-dx** [comment]
You can disable specific parts of your RC file just for Warp! Take a look at this section of our documentation: <https://docs.warp.dev/help/known-issues#debugging>

--- original message ---
On April 20, 2022, 2:18 AM EDT ***@***.*** wrote:



Looks like you're using powerline or similar PS1 helper... I had this issue with git-prompt, and worked around the issue (at the expense of not using git-prompt in warp) by conditionally sourcing git-prompt in .bash_profile. HTH!

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
