### ISSUE TITLE
Is there a way to opt-out of frequent HTTP requests sent to app.warp.dev

### ISSUE THREAD

**Issue by NotJustClarkKent** [warpdotdev/Warp#1131]
### GitHub username

NotJustClarkKent

### Description of issue

I run LittleSnitch and noticed frequent requests (~hourly) being sent back to app.warp.dev. What sort of information is being sent and is there a way to disable this reporting?

![warp-calling-home](https://user-images.githubusercontent.com/2006387/164121811-213d8514-9430-44c2-912f-1233b9a8522a.png)

**Comment by NotJustClarkKent** [comment]
I just [found this](https://docs.warp.dev/getting-started/privacy#telemetry-what-usage-data-are-you-collecting-and-why) and it answered the telemetry question. That said, can we opt-out?

**Comment by warpdotdev-dx** [comment]
Can you email ***@***.***? We can reach back out once there have been changes.

--- original message ---
On April 20, 2022, 10:55 AM EDT ***@***.*** wrote:



I just found this and it answered the telemetry question. That said, can we opt-out?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by elviskahoro** [comment]
@NotJustClarkKent can you email feedback@warp.dev? I can add you to my list of people to circle back with regarding telemetry.
