### ISSUE TITLE
Settings/Preferences should be available in the MenuBar

### ISSUE THREAD

**Issue by AndrewGrossman** [warpdotdev/Warp#1136]
### Describe the solution you'd like?

```text
Request: Terminal window options, especially general application settings, should be available via the OS-provided menu bar.

Just installed Warp, after excitedly reading about it in console.dev. The first thing I almost always do when installing a new terminal or editor application is go to increase the font size. I'm getting to be an old man now, but even before then, my optometrist always encouraged larger text sizes. I'm a believer and actually think there's a separate opportunity to make the world better for developers just by prompting for "Larger text: yes/no (Optometrist recommended!)" on first runs of application like Warp.

Anyway, I went looking for the settings to update font size. To my surprise, settings are not available in any of the menu bar options, as far as I could tell. Eventually, the docs showed me that it's part of the terminal window. IMO, not all of those generic options that are in the terminal window as part of the application menu bar is an anti-pattern. If I'm in any application looking for settings, that's where I go. Not to some widget off of one of the application windows. I would anticipate this is a common user expectation.

Apologies if I missed it. I triple-checked and don't see it there.
```

**Comment by elviskahoro** [comment]
Thanks for opening. Gonna close in favor of #101

**Comment by warpdotdev-dx** [comment]
I think is a duplicate:
GitHub issue for updating our mac menu: https://github.com/warpdotdev/Warp/issues/101​


Agreed with your analysis! (elvis)

--- original message ---
On April 20, 2022, 1:34 PM EDT ***@***.*** wrote:



Discord username (optional)

No response

Describe the solution you'd like?

Request: Terminal window options, especially general application settings, should be available via the OS-provided menu bar.

Just installed Warp, after excitedly reading about it in console.dev. The first thing I almost always do when installing a new terminal or editor application is go to increase the font size. I'm getting to be an old man now, but even before then, my optometrist always encouraged larger text sizes. I'm a believer and actually think there's a separate opportunity to make the world better for developers just by prompting for "Larger text: yes/no (Optometrist recommended!)" on first runs of application like Warp.

Anyway, I went looking for the settings to update font size. To my surprise, settings are not available in any of the menu bar options, as far as I could tell. Eventually, the docs showed me that it's part of the terminal window. IMO, not all of those generic options that are in the terminal window as part of the application menu bar is an anti-pattern. If I'm in any application looking for settings, that's where I go. Not to some widget off of one of the application windows. I would anticipate this is a common user expectation.

Apologies if I missed it. I triple-checked and don't see it there.

Is your feature request related to a problem? Please describe.

No response

Additional context

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
