### ISSUE TITLE
Provide a way to delete Command History

### ISSUE THREAD

**Issue by ghost** [warpdotdev/Warp#1157]
### Discord username (optional)

beeHive#1515

### Describe the solution you'd like?

```text
Provide a shortcut to clear the Command History
```

### Is your feature request related to a problem? Please describe.

```text
I often find myself passing my computer with my terminal open when I'm collaborating with friends on something and it makes me a bit uneasy to expose the full command history.
```

**Comment by warpdotdev-dx** [comment]
I think is a duplicate:
GitHub issue for natively supporting ways to delete history: <https://github.com/warpdotdev/Warp/issues/516>

--- original message ---
On April 22, 2022, 4:47 AM EDT ***@***.*** wrote:



Discord username (optional)

beeHive#1515

Describe the solution you'd like?

Provide a shortcut to clear the Command History

Is your feature request related to a problem? Please describe.

I often find myself passing my computer with my terminal open when I'm collaborating with friends on something and it makes me a bit uneasy to expose the full command history.

Additional context

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
