### ISSUE TITLE
Fish right side prompt locked in time

### ISSUE THREAD

**Issue by rcousens** [warpdotdev/Warp#1159]
### Describe the bug

Launch warp, using tide prompt and fisher with fish shell. I have a right side as part of my prompt that for whatever reason is not overridden by warp. Regardless, it shows what it normally does in fish, however it is "stuck in time". I.e. the time never updates.

My preference would be if you're going to override the prompt then clear out the right side prompt for fish (fish_right_prompt, see https://fishshell.com/docs/current/cmds/fish_right_prompt.html)

### To Reproduce

Open warp

### Screenshots

![Screen Shot 2022-04-22 at 8 37 29 pm](https://user-images.githubusercontent.com/6834920/164699168-1295a1e6-a7e9-482a-999a-dd01dc7161cb.png)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by warpdotdev-dx** [comment]
Hey Ross,


You can disable this prompt just for Warp using a conditional flag:
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

--- original message ---
On April 22, 2022, 6:41 AM EDT ***@***.*** wrote:



Discord username (optional)

No response

Describe the bug

Launch warp, using tide prompt and fisher with fish shell. I have a right side as part of my prompt that for whatever reason is not overridden by warp. Regardless, it shows what it normally does in fish, however it is "stuck in time". I.e. the time never updates.

My preference would be if you're going to override the prompt then clear out the right side prompt for fish (fish_right_prompt, see https://fishshell.com/docs/current/cmds/fish_right_prompt.html)

To Reproduce

Open warp

Expected behaviour

No response

Screenshots


Operating System

MacOS

OS Version

12.3.1

Additional context

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by elviskahoro** [comment]
Gonna merge this with #936
