### ISSUE TITLE
[Feature] Transparency and blur of window

### ISSUE THREAD

**Issue by mikigal** [warpdotdev/Warp#1165]
### Discord username (optional)

Miyukki#5517

### Describe the solution you'd like?

Currently while creating own theme there's only option named ```opacity``` which sets transparency of background color. It would be nice to add option to allow make window of terminal semi-transparent and blured (to make it more readable), so I can see my desktop wallpaper or other apps under terminal in background. Same feature is implemented in iTerm 2. 
Example of this feature: https://progsoft.net/images/iterm-e91bb32b0bb771ca594d0f45dfb2182ba62e6be2.png

**Comment by bryanbrunetti** [comment]
I'd love this feature as well.

_This is also possible with the built-in OSX Terminal by setting the opacity and blur of the background color:_

<img width="929" alt="Screen Shot 2022-05-04 at 9 55 35 AM" src="https://user-images.githubusercontent.com/2984304/166696804-9af9ed9c-6242-480e-970c-7ca9adb2e4e3.png">

<img width="301" alt="Screen Shot 2022-05-04 at 9 58 03 AM" src="https://user-images.githubusercontent.com/2984304/166697073-b57347ff-3d3f-4405-ba9c-c5fadbd9a802.png">

**Comment by elviskahoro** [comment]
Thanks for opening
Tracking this here:
#17

**Comment by warpdotdev-dx** [comment]
I think is a duplicate:
GitHub issue for changing background opacity / transparency: <https://github.com/warpdotdev/Warp/issues/17>

--- original message ---
On May 4, 2022, 9:59 AM EDT ***@***.*** wrote:



I'd love this feature as well.

This is also possible with the built-in OSX Terminal by setting the opacity and blur of the background color:



—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
