### ISSUE TITLE
add Reuse previous session's

### ISSUE THREAD

**Issue by zxitedu** [warpdotdev/Warp#1170]
### Describe the solution you'd like?

```text
I hope you can add Reuse previous session's directory to make sure that re-establishing a new window of ssh will not make you re-enter your password.
Thank you
```

### Is your feature request related to a problem? Please describe.

```text
After opening the window and using ssh to connect to the remote server, re-open a new window and use ssh to connect to the same server without entering a password again
```

**Comment by elviskahoro** [comment]
Great idea! We're tracking this here:
https://github.com/warpdotdev/Warp/discussions/442

**Comment by warpdotdev-dx** [comment]
Keeping track of this here: https://github.com/warpdotdev/Warp/discussions/442

--- original message ---
On April 22, 2022, 11:25 PM EDT ***@***.*** wrote:



Discord username (optional)

No response

Describe the solution you'd like?

I hope you can add Reuse previous session's directory to make sure that re-establishing a new window of ssh will not make you re-enter your password.
Thank you

Is your feature request related to a problem? Please describe.

After opening the window and using ssh to connect to the remote server, re-open a new window and use ssh to connect to the same server without entering a password again

Additional context

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
