### ISSUE TITLE
Fish shell syntax highlighting not supported

### ISSUE THREAD

**Issue by nanthony007** [warpdotdev/Warp#1177]
### Discord username (optional)

TimeWellWasted#3327

### Describe the bug

```text
I am not seeing fish shell syntax highlighting being supported, but I may be wrong.
```

### To Reproduce

1. Enable fish shell
2. Attempt prompt typing

### Expected behaviour

```text
I expected to see valid commands colors and invalid commands colored red.
```

### Screenshots

<img width="227" alt="Screen Shot 2022-04-23 at 4 59 53 PM" src="https://user-images.githubusercontent.com/45318637/164945833-abc76f9f-28b9-47ba-b87d-292c60402bad.png">
<img width="227" alt="Screen Shot 2022-04-23 at 5 00 24 PM" src="https://user-images.githubusercontent.com/45318637/164945847-41d1cfe0-7aba-44df-86d1-6aa09345da35.png">
<img width="433" alt="Screen Shot 2022-04-23 at 5 00 49 PM" src="https://user-images.githubusercontent.com/45318637/164945854-218f1f65-1cef-4fe4-8d8c-fcddfedfebd1.png">

### Operating System

MacOS

### Additional context

```text
Interestingly this DOES work when I enter the fish prompt inside Warp, but then the entire fish session is treated as one cell.
```

**Comment by elviskahoro** [comment]
Gonna close in favor of:
#66

**Comment by Advait-M** [comment]
Hey folks 👋 ! @nanthony007 @shinlang @henrik2706 @Agrailag @omninonsense @elijah-rou

Super excited to let everyone know that we just launched **Syntax Highlighting and Error Underlining on Warp yesterday** 🎉 ! By default, Warp will highlight each part of a command in a different color denoting arguments, options/flags, variables, etc. and underline invalid commands with a dashed red line. You can toggle these features on/off via the Command Palette or Settings > Features.

Note that these features are built into Warp itself and will be active within Warp's [custom input editor](https://docs.warp.dev/features/editor). Syntax highlighting by shells such as fish will continue to apply to past commands (in the block grid), since they function by using ANSI escape sequences for coloring text. We may explore adding Warp syntax highlighting to past commands as well, in the future.

Please download the latest release (`v0.2022.10.11.08.13.stable_01`) to get access to these features! The screenshot below shows the features in action:

![Syntax Highlighting and Error Underlining Demo](https://user-images.githubusercontent.com/12927474/195830313-e3eab7b1-84c7-4118-896d-443215c1e3b5.png)

Check out our [user documentation](https://docs.warp.dev/features/editor/error-syntax-highlighting) for more details!

Let us know if you have any comments/feedback on these features!
