### ISSUE TITLE
Feature request: Close tab with mouse wheel click

### ISSUE THREAD

**Issue by PhilipDukhov** [warpdotdev/Warp#1180]
### Describe the solution you'd like?

```text
When I hover my mouse over a tab and click the mouse wheel, I expect the tab to be closed.
```

### Additional context

This is Mac system behavior, and I'm used to using it in all applications.

**Comment by warpdotdev-dx** [comment]
I think is a duplicate:
GitHub issue for closing tab with middle button click: https://github.com/warpdotdev/Warp/issues/553

--- original message ---
On April 24, 2022, 3:50 AM EDT ***@***.*** wrote:



Discord username (optional)

No response

Describe the solution you'd like?

When I hover my mouse over a tab and click the mouse wheel, I expect the tab to be closed.

Is your feature request related to a problem? Please describe.

No response

Additional context

This is Mac system behavior, and I'm used to using it in all applications.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
