### ISSUE TITLE
in docker exec -it php /bin/sh,is no intelligent prompt for the tab button

### ISSUE THREAD

**Issue by tlerbao** [warpdotdev/Warp#1184]
### Describe the bug

Using the "docker exec -it php /bin/sh" command, after entering the docker container terminal, there is no intelligent prompt for the tab button.

### Operating System

MacOS

### OS Version

11.6.5

**Comment by elviskahoro** [comment]
Thanks for opening. We're tracking this here:
https://github.com/warpdotdev/Warp/discussions/652

**Comment by warpdotdev-dx** [comment]
Is 1 still happening to you?
Also we don't have docker support for tab completions yet!


See our GitHub issue for missing completion specs: https://github.com/warpdotdev/Warp/discussions/652

--- original message ---
On April 24, 2022, 10:24 AM EDT ***@***.*** wrote:



Discord username (optional)

No response

Describe the bug

1. Prompt after connecting to ssh（iterm2 doesn't have this problem）: 

/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory



2. Using the "docker exec -it php /bin/sh" command, after entering the docker container terminal, there is no intelligent prompt for the tab button. 

To Reproduce

No response

Expected behaviour

No response

Screenshots

No response

Operating System

MacOS

OS Version

11.6.5

Additional context

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
