### ISSUE TITLE
zsh-syntax-highlighting is not working

### ISSUE THREAD

**Issue by rk-windo** [warpdotdev/Warp#1211]
### Discord username (optional)

Dhanush#1207

### Describe the bug

```text
zsh-syntax-highlighting is not working on warp!
```

### Screenshots

<img width="1247" alt="Screenshot_2022-04-27_at_1 18 14_PM" src="https://user-images.githubusercontent.com/103654620/165486815-fe24bb6c-e5af-4cb8-8827-633a023fa5ab.png">

### Operating System

MacOS

### OS Version

12.13.1

### Additional context

[zshrc](https://github.com/warpdotdev/Warp/files/8571006/zshrc.txt)

**Comment by guidoferreyra** [comment]
+1 on this. Would be great if Warp supports syntax highlighting.

**Comment by ansonliao** [comment]
+1 on this, Would be great if Warp supports syntax highligting.

**Comment by timrcase** [comment]
+1

**Comment by thutto** [comment]
+1

**Comment by warpdotdev-dx** [comment]
I think is a duplicate:
GitHub issue for Syntax highlighting: https://github.com/warpdotdev/Warp/issues/66

**Comment by Advait-M** [comment]
Hey folks 👋 ! @rk-windo @guidoferreyra @ansonliao @timrcase @thutto @rewired-gh @imjordanxd 

Super excited to let everyone know that we just launched **Syntax Highlighting and Error Underlining on Warp yesterday** 🎉 ! By default, Warp will highlight each part of a command in a different color denoting arguments, options/flags, variables, etc. and underline invalid commands with a dashed red line. You can toggle these features on/off via the Command Palette or Settings > Features.

Note that these features are built into Warp itself and will be active within Warp's [custom input editor](https://docs.warp.dev/features/editor). Plugins such as `zsh-syntax-highlighting` will continue to apply to past commands (in the block grid), since they function by using ANSI escape sequences for coloring text. We may explore adding Warp syntax highlighting to past commands as well, in the future.

Please download the latest release (`v0.2022.10.11.08.13.stable_01`) to get access to these features! The screenshot below shows the features in action:

![Syntax Highlighting and Error Underlining Demo](https://user-images.githubusercontent.com/12927474/195830313-e3eab7b1-84c7-4118-896d-443215c1e3b5.png)

Check out our [user documentation](https://docs.warp.dev/features/editor/error-syntax-highlighting) for more details!

Let us know if you have any comments/feedback on these features!

**Comment by ansonliao** [comment]
Hi @Advait-M , thanks for your excellent work on this, I upgraded to the version you mention, yes and it's working now, appreciate.

**Comment by Advait-M** [comment]
> Hi @Advait-M , thanks for your excellent work on this, I upgraded to the version you mention, yes and it's working now, appreciate.

Awesome!! Thanks for the kind words ❤️ - glad to hear it's working well for you!

**Comment by lowercase00** [comment]
@Advait-M it the current syntax highlighting works great, but I still wonder how could Warp work with `syntax-highlighter`, mainly because the latter offers some customization options (bold commands, coloring etc). Or maybe there's a way to customize Warp's highlighter?

**Comment by Advait-M** [comment]
> @Advait-M it the current syntax highlighting works great, but I still wonder how could Warp work with `syntax-highlighter`, mainly because the latter offers some customization options (bold commands, coloring etc). Or maybe there's a way to customize Warp's highlighter?

Thanks for the comment and suggestion @lowercase00 ! 

Gotcha, definitely agree that more customization options would be nice. `syntax-highlighter` as in `zsh-syntax-highlighting` or do you mean another package? 

But yep, since Warp's input editor is architected differently from the command blocks (which follow more "traditional" terminal concepts, using ANSI escape codes for colouring text), we're unable to directly use these plugins/packages within the context of the input editor. As such, we need to build custom solutions for the input editor - it wouldn't be possible to directly integrate existing plugins here. Though, as a sidenote, likely be exploring how to preserve highlighting within command blocks in the future as well.

Could you create another issue for this, for tracking purposes, highlighting which customization features you'd like to see? Thanks!
