### ISSUE TITLE
Option to remove the jump to last command?

### ISSUE THREAD

**Issue by igniscyan** [warpdotdev/Warp#1213]
### Discord username (optional)

IgnisCyan#1337

### Describe the solution you'd like?

```text
Annoyingly, there’s no way to disable the button that brings you to the last command.

Example: run clear, and now you have a “jump to clear” button on top of the terminal window for the remainder of the session. 

I don’t think this behavior should be default, and at the very least it should be an option.
```

**Comment by warpdotdev-dx** [comment]
I think is a duplicate:
GitHub issue for hiding the clear button / snackbar: https://github.com/warpdotdev/Warp/issues/8

--- original message ---
On April 27, 2022, 9:20 AM EDT ***@***.*** wrote:



Discord username (optional)

IgnisCyan#1337

Describe the solution you'd like?

Annoyingly, there’s no way to disable the button that brings you to the last command.



Example: run clear, and now you have a “jump to clear” button on top of the terminal window for the remainder of the session. 



I don’t think this behavior should be default, and at the very least it should be an option. 

Is your feature request related to a problem? Please describe.

No response

Additional context

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
