### ISSUE TITLE
Support https://fig.io/

### ISSUE THREAD

**Issue by seabornlee** [warpdotdev/Warp#1234]
### Describe the solution you'd like?

```text
Fig is popular and helpful.
And it works perfectly with iTerm2. Warp is a game changer, I use it as main terminal, hope it support Fig ASAP.
```

**Comment by StarWais** [comment]
Would like to see fig integration too

**Comment by joshwcorbett** [comment]
The ai autocomplete is cool and all but I'd much rather have fig support, or the ability to toggle between both.

**Comment by chav-aniket** [comment]
I'd love to see support for fig autocomplete and extensions as well!

**Comment by elviskahoro** [comment]
We actually bootstrapped our completion specs based on Fig. Our completions behavior and UX is something to be built natively into Warp versus relying on an external platform that sits on top of it.

Here's some of the outstanding issues and opportunities for improvement:
https://github.com/warpdotdev/Warp/milestone/3

**Comment by yehudamakarov** [comment]
@elviskahoro, I've heard this before that "warp is based on fig specs" or something like that.

Most documentation and completion is **vastly** superior in Fig than it is in Warp. This includes 
- flags, 
- documentation, 
- even top-level commands

What class of improvements need to be made in Warp in order for there to be complete auto-complete?

are they already on https://github.com/warpdotdev/Warp/milestone/3

**Comment by yehudamakarov** [comment]
**fig**
<img width="580" alt="image" src="https://user-images.githubusercontent.com/27930483/182933138-40ba1202-cea2-46fd-9b11-d44b5cd84cf9.png">

**warp**
1. lookin good...
<img width="767" alt="image" src="https://user-images.githubusercontent.com/27930483/182933422-9fbcf13c-9280-4013-9cab-8de4d4a3a25e.png">
2. and that's it
<img width="207" alt="image" src="https://user-images.githubusercontent.com/27930483/182933981-732b18b5-56d9-4928-aa35-f1a4be4eecb6.png">

**Comment by elviskahoro** [comment]
Warp's completion spec, which is based off of Fig's is in Rust. Importing Fig's specs requires that the team rewrites them in Rust, the last import was in January. The group at Fig are high velocity and so they've added lots since then as well as building out the completions **product**. The team is currently working on a refresh, this doesn't imply that the completions product will be as good, we'll just be up-to-date regarding the spec.

Improving the completions product and UX is a project that's been undertaken this next quarter, so there'll be exciting advancements!

**Comment by chav-aniket** [comment]
Are there any updates in this space?

**Comment by elviskahoro** [comment]
Yeah we've had two big updates when it comes to the completion spec but less so with improving command entry.
