### ISSUE TITLE
`PROMPT_COMMAND` causing bug. The value of `PS1` gets entered in my command prompt... as a command

### ISSUE THREAD

**Issue by acarl005** [warpdotdev/Warp#1321]
### Local Shell and Version

Zsh 5.8

### Remote Shell and Version

Bash 5.0.11(1)-release

### Operating System and Version

an internal, custom Linux distro

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

![Screen Shot 2022-05-09 at 4 55 39 PM](https://user-images.githubusercontent.com/8334252/167497034-2a1e5f66-6cbf-4033-b859-af6a1cb9e684.png)

My `.bashrc` contains `PROMPT_COMMAND='PS1="my prompt>";'`.
This is causing the string `my prompt>` to appear *after* the actual prompt as part of my **command**. I have to backspace it in order to enter any commands. If I remove that line, the problem goes away. However, `PROMPT_COMMAND` is a standard part of the shell and I think I should be able to set it in order to customize my experience.

### Include shell xtrace output

emailed

**Comment by caleb531** [comment]
I am having this same issue, as I am also setting my `PS1` within my `PROMPT_COMMAND` function. Doing so is useful because it allows my PS1 to change dynamically (e.g. current git branch of whichever repository I'm in, even if I switch directories).

```sh
__output_ps1() {
    # Output lots of stuff
}
__update_prompt_command() {

    PS1="$(__output_ps1)"
    # Append in-memory command history to file
    history -a
    # Ensure current working directory carries to new tabs
    update_terminal_cwd 2> /dev/null

}
PROMPT_COMMAND="__update_prompt_command"
```

The above code works fine in my Terminal, however in Warp, the output of `__output_ps1` gets prepended before my insertion point, for every command after the first.

<img width="284" alt="Screen Shot 2022-05-10 at 12 13 04 PM" src="https://user-images.githubusercontent.com/872474/167705097-f4462a35-1dd2-419a-bb0c-bf418d60ea3f.png">
