### ISSUE TITLE
Date being inserted into Suggestions after adding a timestamp to Right via .zshrc

### ISSUE THREAD

**Issue by ncbooth** [warpdotdev/Warp#1378]
### Describe the bug

After enabling a terminal timestamp via adding RPROMPT="[%D{%y/%m/%f}|%@]" AI include the rprompt date in suggestions.  Because it is to the right, it is very hard to notice.

### To Reproduce

1. Add a timestamp to zsh via RPROMPT="[%D{%y/%m/%f}|%@]"
2. Enter a command semi-frequently so that it is autosuggested
3. Suggestions will frequently include spaces and timestamp

### Screenshots

<img width="1605" alt="Screen Shot 2022-05-19 at 6 00 35 PM" src="https://user-images.githubusercontent.com/9791530/169411764-692172e1-ebc2-47c4-9b97-ebda247d150f.png">

### Operating System

MacOS

### OS Version

12.3.1 (21E258)

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna clsoe in favor of #1015

**Comment by warpdotdev-dx** [comment]
You can disable specific parts of your RC file just for Warp! Take a look at this section of our documentation: <https://docs.warp.dev/help/known-issues#debugging>

--- original message ---
On May 19, 2022, 6:02 PM EDT ***@***.*** wrote:



Discord username (optional)

No response

Describe the bug

After enabling a terminal timestamp via adding RPROMPT="[%D{%y/%m/%f}|%@]" AI include the rprompt date in suggestions. Because it is to the right, it is very hard to notice.

To Reproduce

Add a timestamp to zsh via RPROMPT="[%D{%y/%m/%f}|%@]"

Enter a command semi-frequently so that it is autosuggested

Suggestions will frequently include spaces and timestamp


Expected behaviour

No response

Screenshots


Operating System

MacOS

OS Version

12.3.1 (21E258)

Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

Additional context

No response

Warp Internal (ignore): linear-label:24888f54-df93-45d5-9bdd-e38f740cac19

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
