### ISSUE TITLE
Can't input value when using `command + N` to open new windows？

### ISSUE THREAD

**Issue by southorange1228** [warpdotdev/Warp#1390]
### Describe the bug

```text
open new window by using `command + n`，the new window can't input anything.And it works if I type elsewhere.

It likes can't focus.
```

### To Reproduce

Steps to reproduce:
1. open new window
2. open new window with `command + n`
3. try to type something and it can't work

### OS Version

12.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by southorange1228** [comment]
https://user-images.githubusercontent.com/32590310/175026632-208fa798-5995-4900-894b-5f402f54c15c.mp4


Just like this. I open a new window with `command + n` and the new window can't enter letters, but it can enter numbers and other symbols.
It's always for me.

**Comment by elviskahoro** [comment]
Can you go to settings and enable honor PS1

**Comment by southorange1228** [comment]
> Can you go to settings and enable honor PS1

<img width="507" alt="image" src="https://user-images.githubusercontent.com/32590310/178174012-7fb84444-e20d-478c-b599-4cef0a6a5ac9.png">

Same error

**Comment by elviskahoro** [comment]
@southorange1228 did the recent updates fix this? If not can you send over your dotfiles. Plus it looks like you're running conda or some venv?

**Comment by southorange1228** [comment]
Not yet.
And which file do you want ？I use `oh-my-zsh` and `macos M1`

`~/.zsh` or other file?

**Comment by warpdotdev-dx** [comment]
Can you check whether this still happens even with clean configs? Just to cover our bases:


Set

> ZDOTDIR=/

in your

> ~/.zshenv

file. This forces Zsh to run with zero configs.


See our documentation here: 
<https://docs.warp.dev/help/known-issues#debugging>

--- original message ---
On July 26, 2022, 9:31 PM EDT ***@***.*** wrote:



Not yet.

And which file do you want ？I use oh-my-zsh and macos M1

~/.zsh or other file?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you commented.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by southorange1228** [comment]
<img width="262" alt="image" src="https://user-images.githubusercontent.com/32590310/181188698-c382d01f-fb80-49c1-a075-7201581224eb.png">
Just like this ？
I set this line into `~/.zshenv` and restart `wrap`. It's useless...i got the same error

**Comment by elviskahoro** [comment]
@zheng any ideas

**Comment by javasopp** [comment]
I also have the same operation, the same problem occurs, the combined operation of command + n cannot input anything.

**Comment by zheng** [comment]
Does this also happen if you try in a new pane (cmd+D) and in a new tab (cmd+T) or only for new windows?

Are you on an international keyboard?

If you open Console and check the Warp logs when you encounter the bug, what do you see?

**Comment by southorange1228** [comment]
`open warp -> cmd + N -> cmd + D/T ` that's ok   
`open warp -> cmd + D/T`  the same problem

Of course, it's an international keyboard.And what should i do to open console? i can't find any documents about it.

**Comment by southorange1228** [comment]
@zheng @elviskahoro Any suggestions to fix it? Now i can be reproduce in latest version.

**Comment by javasopp** [comment]
I will have this situation in special scenarios, the probability of occurrence is not large, but it will still happen. For example, if I use frpc, enter the command `frpc -c ./frpc.ini` and then use command + n to open a new window, which may cause the input to fail.
