### ISSUE TITLE
Restore/Default window size/location on open/in launch configs

### ISSUE THREAD

**Issue by madatbay** [warpdotdev/Warp#1399]
### Describe the bug

```text
When I resize the window and close the terminal (with a red button or cmd+Q), the size of the window resizes back to the default value that comes with installation.
```

### To Reproduce

Steps to reproduce:
1. Go to terminal
2. Resize the window to another width and height
3. Close the terminal
5. Open it againç you'll see your resized window is not persistent

### Expected behaviour

```text
When I reopen the terminal window, it should be opened with the custom width and height I resized.
```

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

bash: 3.2.57(1)-release, zsh: 5.8

**Comment by elviskahoro** [comment]
@madatbay thanks for reporting. Is session restoration enabled in settings? can you share a video

**Comment by elviskahoro** [comment]
The video has been archived @madatbay can you just drop the file here in github. It can embed

**Comment by deadcoder0904** [comment]
can we get this please?

it's annoying to use warp when it keeps changing my preference (rectangle window) to square window everytime i launch it.

**Comment by dannyneira** [comment]
Hi all, I'm Danny, Support Engineer with Warp. We are aware of this and it currently isn't a bug. I've marked this as a feature request. Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by danaspiegel** [comment]
Definitely would like to see this. Additionally, it would be helpful to be able to configure what the new window size is for any new windows created. OS X Terminal has this as well, with a hotkey (cmd-option-0) to resize the current window to be the default window size. The hotkey is useful because the window size changes if you sleep the display and swap monitors.

![Screenshot 20221113132742@2x](https://user-images.githubusercontent.com/6631/201538022-0810d8a7-4222-4149-b448-e826e14bc6fd.png)

**Comment by dezerving** [comment]
Persistent window sizing with setting dimensions manually would be amazing. If not that then at least just honor whatever we last set the window size to. +1

**Comment by zormandi** [comment]
+1

**Comment by acampb** [comment]
+1

**Comment by deadcoder0904** [comment]
guys don't unnecessarily do +1. just react 👍  on first comment.

lots of people are subscribed to this issue get useless notification emails.

**Comment by esycat** [comment]
It would be handy to set window size in launch configurations.

**Comment by jackbow** [comment]
+1 for the hotkey window height

**Comment by Haruno19** [comment]
+1!
Persistent/configurable window size is much needed! It's the only "big" productivity issue I am facing right now with Warp

**Comment by glhrmv** [comment]
This is a must have. Additionally, I would suggest setting the default size to be a lot smaller. 
On a MacBook Pro, the window takes up about 2/3 of the screen.

**Comment by RoyRao2333** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/31413093/227820474-190784be-9eca-4468-97bc-75f8e3a1d504.png">

Yes, each of us came here would want this feature. But you can simply click the little thumb-up button rather than reply *how you want this feature badly* because the subscribers of this issue just wanna see some progress, not these complains. Thanks! :)

**Comment by dannyneira** [comment]
Consolidated several requests into this one, requesting persistent/configurable window size/location on window open/in launch configurations.

**Comment by zachlloyd** [comment]
I'm currently working on (parts) of this request and would love feedback on whether I'm doing it in a way that satisfies folks needs.

Part 1: Reopen closed windows with the same size and location -- check out this video and let me know if it's right

https://user-images.githubusercontent.com/8727141/235011000-b5c4103c-797a-4e90-b645-7495d7c6bcac.mov

Part 2: Set a default size for all new windows -- is this the correct idea?

<img width="423" alt="Image 2023-04-27 at 5 16 15 PM" src="https://user-images.githubusercontent.com/8727141/235010526-77896e5a-b95f-41cf-879f-667de739df50.png">

**Comment by jackbow** [comment]
That looks great! Thanks for working on it!

I'm curious if it fixes my personal use case which is with the dedicated hotkey window (settings -> features -> keys -> global hotkey -> dedicated hotkey window) (which I've got at 100% width, 40% height & pin to top). I want to be able to open the hotkey window, drag the bottom window border to enlarge the window, dismiss the window, re-open it, and have the same height as previous.

Here's a video of how it works for me now (on v0.2023.04.25.08.05.stable_00):
https://user-images.githubusercontent.com/15710512/235026787-8d579015-d3b0-406a-88ef-b1ed64f11a49.mov

Here's a video of how it would ideally work (using iterm):
https://user-images.githubusercontent.com/15710512/235027110-60bb343a-8005-462d-b585-d88bb209b7fe.mov

**Comment by zachlloyd** [comment]
Great call on the hotkey window - I would have missed that.  I'll make sure that works correctly.

**Comment by zachlloyd** [comment]
@jackbow how would you expect the "remember the last size" behavior to interact with the explicit settings for height and width?

<img width="505" alt="Image 2023-04-28 at 1 39 51 PM" src="https://user-images.githubusercontent.com/8727141/235239839-334aef1e-f4c3-4f8b-b7d2-1dcaa7ffeac1.png">

Some options:
* We could default those settings to be only for the first time you open the window and remember the last size by default
* We could add another explicit setting around "remember the quake windows last size" that overrides the size from settings

@robbieejones any thoughts?

**Comment by jackbow** [comment]
Either of the options sound good to me 👍

**Comment by robbieejones** [comment]
@zachlloyd I personally prefer option 1 as it's simpler.

**Comment by zachlloyd** [comment]
@jackbow Actually, we debugged this internally, and it's already supposed to be working the way you suggest, but on some kinds of monitors there's a bug (which I'm going to try and fix).  

If you change your hotkey setting from Active Screen to Main Screen does that workaround fix it for you?

<img width="546" alt="Image 2023-04-28 at 5 43 38 PM" src="https://user-images.githubusercontent.com/8727141/235270395-0fa68a07-d7d3-4ace-8f34-d176b8a45b52.png">

**Comment by loucostello** [comment]
@zachlloyd that looks great, thanks! Two questions:

1. Does that part 1 behavior--recall of last size and location after close--work the same way after quit, as well?
2. What's the behavior across multiple MacOS Spaces?

Re question 2, I think "expected" to _me_ would mean the last size/location from any space to determine the next new window size/location on another Space. For example, if I were to relocate and resize a window in one space, switch to another space, and open a new window there, it would have the same size and location of the last one I interacted with on the previous desktop. But whatever is the norm is fine, just wouldn't want the Spaces handling to get overlooked since I'm a heavy user of them.

Totally fine if any of that is not in scope, too, just asking!

**Comment by Yonben** [comment]
Hi,
In my case, as explained in the issue I opened, mentioned above, no matter which screen I choose, it always opens on the same screen, as if it could read which screens I have, but not managing to open anywhere except the screen it's on (or my main screen when laptop is closed, or laptop screen when it's open).

Hope the extra info helps.

**Comment by zachlloyd** [comment]
FYI this is partially fixed in our latest release: v0.2023.05.09.08.03.stable_01

We now remember and reopen windows at the position and size of the last closed window.

I'm working on a setting for opening windows at a default size now

**Comment by OldSubSailor** [comment]
I do not know about all this hot key stuff; however; November 13, above the macOS window settings were shown and that is what I thought was being asked, and what I am looking for. That is when I drag to resize a window to my liking, I would like to see a way to save that size so that it returns if I close the window or if I quit the Warp application. To date, that is not happening, in that I have to resize every time that I open the application.  I had hoped that simply clicking on that check mark while in Settings would do the job, but no joy. 
Perhaps I am, or evidently I am missing something, but I had thought that going to Settings would be the natural place to adjust and set the window size.

**Comment by apolzon** [comment]
It would be great if there was also support for specific window sizes in launch configurations. Right now, when I open warp normally, I always get a full-size/maximized window (which is what I want), but if I open a launch configuration its using some random window size (about 50% of screen?)

**Comment by dannyneira** [comment]
Hi Folks, Warps Appearance Settings allow you to set a custom size for new Windows. See more in our docs https://docs.warp.dev/appearance/opacity-blurring-dimming#window-size

![CleanShot 2023-08-23 at 10 14 03](https://github.com/warpdotdev/Warp/assets/16809145/83e223c7-2c2e-4539-85e3-7cc54a4db6ba)

**Comment by apolzon** [comment]
@dannyneira - thanks, thats very helpful! I just realized today that setting works for windows created after startup, but when you first open warp, the window auto-created on startup is not respecting those settings

**Comment by dannyneira** [comment]
@apolzon Nice! From what I understand the setting only applies to new windows, but you can enable [Session Restoration](https://docs.warp.dev/features/sessions/session-restoration) which should cause Warp to remember the previous windows (size/position, tabs, panes, etc.) on startup. Hope that helps!

**Comment by OldSubSailor** [comment]
That is true. It will only create create that saved window when you again open a new window after you launch Warp.  
So you can close; the old red button; the launched window then open the window that you “created” in Appearances. (That way you only have one Warp window open)
It’s a pain, but it is better than it was before, so I look at it as a step in the right direction. 
Trav

**Comment by sergiivelykodnyi** [comment]
If it is possible, it will be better to have props to set window size in the Lunch Configuration feature. Because “Open new windows with custom size” parameters do not apply to new window which is lunched from Launch Configuration, It always launches with default Warp size (80×40).

**Comment by kallebornemark** [comment]
I would like the window size to be remembered per monitor. Every time I unplug my external monitor, causing Warp to be displayed on the laptop, it's shrunken down, and this isn't restored when the external monitor is plugged back in.

**Comment by flamadrid-jsmdg** [comment]
+1 can this be fixed? I think it seems more of a bug rather than a feature request

**Comment by Pjhochman** [comment]
Bump!

Is there any progress on this? I'm not using Warp because of this issue :(

- I need to be able to open my launch config on top of VS Code. Currently, it takes me to a new view on Mac, which is why I'm not using Warp at all.
- I need the custom window size to also apply to the launch config.
- It would be great to be able to set the absolute position (left and right). I'd like it to match my terminal size in VS Code, starting from the right and ending before the file view. The 80% width reduces Warp's total size, but it's still centered.
- It would be great to have the launch config open on the initial launch.
- It would be great if launching Warp didn't open a completely new window.

There are so many annoyances currently, which is sad. I'd go so far as to say that most devs probably use launch config, and it's missing so many features!

**Comment by nguyenvulong** [comment]
For Linux (Mint), Warp always opens the terminal window to the fullest and hide the prompt. I have to triple click on the top bar to make the prompt show. Also the windows size settings in Appearance did not help, it is always full-screen.

**Comment by dannyneira** [comment]
Hi Folks, In the [latest version of Warp](https://docs.warp.dev/getting-started/changelog#id-2024.09.26-v0.2024.09.24.08.02), the first window after launching Warp will now use a custom window size if set and when opening a [Launch Configuration](https://docs.warp.dev/features/sessions/launch-configurations), Warp now respects restored and custom window sizes. 

Please note if [Session Restoration](https://docs.warp.dev/features/sessions/session-restoration) is enabled, the size of the window(s) when closed will be restored when opening Warp.

Closing as resolved, but please let us know if the issue persists.

**Comment by tborychowski** [comment]
size only? what about the location?

**Comment by danechitoaie** [comment]
Same here, still having this issue.
If I close all warp windows and then quit the app next time I'm opening it the window is small sqare.
If I quit warp directly then next time I open it it remembers the size.

**Comment by apolzon** [comment]
This feature had been working fine for me, but as of today, with the latest update, its back to opening with a small centered window after quitting. Closing that window and opening a new one with command+n does respect my settings, however. Not sure exactly what version it broke in, but I'm currently running v0.2025.03.05.08.02.stable_02

**Comment by OldSubSailor** [comment]
Well, it is back to not being back as described above. I truly love Warp, but I am a 78 year old hobby kinda guy, and evidently Warp was not meant for me. The documentation is either written for folks who are very high above me i.e. developer pros, or  the authors are too close to their subject matter (it happens). 
Regardless, I appreciate all of you, and keep the boat on a zero bubble. 
Take care.
