### ISSUE TITLE
Restore blog RSS feed

### ISSUE THREAD

**Issue by canac** [warpdotdev/Warp#1420]
### Describe the solution you'd like?

```text
The warp.dev blog used to have an RSS feed so I could read it in Feedly. It doesn't seem to have an RSS feed anymore. It would be awesome if it could be restored because I love following along with the work you guys are doing!
```

**Comment by elviskahoro** [comment]
@canac will look into this!

**Comment by warpdotdev-dx** [comment]
Hi @canac


Just to circle back, we've added an RSS feed to our blog. ​http://www.warp.dev/blog/rss.xml

__
Danny Neira (he/him/his)
Support Engineer
www.warp.dev

--- original message ---
On July 9, 2022 at 12:20 AM MDT ***@***.*** wrote:



@canac will look into this!

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
