### ISSUE TITLE
Quake mode hotkey doesn't work on another language

### ISSUE THREAD

**Issue by ramzzzay** [warpdotdev/Warp#1423]
### Discord username (optional)

RAMZAY (Антон)#3383

### Describe the bug

```text
Quake mode hotkey doesn't work on Russian language layout. But all works fine in iTerm.
```

### To Reproduce

Steps to reproduce:
1. Set English/Polish language layout
2. Set Quake mode hotkey to option+`
3. Change layout to Russian
4. Tap option+`

### Expected behaviour

```text
Quake mode hotkey have to be called.
```

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by tkafka** [comment]
+1, same for Czech (and I suspect for every other language that maps a different character to hotkey's keyboard key).

As mentioned, iTerm somehow makes it work (does it use key's scancode instead of a mapped character in currently active keyboard layout?), but a workaround could be an option to add multiple hotkeys for the hotkey window.

**Comment by elviskahoro** [comment]
Thanks for opening this! Like @tkafka mentioned the underlying issue is #341 gonna close this in favor of that one.
