### ISSUE TITLE
More convenient urls/files behavior

### ISSUE THREAD

**Issue by rmbaad** [warpdotdev/Warp#1480]
### Describe the solution you'd like?

```text
Hi, everyone!
Thank you for the great terminal app!
I'd like to propose some thoughts about the usage of URLs and files in the Warp terminal.

1. It would be great to change the default behavior of clicking by URLs or to have a setting for it. I misclick them every time. I guess cmd+click in most cases will be more convenient.

2. I heard you are working on file opening support and maybe you'll be able to fix double click by file paths. E.g. iTerm works perfectly with it. If somebody makes a double click by file path, 99.9% they'd like to select file path :) instead of a single word. This thing makes me sad because I do it dozens of times a day.

Thank you!
```

**Comment by mnapoli** [comment]
Coming from iTerm, this bits me every time as well.

**Comment by alokedesai** [comment]
Hey there! We're in the process of switching this behavior to cmd-click. It should launch roughly in 2 weeks from now. cc @kevinyang372

**Comment by elviskahoro** [comment]
Gonna close this favor of #177 and also #659

**Comment by mnapoli** [comment]
Awwwwwesome! Thank you!

**Comment by junhyuk-prestolabs** [comment]
I removed Warp because I was not able to double-click to copy path.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/58673794/185088260-8ab5ecd1-d25e-40ed-b8a7-7f1feec8ea43.png">

If I want to select `src/assets/svgs/priceDirections/index.tsx`, I need to drag and copy.

This part is really inconvinient.
