### ISSUE TITLE
FZF + Fuzzy search / completion when pressing tab

### ISSUE THREAD

**Issue by estruyf** [warpdotdev/Warp#149]
### Is your feature request related to a problem? Please describe.

```shell
Not really a problem, but something I always use with `zsh` or `fig` is the ability to enter a part of the folder name and let the tool figure out the options.
```

### Describe the solution you'd like?

```shell
Ability to enter a part of a folder name, and let the tool figure out the options.
```

### Additional context

`cd front` would give the following options:
- frontmatter
- vscode-frontmatter
- ...

**Comment by benwaffle** [comment]
Would also be nice to have fuzzy search when searching history

**Comment by freak4pc** [comment]
For me it's a deal breaker right now unfortunately :( 
Fuzzy search is such a standard thing, that even Terminal.app basically does a solid job at it. It's immensely hard changing one's typing habits to not use it, and it's a huge downgrade.

Mainly writing to be able to track this so I can go back to using Warp, but for now I'll have to stick with iTerm until using this is possible :(

**Comment by elviskahoro** [comment]
Linking:

- #167

**Comment by iammoen** [comment]
FZF is pretty much a necessity for me these days. Use it to match git branches, cd into directories, search past command history, and I have it used in some of my zsh scripts to be able to match ssh entries etc. Ever time I come over to warp to take advantage of some of the awesome features (easily copy output of a command FTW) I end up having to go back due to my fzf usage.

**Comment by elviskahoro** [comment]
+ Propose adding FZF for searching through command prompt.

**Comment by rmbaad** [comment]
I faced the same issue.
I have a lot of projects in my working directory, and I don't remember the prefix of each of them.
E.g., I have:
`
some-namespace-api
api-tests
another-namespace-ui-library
one-more-namespace-web
`

And `zsh` with autocomplete works fine when I write "api" I get all possible folders which contain "api" in their names and shows suggest only with them, but `Warp` doesn't.
It's very uncomfortable, and it will be great if you'll think about it.

**Comment by elviskahoro** [comment]
My only gripes so far are lack of support for FZF (or other easy way to autocomplete nested files) and no easy way to bookmark and navigate between directories (so far as I could tell). In my standard setup I use FZF-Marks.

https://github.com/urbainvaes/fzf-marks

**Comment by YuraLaguta** [comment]
personally blocker for using Warp. Have to fall back to iTerm

**Comment by denisidoro** [comment]
My blockers for using Warp:
- support for fzf
- https://github.com/warpdotdev/Warp/issues/537, so that I can use:
   - [navi](https://github.com/denisidoro/navi)
   - [edit-command-line](https://unix.stackexchange.com/questions/6620/how-to-edit-command-line-in-full-screen-editor-in-zsh) in vim

**Comment by elviskahoro** [comment]
@denisidoro have you seen this?!
- https://github.com/warpdotdev/Warp/discussions/625

**Comment by robbienohra** [comment]
This would really seal the deal for me, key thing that seems to be missing.

**Comment by sgoumaz** [comment]
I'm not using FZF but FWIW (not sure if it belongs here), Fish has had fuzzy matching for completions since v2.1, and this is the main thing I miss after a few days trying out Warp.

**Comment by elviskahoro** [comment]
Will circle back with the team about this and then follow up here.

**Comment by matei** [comment]
Agreed, this is a key feature for me as well to make the transition

**Comment by elviskahoro** [comment]
From @gvko
[gvko](https://github.com/gvko)
### Describe the solution you'd like?

Eg. when I have the file `cron-zombie-pod-killer.yaml` and I write `kubectl apply -f zom` and I click `Tab`, iTerm will autocomplete the `cron-zombie-pod-killer.yaml` filename, since it finds the `zom` pattern match. 
And if there are more than 1 files that match the given pattern, it would partially autocomplete and expect more characters to know how to autocomplete.
_(see detailed examples in the attached screen recording videos)_

It would be great to see this type of feature in Warp.


### Additional context

Autocompleting by pattern match when only 1 file that matches the pattern exist in the dir:

https://user-images.githubusercontent.com/1754630/155560878-4c57497c-4273-4f46-bbd0-7d53072f90e0.mov

When more than 1 files that matches the pattern exist in the dir:

https://user-images.githubusercontent.com/1754630/155560889-de766771-5276-4f3d-8558-1d11f2728c9d.mov

Current experience in Warp:

https://user-images.githubusercontent.com/1754630/155561053-bad3295e-7384-43ef-992c-8f7cf377c9b8.mov

**Comment by elviskahoro** [comment]
From @[jrr](https://github.com/jrr) via #190 Comment: https://github.com/warpdotdev/Warp/issues/190#issuecomment-1078594251


Thanks for adding Fish support! I'm excited to combine my old favorite shell with my new favorite terminal. I noticed two things during the first ~hour with it:

### 1) History searching

Fish does this a little differently from most shells' Ctrl+R.

In Terminal.app, I can type a substring of a previous command, hit the up arrow, and recall the command. (for example, `conf` -> `vim ~/.config/fish/config.fish`)

In Warp:
 - I can type the _beginning_ substring of a command and hit the up arrow (like `v` for `vim ...`)
 - I can type an inner substring and hit Ctrl+R

This isn't super important to me -- I'm sure I'll get used to using Warp's history searching instead of fish's -- but it's definitely a speed bump.

**Comment by alokedesai** [comment]
Hey all! Just an update here: @szgupta is actively working on this feature. We hope to launch it either this week or next week. Thanks for your patience here!

**Comment by szgupta** [comment]
Hey everyone! This was released today (`v0.2022.08.31.18.11.stable_00`) -- please let us know what you think! 😄

**Comment by estruyf** [comment]
Thanks @szgupta that is great news! Will give Warp a new try.

**Comment by gvko** [comment]
Hey guys. Congrats on the great work so far.
I just tried out the feature (since I was one of the ppl who submitted [a ticket](https://github.com/warpdotdev/Warp/issues/778) for this). 

The feature works great. I'm still a bit conflicted though, since iTerm directly auto-completes the file name (see the example in [my ticket](https://github.com/warpdotdev/Warp/issues/778), whereas Warp gives you a list of suggestions of filenames to choose from.
Now, this is not a problem at all. Just a personal opinion/preference. And also, it's just a different approach of the feature, which I guess takes getting used to. 🤷‍♂️

**Comment by elviskahoro** [comment]
the example @gvko is referring to for reference:
### Describe the solution you'd like?

Eg. when I have the file `cron-zombie-pod-killer.yaml` and I write `kubectl apply -f zom` and I click `Tab`, iTerm will autocomplete the `cron-zombie-pod-killer.yaml` filename, since it finds the `zom` pattern match. 
And if there are more than 1 files that match the given pattern, it would partially autocomplete and expect more characters to know how to autocomplete.
_(see detailed examples in the attached screen recording videos)_

It would be great to see this type of feature in Warp.


### Additional context

Autocompleting by pattern match when only 1 file that matches the pattern exist in the dir:

https://user-images.githubusercontent.com/1754630/155560878-4c57497c-4273-4f46-bbd0-7d53072f90e0.mov

When more than 1 files that matches the pattern exist in the dir:

https://user-images.githubusercontent.com/1754630/155560889-de766771-5276-4f3d-8558-1d11f2728c9d.mov

Current experience in Warp:

https://user-images.githubusercontent.com/1754630/155561053-bad3295e-7384-43ef-992c-8f7cf377c9b8.mov

**Comment by szgupta** [comment]
Hey @gvko, thanks for the feedback! We're actually considering a setting that inserts the suggestion into the buffer! @elviskahoro, do we have a separate GH issue for that to track progress?

**Comment by elviskahoro** [comment]
@szgupta we don't have one.

**Comment by DevAtDawn** [comment]
@elviskahoro @szgupta id be interested in helping out with this, let me know if/when you create a new issue/pull request

**Comment by elviskahoro** [comment]
@DevAtDawn we'll comment with the link after we make it so we can get your feedback and others

**Comment by szgupta** [comment]
Let's track this discussion here #1795

**Comment by lunemec** [comment]
👋 Hi, just trying warp and it looks promising, however the ctrl-R functionality is slow/laggy on my M1 mac compared to iterm + fzf solution that is instant. 

Also the match is not the same. Example:
- I'm searching for commands using cloud_sql_proxy
  - fzf: ctrl+R, type `sql proxy` and it will immediatelly show correctly `cloud_sql_proxy`
  - warp: ctrl+R, type `sql proxy` and it will show `gcloud sql create proxy`
  
The sluggish speed in Warp may be because my zsh history is 4.2MB with ~30k records. I will give the workflows a shot and see if that can replace how I'm used to work. But since I have to actively predefine them, its not so convenient as just finding a command you know you've run 100 times before.

**Comment by piercecohen1** [comment]
I want ⌃ + R bring up my reverse search command history	with fzf instead of Warp history search. Is there any way/workaround to accomplish this?

Warp's search history only remembers the last 15 commands for me. Is there any way to change this?

**Comment by ishavitcisco** [comment]
Hey, I've read the discussion here, and started using Warp recently.
Would like to add that the ctrl+r search history does not work similar to fzf/etc.
Example:
- command in history: aaa bbb ccc
- using fzf i can search: ccc aaa 
and it will find the command
with Warp, searching "ccc aaa" will NOT find my command in history.

**Comment by lunemec** [comment]
I tried warp again, to see what is new, and I like the new command completion from history, however it doesn't search history like `fzf` - for example, I search `port-for` and I am looking for my `kubectl port-forward` history where I have tons of services to forward locally. How it works currently is not usable, and I would have to type at least `kubectl po`. 

I'm not sure I want to invest time into pre-creating my commands, because that is what history is for, you've already ran it, so why not be able to save it from history and fuzzy find it?

**Comment by freak4pc** [comment]
Just checking before reinstalling Wrap, this issue is still not solved? It's such a huge hassle. I think for many of us it's literally the only blocker to migrating. Warp wants to offer superior usability and productivity, and FZF is exactly one such tool - which should align with this product's vision.

**Comment by Goaman** [comment]
Same for me, I'm a big user of the FZF history search.
In Wrap`ctrl+R` is slow on my mac M1 and the fuzzy search of Wrap reorder my commands, which makes it less efficient to me.
Big deal breaker to me.

**Comment by OneComputerGuy** [comment]
Ugh, almost three years after it was reported and still no solution for it. We just started using fzf for pretty much everything (from git commands to fuzzy search to auto-completion) and none of the commands for fzf works (Ctrl+T, Ctrl+R, **+TAB).

Shame, I was enjoying working in Warp but this is a dealbreaker for me. Time to switch back to iTerm2 I suppose

**Comment by ishavitcisco** [comment]
Can’t you use fzf with Warp?

From: Sebastian ***@***.***>
Date: Thursday, 18 April 2024 at 17:27
To: warpdotdev/Warp ***@***.***>
Cc: Ido Shavit (ishavit) ***@***.***>, Comment ***@***.***>
Subject: Re: [warpdotdev/Warp] FZF + Fuzzy search / completion when pressing tab (#149)

Ugh, almost three years after it was reported and still no solution for it. We just started using fzf for pretty much everything (from git commands to fuzzy search to auto-completion) and none of the commands for fzf works (Ctrl+T, Ctrl+R, **+TAB).

Shame, I was enjoying working in Warp but this is a dealbreaker for me. Time to switch back to iTerm2 I suppose

**Comment by cgroening** [comment]
It still doesn't work. Is there a workaround?
