### ISSUE TITLE
Add a CLI for controlling the terminal and new windows / split panes

### ISSUE THREAD

**Issue by ranyitz** [warpdotdev/Warp#1550]
### Describe the solution you'd like?

Controlling the terminal using the CLI will enable devs to program predefined terminal experiences.

The most basic functionality would be to open a new tab and split pane.

An example of the functionality can be seen within [windows-terminal](https://docs.microsoft.com/he-il/windows/terminal/command-line-arguments?tabs=windows)

### Additional context

There is an OSS project for controlling terminal windows programmatically ([newsh](https://github.com/ranyitz/newsh)) In which there is an [issue that request to support warp](https://github.com/ranyitz/newsh/issues/35)

**Comment by warpdotdev-dx** [comment]
I think is a duplicate:
GitHub discussion on supporting a Warp scripting API: <https://github.com/warpdotdev/Warp/discussions/612>

--- original message ---
On June 25, 2022, 12:29 AM EDT ***@***.*** wrote:



Discord username (optional)

No response

Describe the solution you'd like?

Controlling the terminal using the CLI will enable devs to program predefined terminal experiences.

The most basic functionality would be to open a new tab and split pane.

An example of the functionality can be seen within [windows-terminal](https://docs.microsoft.com/he-il/windows/terminal/command-line-arguments?tabs=windows)

Is your feature request related to a problem? Please describe.

No response

Additional context

There is an OSS project for controlling terminal windows programmatically (newsh) In which there is an issue that request to support warp

Warp Internal (ignore) - linear-label:efcea52d-0ab4-4a92-a41b-93c3e244f0a0

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---
