### ISSUE TITLE
No Autocompletion for paths starting with `/`

### ISSUE THREAD

**Issue by aDotInTheVoid** [warpdotdev/warp#16]
**Describe the bug**

If a command starts with `/`, autocomplete doesn't work

**To Reproduce**

Type `/usr/bi`

Press Tab

**Expected behavior**

Autocompletes to ` /usr/bin/`

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS 10.15.7 

**Additional context**

**Comment by donaldguy** [comment]
As described, I'd suggest a better title for this issue as a bug would be something like

>Absolute path to executable (as argv0, `$0`, etc.) should autocomplete (only) without `--`

since it seems like a bug that this should work for relative paths (<code>./<kbd>Tab</kbd></code> and <code>../<kbd>Tab</kbd></code> but not absolute paths )

There is a separate feature request here for handling of more heuristic path autocompletes in the general case, because I can attest that for e.g. <code>ls <kbd>Tab</kbd></code> absolute paths and relative paths (with or without explicit `./`) work equally well, and for most other commands I tried neither works (**until** one gives an explicit `--`)

Indeed one can type on a new prompt <code>-- /usr/bi<kbd>Tab</kbd></code> and `/usr/bin/` fills accordingly, but taking this to its conclusion does not work as a workaround

<img width="225" alt="image" src="https://user-images.githubusercontent.com/43136/126082921-0f2afd93-a213-4d1b-a900-6af16f0d761c.png">

**as a workaround:**

If one in fact is not planning to use any flags (or knows them by heart, man page) and is okay bypassing shell aliases

 doing <code>\\<var>$cmd</var></code> (e.g. `\mkdir` ) will offer path completions immediately on first tab. But probably its a better workaround to just add an explicit `--`

**Comment by zheng** [comment]
Completions for commands starting with `/` will be available in our next release later this week!
