### ISSUE TITLE
Support SHIFT-Home and SHIFT-End keys for moving the cursor

### ISSUE THREAD

**Issue by talelmishali** [warpdotdev/Warp#163]
### Describe the bug

```shell
When writing a command in the Warp terminal and trying to select the text using the keyboard by pressing: Shift + Home or Shift + End - the text is not being selected.
```

### To Reproduce

Steps to reproduce:
1. Write command in the Warp terminal
2. Press Shift + Home or Shift + End

### Expected behaviour

```shell
All text to the left or to the right of the cursor should be selected.
```

### Operating System

MacOS

### OS Version

11.5.1

**Comment by elviskahoro** [comment]
### Describe the bug

I have mapped the following key combinations:
Home - Start of line
End - End of line
Shift+Home - Select to start of line
Shift+End - Select to end of line
according to this answer https://apple.stackexchange.com/a/16137

Home and End work perfectly but Shift+Home and Shift+End do nothing.
This works everywhere (Intellij, Sublime Text, Chrome browser) but doesn't appear to work in Warp.

### To Reproduce

Steps to reproduce:
1. Create or overwrite `~/Library/KeyBindings/DefaultKeyBinding.dict` with the following content:
```
{
    "\UF729"  = moveToBeginningOfLine:; // home
    "\UF72B"  = moveToEndOfLine:; // end
    "$\UF729" = moveToBeginningOfLineAndModifySelection:; // shift-home
    "$\UF72B" = moveToEndOfLineAndModifySelection:; // shift-end
}
```
2. Reboot the system (logout and login should also work)
3. Open any text editor (eg. Sublime Text) and check that Shift+Home and Shift+End work according to the **Expected behaviour** description.
4. Type some command in Warp.
5. Go to the middle of the line.
6. Press Shift+Home or Shift+End.

### Expected behaviour

Shift+Home should select all text from the beginning of line to the cursor and Shift+End should select all text from the cursor to the end of line.

### Screenshots

_No response_

### Operating System

MacOS

### OS Version

11.6

### Additional context

_No response_

**Comment by elviskahoro** [comment]
This has been marked as high priority! Will follow up here once it's a WIP

**Comment by elviskahoro** [comment]
This should be out now! Please comment if it's not working for you.
