### ISSUE TITLE
Warp is very slow so split terminal windows - getting spinning wheel

### ISSUE THREAD

**Issue by joshkerr** [warpdotdev/Warp#1724]
### Describe the bug

I'm seeing a lot of spinning beach balls on MacOS when splitting windows with processes running. For example if I have yt-dlp downloading from a video stream and I try to split the window, I get a spinning beach ball for a while and 3 to 4 seconds to get a prompt. I'm using a top of the line M1 Max Macbook Pro loaded with memory and not a lot of other things running. 

### To Reproduce

Use yt-dlp to download a stream. Split the window vertically (command D). 

### Expected behaviour

This should be much faster. iTerm2 and MacOS Terminal don't have these performance issues.

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

 v0.2022.04.01.01.37.stable_03

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
Hey @joshkerr, thanks for flagging! If I'm reading the Warp version you listed correctly, it seems like you are using a version from last April. Are you able to repro on the latest version of Warp (available here: https://www.warp.dev/). 

On a separate note, would love to hear why you've been using that specific version of Warp and whether there have been any issues with autoupdate that have prevented you from updating to the latest version

**Comment by alokedesai** [comment]
Got it, thanks for clarifying! To help me debug, are you able to repro this with a vanilla ZSH rc? 

Would you be comfortable sharing a redacted version of your zshrc with me via email?

**Comment by warpdotdev-dx** [comment]
You can quickly set up clean (Vanilla) configs by putting ZDOTDIR=/ in a ~/.zshenv file. This forces zsh to run with zero configs.
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files




You can also disable parts of your dotfiles just for Warp by using this conditional statement:
```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW


# Whatever you want to disable


##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
```


See our documentation here: 
<https://docs.warp.dev/help/known-issues#debugging>

**Comment by joshkerr** [comment]
I tried with an empty .zshrc file, and I still see the same performance issue. It made no difference.

**Comment by warpdotdev-dx** [comment]
Hi



We are working to gather configuration files to further investigate the slow bootstrap times. 



If you're comfortable, please remove any personal information and attach your redacted configuration files.


Common config file locations by shell below:


Bash = `~/.bashrc`
Zsh = `~/.zshrc`
Fish = `~/.config/fish/config.fish`

Danny Neira (he/him/his)
Support Engineer
www.warp.dev

--- original message ---
On August 19, 2022 at 10:50 AM MDT ***@***.*** wrote:



I tried with an empty .zshrc file, and I still see the same performance issue. It made no difference.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you commented.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by dannyneira** [comment]
We are working to gather configuration files to investigate the slow performance.

If you're comfortable, please remove any personal information and share your dot files with us by attaching your redacted configuration files to this issue or by emailing [feedback@warp.dev](mailto:feedback@warp.dev?subject=Performance%20-%20GH%20%23Your_Issue_Number_Here&body=For%20performance%20troubleshooting.). Be sure to append you Github Issue # in the subject line to help us track your issue.

Common config file locations by shell below:

Bash = `~/.bashrc`
Zsh = `~/.zshrc`
Fish = `~/.config/fish/config.fish`

**Comment by joshkerr** [comment]
I sent my zshrc file via email to y'all. I hope it helps.

**Comment by dannyneira** [comment]
@joshkerr After todays release, v0.2022.09.07.14.56, we're no longer able to reproduce this issue. Can you please try again after upgrade and let us know if the issues resolved. Thanks!

**Comment by joshkerr** [comment]
The issue is resolved. Much faster, no more spinning beach ball.

Sent via Superhuman ( ***@***.*** )
