### ISSUE TITLE
 Wrong shortcut displayed for A. I. Command Search

### ISSUE THREAD

**Issue by rejurime** [warpdotdev/Warp#1750]
### Discord username (optional)

rejurime#1766

### Describe the bug

The shortcut displayed for A. I. Command Search is not right in the background.

### To Reproduce

When you have no blocks several shortcuts are displayed.
Yo can go to:
1. Blocks menu
2. Clear blocks

### Expected behaviour

See the correct key combination (like the one you see on the menu).

### Screenshots

<img width="688" alt="imagen" src="https://user-images.githubusercontent.com/7131403/185987325-edd981aa-8c5f-46c4-8849-8f5302719060.png">

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.08.16.10.16.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by warpdotdev-dx** [comment]
Hi @rejurime , please give the following a try. 



Go to the Settings > Keyboard shortcuts.

Bind the A.I. Command Search to a new keybinding and click Save, this is just temporary.

"Reset to default" the A.I. Command Search keybinding and close the settings menu.

Open the View menu and see if the issue persist.



Assuming the above works, you should be able to change the keybind to your preference nd confirm its showing in the View menu. 



If the issue persist, please send a screenshot of your A.I. Command Search key binding along with the View menu open as well.

—
Danny Neira (he/him/his) 
Support Engineer
www.warp.dev
{{survey}}

--- original message ---
On August 22, 2022 at 12:01 PM MDT ***@***.*** wrote:



Discord username (optional)

rejurime#1766

Describe the bug

The shortcut displayed for A. I. Command Search is not right in the background.

To Reproduce

When you have no blocks several shortcuts are displayed.

Yo can go to:

Blocks menu

Clear blocks


Expected behaviour

See the correct key combination (like the one you see on the menu).

Screenshots


Operating System

MacOS

OS Version

12.5.1

Shell Version

zsh 5.8.1

Warp Version

v0.2022.08.16.10.16.stable_02

Additional context

No response

Does this block you from using Warp daily?

No

Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by rejurime** [comment]
Hi Danny!
I followed the steps and the issues persists.
Here are the screenshots.
<img width="708" alt="imagen" src="https://user-images.githubusercontent.com/7131403/186015030-2b98d122-d028-451c-bbd0-147032938b03.png">
<img width="280" alt="imagen" src="https://user-images.githubusercontent.com/7131403/186015115-05536ae1-bec1-49e0-b4e7-4470408b5879.png">

**Comment by warpdotdev-dx** [comment]
Thanks for giving it a try and the extra info! 



A few more things to confirm, are you using a Standard US keyboard?
Is the issue visual, as in it only affect the View menu, or does the actual keybinding not work for A.I. Command Search? 
Lasty, does it persist if you uninstall/reinstall the app?

Danny Neira (he/him/his)
Support Engineer
www.warp.dev

--- original message ---
On August 22, 2022 at 1:21 PM MDT ***@***.*** wrote:


Hi @rejurime , please give the following a try. 



Go to the Settings > Keyboard shortcuts.

Bind the A.I. Command Search to a new keybinding and click Save, this is just temporary.

"Reset to default" the A.I. Command Search keybinding and close the settings menu.

Open the View menu and see if the issue persist.



Assuming the above works, you should be able to change the keybind to your preference nd confirm its showing in the View menu. 



If the issue persist, please send a screenshot of your A.I. Command Search key binding along with the View menu open as well.

—
Danny Neira (he/him/his) 
Support Engineer
www.warp.dev
{{survey}}

--- original message ---
On August 22, 2022 at 12:01 PM MDT ***@***.*** wrote:



Discord username (optional)

rejurime#1766

Describe the bug

The shortcut displayed for A. I. Command Search is not right in the background.

To Reproduce

When you have no blocks several shortcuts are displayed.

Yo can go to:

Blocks menu

Clear blocks


Expected behaviour

See the correct key combination (like the one you see on the menu).

Screenshots


Operating System

MacOS

OS Version

12.5.1

Shell Version

zsh 5.8.1

Warp Version

v0.2022.08.16.10.16.stable_02

Additional context

No response

Does this block you from using Warp daily?

No

Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message --- 
—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by rejurime** [comment]
Hi Danny!
I use a keyboard with Spanish layout.
The last update fixed it.
Thanks! 😃

**Comment by webidsecurityrepo** [comment]
Do you have WARP working for servers ? Like openssh for example is terrible unreliable.

David

All Regards

PhD Mr David Lie

SECURE WEB PARTNER
Offcial Buisness License Norway: 92177746
Straumavegen 43, 5550 Sveio, Hordaland
Norway

Phone emergecy 4/7/465 +47 41259593
My private phone: +47 90048400
TEMP Email: ***@***.*** or SLACK Mail ***@***.***
MEETNGS https://calendly.com/securewebpartner

Part of 
WEB SECURITY (Company License Norway: 927958740 DUNS International Buisness License for US Govermenrts and Businesses 346631231)
Straumavegen 43
5550 Sveio
Norway

> 22. aug. 2022 kl. 23:03 skrev Warp Developer Experience ***@***.***>:
> 
> 
> Thanks for giving it a try and the extra info! 
> 
> 
> 
> A few more things to confirm, are you using a Standard US keyboard?
> Is the issue visual, as in it only affect the View menu, or does the actual keybinding not work for A.I. Command Search? 
> Lasty, does it persist if you uninstall/reinstall the app?
> 
> Danny Neira (he/him/his)
> Support Engineer
> www.warp.dev
> 
> --- original message ---
