### ISSUE TITLE
Launch search not finding any launch files

### ISSUE THREAD

**Issue by khanakia** [warpdotdev/Warp#1827]
### Describe the bug

I created a launch configuration but when i search for a configuation it's empty.

I followed this tutorial https://docs.warp.dev/features/session-management/launch-configurations

### To Reproduce

1. Install the new app
2. Create a new launch configuration file using this tutorial I followed this tutorial https://docs.warp.dev/features/session-management/launch-configurations
3. Now when i search for a file it does not comes up
4. Check above screenshot which shows i do have launch files exists

### Expected behaviour

Launch search should work

## Proof that launch file exists
<img width="1023" alt="Screenshot 2022-09-11 at 12 56 24 PM" src="https://user-images.githubusercontent.com/2174170/189516811-b3dc14e2-0bf6-4cb9-9e4b-d638bce000cb.png">

## Cannot find the file
<img width="1018" alt="Screenshot 2022-09-11 at 12 57 43 PM" src="https://user-images.githubusercontent.com/2174170/189516871-55f54329-35c2-4dd6-a660-7c7533467f43.png">

### Operating System

MacOS

### OS Version

12.5 (21G72)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.07.14.56.stable_00

### Additional context

I want to get it fixed

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
Hi @khanakia, I'm Danny, Support Engineer at Warp. Thanks for bringing this issue to our attention. So sorry to hear you're having issues with launch configs. I noticed if you use`~` instead of a specific path for **_cwd:_** in your yaml code, the config won't show up on the list how you described. Please see an example of some working code below:
`---
name: Default
windows:
  - tabs:
      - layout:
          cwd: /Users/<YOUR_USERNAME_HERE>
          commands:
            - exec: pwd
            - exec: ls -lathr --color=auto`

Finally, yaml can be a bit picky when it comes to spaces, can you please run your .yaml code thru [this validator](http://www.yamllint.com/) to make sure that it has the proper spaces. I hope this helps get you up and running for now. I will bring up the issue with `~` paths with the team and post any updates here.

**Comment by adamsuskin** [comment]
Hey @dannyneira. I ran into this also. The validator you provided helped me discover my issue. Maybe there's an FR in here for a yaml validator that Warp can run on yaml files in the launch configuration path?

**Comment by khanakia** [comment]
> Hi @khanakia, I'm Danny, Support Engineer at Warp. Thanks for bringing this issue to our attention. So sorry to hear you're having issues with launch configs.
> 
> I noticed if you use`~` or nothing instead of a specific path for **_cwd:_** in your yaml code, the config won't show up on the list how you described. Please see an example of some working code below:
> 
> ```
> ---
> name: Default
> windows:
>   - tabs:
>       - layout:
>           cwd: /your/path/here
>           commands:
>             - exec: ls -lathr --color=auto
> ```
> 
> Finally, yaml can be a bit picky when it comes to spaces, can you please run your .yaml code thru [this validator](http://www.yamllint.com/) to make sure that it has the proper spaces.
> 
> I hope this helps get you up and running for now. I will bring up the issue with cwd path with the team and post any updates here.

I was able to validated the yaml please check attached file

[launch_test.yaml.txt](https://github.com/warpdotdev/Warp/files/9585763/launch_test.yaml.txt)

<img width="900" alt="Screenshot 2022-09-16 at 10 03 48 PM" src="https://user-images.githubusercontent.com/2174170/190687128-41e5abac-4e27-48c2-b484-e76b28a7e9d8.png">

**Comment by dannyneira** [comment]
> Hey @dannyneira. I ran into this also. The validator you provided helped me discover my issue. Maybe there's an FR in here for a yaml validator that Warp can run on yaml files in the launch configuration path?

Yeah I can have the team look into something like this to validate launch_configs yaml files automagically

**Comment by dannyneira** [comment]
>I was able to validated the yaml please check attached file

@khanakia The  cause of your error is that the file ends in .txt instead of .yaml. Just drop the .txt at the end of your file and it should show up in the launch configuration palette `CTRL-CMD-L`.

I was able to test your launch config on my end and it worked ( just changed the path for my username, [see loom video](https://www.loom.com/share/3646e6a9c3534f5eae40ce0a916b650a), and removed the .txt extension ).

**Comment by khanakia** [comment]
@dannyneira File does not ends with txt. I added that extension so i can upload to github comment. Github does not allows you to upload yaml files

**Comment by dannyneira** [comment]
Thanks for the update @khanakia, I'll close the issue but out of curiosity happen to know what fixed it ultimately? We can update the docs to help catch this in the future.

**Comment by khanakia** [comment]
@dannyneira I am not 100% sure but i believe it was the permission issue on my home directory :).
