### ISSUE TITLE
[Feature] Custom shell support

### ISSUE THREAD

**Issue by Soromeister** [warpdotdev/Warp#1837]
### Discord username (optional)

Soromeister#1365

### Describe the solution you'd like?

```text
Have an option in Warp where you can select a custom shell to start with instead of the default system shell.
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Thanks again for your suggestion @Soromeister. Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by RumataEstor** [comment]
I'm using a GNU bash from Nix `~/.nix-profile/bin/bash` instead of Mac preinstalled `/bin/bash` and it never was a problem with iTerm2 - it allows to specify any shell I like as a part of terminal profile.
I don't think that adding specific user Nix profile path to `/etc/shells` is a correct solution, so it would be nice if Warp allowed to specify a custom shell in addition to usage of the default user shell.

**Comment by dannyneira** [comment]
Hey Folks, this feature is coming soon! Stay tuned for more info on release.

**Comment by dannyneira** [comment]
Hey Folks! You can now specify the startup shell in Warp! Go to `Settings > Features > Session` and you should see a dropdown for "Startup shell for new sessions" with options for Default, ZSH, BASH, or Custom. 

https://docs.warp.dev/getting-started/using-warp-with-shells#changing-default-shell
