### ISSUE TITLE
Requiring login should be removed

### ISSUE THREAD

**Issue by jbnunn** [warpdotdev/Warp#1838]
### Describe the solution you'd like?

```text
This is an unbelievable requirement for a terminal app. Why would I need to create a login to get to my shell? Some benefits of dropping to the terminal are to be able to quickly navigate the file system or perform functions (e.g., file copies, directory creations, project starts, networking operations), and this is a hinderance. Furthermore, it shows you don't know your audience well: terminal users are generally power users, many of whom build and work with open source projects or share the ethos of those who do. Fundamental to this ethos is a respect for privacy -- and requiring us to create an account to use this shell goes squarely against that ethos.
```

### Is your feature request related to a problem? Please describe.

```text
Requiring login caused me to delete your app.
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by Soromeister** [comment]
Hey @jbnunn, please check the [specific FAQ section](https://www.warp.dev/faq#why-is-login-required-for-a-terminal-app) for an explanation of this.

**Comment by Cerya** [comment]
I agree with @jbnunn, better solution is to have choice to disable Login and Open AI ?

**Comment by jbnunn** [comment]
Thank you @Soromeister, I have read this, but I still don't agree with the sentiment of it. I believe logging in should be optional, even if that means a reduced feature set for users who choose that option. [This quote sums it up](https://github.com/readme/featured/future-of-the-command-line) better than I can: 

> A blank screen and a blinking cursor. That’s all that greeted users when they booted up their machines in the early days of personal computing. No start menu. No icons. Just the command line.

**Comment by dannyneira** [comment]
@jbnunn We currently require login in order to enable some cloud based features, like [A.I. Command Search](https://docs.warp.dev/features/ai-command-search) along with soon to be released Team features. We feel the collaboration is what will set us apart, as it did with other tools like Google Docs, Figma, etc.

In case there was any confusion, we are *never* sending the contents of terminal commands and outputs to our servers (unless a user explicitly chooses to use our ["Block Sharing" feature](https://docs.warp.dev/features/blocks/block-actions#sharing-a-block)). 

What we currently send in regard to telemetry is listed here: https://docs.warp.dev/getting-started/privacy#exhaustive-telemetry-table.  We can reach back out if you're interested if / when we make any product changes around login and telemetry.  And thank you for sending your feature request and considering Warp. I'll post any updates here if login requirements removed.

**Comment by elviskahoro** [comment]
We're tracking this in #900
