### ISSUE TITLE
Double click on text could have better selection precision

### ISSUE THREAD

**Issue by simPod** [warpdotdev/Warp#1871]
### Describe the solution you'd like?

```text
Line   src/some/file.php
```

When I use Iterm, double clicking any where on `src/some/file.php` selects `src/some/file.php`
With warp it selects the full line `Line   src/Contract/Domain/Query/ContractList/FindContractsBillingHandler.php`

The Iterm's behaviour is IMO smarter. But TBH I don't know how their logic works exactly but is more comfortable to work with.

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by svsool** [comment]
I also noticed the difference with the following Kubernetes output for example:

```
NAME                                                             READY   STATUS      RESTARTS   AGE
pod-name-1                                                       1/1     Running     0          31h
pod-name-2                                                       1/1     Running     0          31h
```

In iTerm double click anywhere inside `pod-name-1` string will select the whole `pod-name-1` string which is very convenient, because resource names are used as part of many commands.

In Warp double click on `name` within `pod-name-1` will select just `name` and triple click will select the whole line which isn't very useful.

Due to that I have to select resource name manually via mouse selection which is way less efficient than double click.

**Comment by RhetTbull** [comment]
Yes! I came here to file this very issue. This is frankly a deal break for me. I double-click to select then copy text *all day long* from the terminal and with Warp I need to actually select and drag with mouse to get the text I want whereas with iTerm it's just a double click.

**Comment by svsool** [comment]
That's pretty hard to use Warp without better selection precision. I think this fix should be of higher priority.

A lot more unnecessary clicks than with the other terminals.

**Comment by Aivean** [comment]
The double click on a filename or a path to select (and then copy it) is a pretty common usage pattern in the terminal.

Iterm:
![iterm](https://user-images.githubusercontent.com/2865203/202083591-1a0bcfe8-2d24-4063-8387-4513e9248520.gif)

Warp:
![warp](https://user-images.githubusercontent.com/2865203/202083615-71913136-ce37-4543-aefc-0505a19619fc.gif)

**Comment by sonu-Shiva** [comment]
ITerm2:
<img width="754" alt="Screenshot 2022-11-26 at 9 32 32 PM" src="https://user-images.githubusercontent.com/11310310/204097832-290785b9-d6b4-4860-9cc1-b43f3e9e8e2d.png">
Iterm2 has a pretty wide range of customization around the text selection feature.

Having this level of customization for text selection in Warp terminal should be a high priority feature IMO.

ITerm2:
<img width="725" alt="Screenshot 2022-11-26 at 9 40 11 PM" src="https://user-images.githubusercontent.com/11310310/204098145-c9ee1fe3-4429-47c7-848d-ce61ffc41933.png">
Also, in iterm2 we can select the git branch name or the entire path on the current prompt.

Warp:
<img width="735" alt="Screenshot 2022-11-26 at 9 39 21 PM" src="https://user-images.githubusercontent.com/11310310/204098176-e6d8cf66-7f1d-424f-9a5b-d99215cb6b99.png">
But in Warp, we cannot select either the git branch name or the path visible on the prompt line.

For my use case this is the only feature lacking in Warp stopping me from completing switching over from Iterm2. Otherwise, Warp is the most powerful terminal out of the other teminals i have used so far.

Looking forward for this feature update.

**Comment by kecinzer** [comment]
+1

**Comment by yevhen-harmonizehr** [comment]
+1

**Comment by SuchonC** [comment]
+1

**Comment by remziz4** [comment]
Also becoming a dealbreaker for me. Love Warp as a concept, but the pain of not being able to easily select items with double-click the way I'm used to with iTerm makes me consider switching back. Please prioritize this!

**Comment by lrybak** [comment]
+1 That'is absolute must have for modern terminal

**Comment by sviatsom** [comment]
+1

**Comment by cajbecu** [comment]
+1

**Comment by dannyneira** [comment]
Closing as completed since smart text selection was released in recent version of Warp. 

https://docs.warp.dev/features/smart-select

Please let us know of any issues with the feature.
