### ISSUE TITLE
Clear Blocks is missing from of Keyboard shortcuts in Settings

### ISSUE THREAD

**Issue by mayel** [warpdotdev/Warp#1899]
### Describe the bug

I am trying to customise the keyboard shortcut (changing it from Cmd+K) but it doesn't appear in the list in settings.

See screenshot: 
<img width="501" alt="Screenshot 2022-09-30 at 16 15 19" src="https://user-images.githubusercontent.com/115318/193182514-d3ef8e31-79ae-4acf-b9bb-b483f59a4dde.png">

### To Reproduce

Install latest version of Warp and go to Settings

### Operating System

MacOS

### OS Version

2.6

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.09.27.08.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @mayel, I'm marking this one as a feature request. As a workaround, the Clear command or your key binding for it should help give you free space from Blocks, or `CMD-K` which actually deletes the blocks entirely.

**Comment by mayel** [comment]
Yeah I'm aware of Cmd+K, I just expected to be able to change that binding like the others 👍

**Comment by jornetsimon** [comment]
+1, I'd like to remap the command palette to CMD+K, which is not possible right now because of this.

**Comment by dannyneira** [comment]
Hey Folks, the option to change the "Clear Blocks" shortcuts has been added in recent builds of Warp!

![CleanShot 2023-04-24 at 11 39 39](https://user-images.githubusercontent.com/16809145/234074418-2bc1d982-910f-48b1-97e3-19dfcd62f478.png)

You can also clear any keyboard shortcut altogether so that it doesn't interfere with any other shortcuts you have set.
