### ISSUE TITLE
Ability to set default size for new windows

### ISSUE THREAD

**Issue by dylanwishner** [warpdotdev/Warp#19]
**Is your feature request related to a problem? Please describe.**
If I resize the Warp window, close the app, and re-launch, it defaults to its preset size. 

**Describe the solution you'd like**
An option to set the default size for newly created windows. For example, setting it to 80x24 would create a new Warp terminal window with 80 columns and 24 lines. The default size is a bit large in my opinion, so I'd love to be able to change it to something a bit smaller.

**Comment by bakerkretzmar** [comment]
Additional/alternative idea along these lines: remember the last window size and position and restore it after quitting and reopening.

**Comment by elviskahoro** [comment]
@bakerkretzmar Warp supports restoring window position upon restart but configuring it via settings still isn't supported.

**Comment by danwiesenthal** [comment]
@elviskahoro does that mean that if I command-w a window to close it, and then command-n a window to open a new one (without restarting the app) that the new window is supposed to appear where the old one was?  it doesn't do that for me.  i think that would be the desired behavior, as @bakerkretzmar suggests, and would want to add that it should persist not just after quitting and re-opening, but after closing the final window and opening a new window

**Comment by warpdotdev-dx** [comment]
Sorry about the delay on this btw!

**Comment by alokedesai** [comment]
Closing this out since we now create a window that's the same size as the last window that was opened. Please reopen if you're still experiencing issues here!

**Comment by joggienl** [comment]
Should this also work for opening Warp after completely closing it (CMD+Q)?

**Comment by joggienl** [comment]
It works when you enable this setting (which is enabled by default):

<img width="519" alt="image" src="https://user-images.githubusercontent.com/1089150/201640169-e5547c9f-b59d-4e0e-b27b-c2f7069b4444.png">

I disabled that because I personally would like to open Warp in my home directory when starting a new session. But it also remembers the window size en position.

Personally i would like to have those two settings work independently, window size and position are not the same as the directory you where in before you closed the app.
