### ISSUE TITLE
Lock movement on scroll with long outputs

### ISSUE THREAD

**Issue by enisdenjo** [warpdotdev/Warp#2016]
### Discord username (optional)

enisdenjo#0419

### Describe the solution you'd like?

If I start a command that has a **lot** of output, I naturally expect that when I start scrolling the output is locked and I can inspect the logs in the scrollpoint.

### Is your feature request related to a problem? Please describe.

There's absolutely no chance to inspect the output while commands are running, quite a bummer.

### Additional context

![Screen Recording 2022-10-27 at 17 56 48](https://user-images.githubusercontent.com/11807600/198341928-aee29cfc-e9f1-41d0-b12e-2891576376f3.gif)

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this feature request! We actually already tracking a similar request here #1355, so closing this one in favor of that existing request.
Please +1 that request as it helps us gauge interest. We will post any updates there.

**Comment by DanPotolicchio** [comment]
@dannyneira any updates with this? i was looking at the "similar request" you mentioned in 2022 and saw that is still open but i also saw that the main request there is about the lines output limit and i want to know more about the scroll thing is really annoying and i'm switching to other terminal just because of that. is there any configuration i'm missing? also i saw that thing with the scroll fixed in a gif you post on the other request, or i'm missing some config or maybe it can be a good idea to add that as a beta config if the lines limit request is preventing you guys to publish that change
