### ISSUE TITLE
Supporting older macOS?

### ISSUE THREAD

**Issue by cw1nte** [warpdotdev/Warp#2049]
### Describe the bug

Errors on startup on my 10.11.6 El Capitain machine

### To Reproduce

Install
Double click app

### OS Version

10.11.6

### Shell Version

n/a

### Warp Version

0.1.0 in Finder, cannot get version as described?

### Additional context

Logged:
Nov  4 11:39:00 ⋮ CoreServicesUIAgent[979]: error -1 while removing quarantine data on path /Applications/Warp.app/Contents/Frameworks/Sentry.framework/Headers
Nov  4 11:39:00 ⋮ CoreServicesUIAgent[979]: error -1 while removing quarantine data on path /Applications/Warp.app/Contents/Frameworks/Sentry.framework/Modules
Nov  4 11:39:00 ⋮ CoreServicesUIAgent[979]: error -1 while removing quarantine data on path /Applications/Warp.app/Contents/Frameworks/Sentry.framework/PrivateHeaders
Nov  4 11:39:00 ⋮ CoreServicesUIAgent[979]: error -1 while removing quarantine data on path /Applications/Warp.app/Contents/Frameworks/Sentry.framework/Resources
Nov  4 11:39:00 ⋮ CoreServicesUIAgent[979]: error -1 while removing quarantine data on path /Applications/Warp.app/Contents/Frameworks/Sentry.framework/Sentry
Nov  4 11:39:00 ⋮ CoreServicesUIAgent[979]: error -1 while removing quarantine data on path /Applications/Warp.app/Contents/Frameworks/Sentry.framework/Versions/Current
Nov  4 11:39:01 ⋮ com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000018.stable[17423]): Service exited due to signal: Trace/BPT trap: 5
Nov  4 11:39:01 ⋮ ReportCrash[17426]: Attempt to read info_array in pid 17423 failed, address was 7fff68e9a768
Nov  4 11:39:01 ⋮ ReportCrash[17426]: Attempt to read info_array in pid -1 failed, address was 7fff68e9a768
Nov  4 11:39:01 ⋮ ReportCrash[17426]: Attempt to read info_array in pid 17423 failed, address was 7fff68e9a768
Nov  4 11:39:01 ⋮ ReportCrash[17426]: Attempt to read info_array in pid -1 failed, address was 7fff68e9a768
Nov  4 11:39:01 ⋮ ReportCrash[17426]: Saved crash report for stable[17423] version ??? to ~/Library/Logs/DiagnosticReports/stable_2022-11-04-113901_MacName.crash

### Does this block you from using Warp daily?

Yes

**Comment by cw1nte** [comment]
Is local build likely to work? I think this older macOS is no longer supported by most tool chains...

**Comment by dannyneira** [comment]
Hi @cw1nte, Thanks for letting us know! We're sorry about this, this is not an ideal experience. We dropped support for older macOS versions when notifications were implemented. There are no current plans on the books for older macOS support due to this reason. We do hope to support Linux in the future so that may help for older OS support ([#120](https://github.com/warpdotdev/Warp/issues/120)) if this is something that interest you, please +1 that request as it helps us gauge interest, we will post any updates there. I hope that helps some.

Closing this as there are no plans for older macOS support.
