### ISSUE TITLE
AI Command Search port

### ISSUE THREAD

**Issue by day0n** [warpdotdev/Warp#2061]
### Local Shell and Version

latest

### Remote Shell and Version

zsh

### Operating System and Version

ubuntu20

### Warp Version

latest

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

What is the port of this AI command search service? I want to open the port in the server because my AI search cannot be used.

### Include shell xtrace output

ok

**Comment by dannyneira** [comment]
Hi @day0n, I'm Danny, a Support Engineer at Warp. Thanks for letting us know! We're sorry about this, this is not an ideal experience.

What I recommend is you open up access to `app.warp.dev` in order to use the A.I. Command Search feature. See our docs on the feature here: https://docs.warp.dev/features/ai-command-search
Also if you run A.I. command search on the remote server, you should only need access to that `app.warp.dev` URL on your local machine which is making the calls to the API. you should not need to open up access on the remote server.

Let me know if that helps with your issue.

**Comment by dannyneira** [comment]
Any luck with the above? @day0n
