### ISSUE TITLE
Make Signup Optional

### ISSUE THREAD

**Issue by adarsh-chauhan** [warpdotdev/Warp#2168]
### Describe the solution you'd like?

```text
The fact that someone has to signup to use an advance terminal is i believe hindering users like me to move to wrap.

I use office laptop and i am not comfortable signing up and then know some telemetry is being collected in the background.

It would be nice to have it optional.
```

### How important is this feature to you?

2

**Comment by dannyneira** [comment]
Warp currently requires a login to enable cloud-based features, like A.I. Command Search and Block Sharing, along with team features on the roadmap.

In case there was any confusion, Warp never sends the contents of terminal commands and outputs to our servers (unless a user explicitly chooses to use the "Block Sharing" feature).

Please see more on Warp's stance in regard to privacy & telemetry:
https://www.warp.dev/privacy
https://docs.warp.dev/getting-started/privacy

We plan to make telemetry optional in the near future ( next few weeks should be releasing something on this ), but as there are no plans in the near future to make login optional. We will post updates on telemetry on this thread.

**Comment by adarsh-chauhan** [comment]
@dannyneira Thank you for replying.

I believe that making core functionalities available should not require Signup.

Additional AI and sharing can be available after signup.

i think it can help increase adoption. Please see if it aligns with the product vision.

**Comment by dannyneira** [comment]
We understand your concern. Thanks for your feedback and for considering Warp!

**Comment by erikkrieg** [comment]
I was actually on my way to open a similar issue when I saw this was the most recent issue. I'd like to echo @adarsh-chauhan's sentiment. I am really curious to give warp a try but was disappointed to see when I started that I was required to login/signup. I have uninstalled warp for now, but will keep my eyes on the project hoping to see this requirement made optional because I am still really interested in trying out warp.

**Comment by lfitzpatrick** [comment]
I want to echo the sentiments shared above and add while it is correct that sharing terminal based work within a team is definitely an interesting feature, I can tell you the 5 individuals I shared this project with all had the same response: not even considerable with the requirements to send telemetry or any data.

While I can see how using this pretty awesome sounding terminal internally the security concerns of the target audience could be missed, since you are sharing data with and need to trust yourself, but we would have to do that for one of the most sensitive environments we use.

I do hope you get some great adoption and I will continue to share this project out.

**Comment by dannyneira** [comment]
Closing this one in favor of existing issue #900. Please +1 and discuss that request as it helps us gauge interest. We will post any updates there.

**Comment by mbrasch** [comment]
I am also absolutely against compulsory registration. As long as this exists, I will not try Warp. This compulsory registration seems very frivolous.
