### ISSUE TITLE
When inside the Ruby irb or Ruby on Rails console I cant navigate using option arrow (to jump between strings) and cant alt click to change cursor position

### ISSUE THREAD

**Issue by feliperaul** [warpdotdev/Warp#2180]
### Describe the bug

When inside the Ruby irb or Ruby on Rails console I cant navigate using option arrow (to jump between strings) and cant alt click to change cursor position

### To Reproduce

In any rails console or ruby IRB (ruby 3.1.1p18), I cant navigate using option arrow (to jump between strings) and cant alt click to change cursor position

It works just fine in iTerm2 or mac os Terminal

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi Felipe, I'm Danny, a Support Engineer at Warp. Thanks for letting us know! We're sorry about this, this is not an ideal experience. Due to how our input editor and Blocks work, we don't support Warp functions inside of subshells like ipython, irb, psql, etc. So those just run within a single Block at the moment and lose the mouse/text editor-like functions. 

There is an open issue here for requesting this support here #64. Please +1 that request as it helps us gauge interest. We will post any updates there. Closing this one as a duplicate for subshell support request.
