### ISSUE TITLE
Right Click to show all windows that are minimized

### ISSUE THREAD

**Issue by Sereja3578** [warpdotdev/Warp#2231]
### Describe the bug

On my mac os monteray 12.5.1 if i have more than one window i cant minimize one of it because it's disappear after i minimize it and i can't find it by cmd + tab or any other way. First window however still possible to minimize and open again. So i can't have 2 or more windows and minimize when i need it some one of them.

### To Reproduce

Open terminal.
Create 2 windows.
Minimize one of it.

### Expected behaviour

When i minimize one of the windows i can open it again

### Screenshots

I want to see here all my opened windows
![image](https://user-images.githubusercontent.com/12445302/204007789-f6e3048d-5fff-4e10-9d91-acb3b2596d1f.png)

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

3.2.57

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi So sorry about this! As a workaround, please right-click and show all windows to show the hidden windows that minimized

**Comment by dannyneira** [comment]
Add the option to right-click Warp icon and to show the windows as with chrome or other terminal apps.

![CleanShot 2022-11-28 at 13 53 22](https://user-images.githubusercontent.com/16809145/204378663-3b278fca-c0a1-4687-aeca-cb87fce38853.png)

**Comment by Sereja3578** [comment]
> changing to feature request. Add the option to right-click Warp icon and to show the windows as with chrome or other terminal apps.
> 
> ![CleanShot 2022-11-28 at 13 53 22](https://user-images.githubusercontent.com/16809145/204378663-3b278fca-c0a1-4687-aeca-cb87fce38853.png)

It will be cool)

**Comment by Sereja3578** [comment]
> Hi So sorry about this! Please try using [Session Navigation](https://docs.warp.dev/features/sessions/session-navigation) or right-click the Warp icon and select 'show all windows' as a workaround.

I tried to find windows with 'show all windows' but it didn't work. But Session Navigation is good way for now)

**Comment by dannyneira** [comment]
Hey Folks, I believe "Show all windows" should now show the minimized windows at the bottom, the open/maximized windows will be at the top portion of the show all windows screen. This is now in line with the default behavior of apps like Chrome.

https://user-images.githubusercontent.com/16809145/225418729-4a830363-0418-45d5-aee5-ab77dc77e5a5.mp4

Closing as resolved, but please feel free to reopen if you're not setting the same. Also, note that the Warps [Session Navigation](https://docs.warp.dev/features/sessions/session-navigation) feature is also available to help with this use case.

Closing as resolved since this feature is now launched.
