### ISSUE TITLE
ssh to VSI OpenVMS host returns the error "exec request failed on channel 1"

### ISSUE THREAD

**Issue by andrewleigh** [warpdotdev/Warp#2280]
### Describe the bug

exec request failed on channel 1

The above error returned when using running ssh to login to a VSI OpenVMS Server.  If I issue the same command from macOS Terminal or from Termius.app the login completes ok.

If I try to login to a Linux server with ssh works fine.

### To Reproduce

ssh user@vmshost.domain

### Expected behaviour

The login should complete without error

### Screenshots

ssh -oKexAlgorithms=+diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-rsa aleigh@tms4.urban.prv

 Welcome to VMS Software, Inc. OpenVMS (TM) IA64 Operating System, V8.4-2L1
aleigh@tms4.urban.prv's password:
exec request failed on channel 1

### Operating System

MacOS

### OS Version

13.01

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.29.08.03.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment]
@andrewleigh Hey, sorry you're experiencing issues - our SSH wrapper (which enables Warp features like blocks for remote sessions) creates an "exec"-style SSH session (as opposed to an interactive one), and it seems like your remote host doesn't permit that?

You should be able to work around this by either disabling our SSH wrapper in Settings > Features, or by explicitly using `/usr/bin/ssh` (instead of `ssh`, which invokes our SSH wrapper function when the feature is enabled).

**Comment by andrewleigh** [comment]
Turning off the "Warp SSH Wrapper" in preferences allows the ssh to work correctly.

Thank you for your help.
