### ISSUE TITLE
When connecting via ssh, auto-completion suggests incorrect command syntax

### ISSUE THREAD

**Issue by san-msdata** [warpdotdev/Warp#2424]
### Describe the bug

Auto-completion for ssh suggests invalid command format - ssh **host_name**,**IP**

<img width="738" alt="image" src="https://user-images.githubusercontent.com/59726367/210035735-1800b8f6-7230-4564-a9a8-744bcc3d04a8.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/59726367/210035819-125a3e03-154b-457d-afe6-f65d96fe2995.png">

### To Reproduce

1. type ssh _003_ (something corresponding to the name of the ssh connections used) and press Tab
2. choose one of the proposed connections

### Expected behaviour

1. keep IP address info in tooltip
2. instead of ssh **host_name**,**IP** insert ssh **host_name**

### Operating System

MacOS

### OS Version

13.1 (22C65)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Sorry about this, thanks for letting us know @san-msdata I wasn't able to repro this, but we're working on ssh improvements in general so we'll post any updates on this thread.

Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by fboaventura** [comment]
Let me know if you want a new issue for this, but since it is related to ssh auto-completion issues, I thought it would fit here.

SSH auto-completion looks into the `known_hosts`, even when the file is encrypted. It adds the hosts defined in the `~/.ssh/config` by the end of the (really big) list of the known_hosts but it will not parse and add the hosts set on any of the [included](https://man.openbsd.org/ssh_config#Include) configs.

![ss 2023-01-19 at 12 12 42](https://user-images.githubusercontent.com/54273/213482452-2986f42a-f12e-4876-8c61-7fe81a46a2f4.png)

**Comment by san-msdata** [comment]
Thank you, the reason was that ~/.ssh/known_hosts contained such links to hosts. Can be closed.
<img width="376" alt="SCR-20230122-we5" src="https://user-images.githubusercontent.com/59726367/213938475-bb47ea1a-a9d6-4fc8-80a2-92c091e41f70.png">
