### ISSUE TITLE
Can't write `#` character in vim 

### ISSUE THREAD

**Issue by fullheart** [warpdotdev/Warp#2442]
### Describe the bug

I open with `vim` a file and switch with `i` in Insert mode. Then I'll add a `#` character. But nothing happens (the character doesn't appear). But all other characters I can write.

### To Reproduce

1. Open `Warp`
2. Open vim `vim test.txt`
3. Switch to Insert mode by typing `i` key
4. Try to insert `#` character

### Expected behaviour

The `#` character should appear.

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Additional context

- In the default Mac terminal I can write the `#` character in vim.
- I use the `Swiss German` keyboard input scheme

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by fullheart** [comment]
A **workaround** is to copy this character from somewhere and paste it in vim.

**Comment by dannyneira** [comment]
Thanks for letting us know @fullheart, I wasn't able to repro this one and I think it may be related to a lack of international kb support at this time #320. Please sub to that issue and :+1: for any updates. 

The only workaround I can think of is possibly changing the kb scheme to US.

Closing this one as a duplicate due to international kb support.
