### ISSUE TITLE
On the Settings/Appearance/Text page, only part of the font name is visible

### ISSUE THREAD

**Issue by yilongdong** [warpdotdev/Warp#2517]
### Describe the bug

![image](https://user-images.githubusercontent.com/62591650/213194607-c4efc8c7-15cc-4cf7-938b-205343b26342.png)

As shown above, I can only see part of the font name.

### To Reproduce

Settings ==> Appearance ==> Text/Terminal font

### Expected behaviour

the font name can be seen in full.

### Screenshots

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/62591650/213196371-5912b6cb-2f0d-465b-b1f6-b38e04c47c93.png">

### Operating System

None

### OS Version

macOS Monterey 12.5.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2023.01.10.08.02.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
Great call out! Thanks @yilongdong

**Comment by dannyneira** [comment]
Hi @yilongdong this issue is resolved in the latest versions of Warp, In some cases where the window size is smaller, you may not see the full name of the font, but as along as the window is big enough you should see the full name of the font. We also added a search to the font so you can find you preferred font easily.


https://github.com/user-attachments/assets/7c40bc2d-47f0-4505-a958-0cebb89d5609
