### ISSUE TITLE
Not able to auto-complete pod name for kubectl logs <name>

### ISSUE THREAD

**Issue by NicolaiSchmid** [warpdotdev/Warp#2525]
### Describe the bug

When trying access the logs `kubectl logs back<TAB>` autocompletion just opens the prompt for a local path and is not querying the kubectl autocompletion, I have setup in my zshrc

### To Reproduce

Autocompleting a pod for `kubectl get pod bac<TAB>` works, but not for logs.

### Screenshots

![grafik](https://user-images.githubusercontent.com/12787309/213475345-98ab7860-8fdc-475e-aeb2-29c2950070f4.png)

![grafik](https://user-images.githubusercontent.com/12787309/213476066-45e6758b-0fcd-4bab-95cb-e48c6d05dea5.png)

### Operating System

MacOS

### OS Version

13.01

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2023.01.10.08.02.stable_01

### Additional context

I removed my custom .zshrc, so it should be clean environment

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, I think this may be due to the fact that Warp isn't using the zsh kubectl auto-completion, it has its own completion specs, which appears to not be working for the logs sub command.

Please sub to this discussion for updates on when we improve completions. https://github.com/warpdotdev/Warp/issues/654

Closing in favor of the discussion.
