### ISSUE TITLE
Focus follows mouse/Hover focus

### ISSUE THREAD

**Issue by jmkawooya** [warpdotdev/Warp#2551]
### Describe the solution you'd like?

```text
Focus on pane/window with mouse hover.

The only thing keeping me from switching to Warp 100%
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @jmkawooya , if anyone else interested, please 👍 this request to help us gauge how many are interested in it.

**Comment by SilentGlasses** [comment]
**Please make this an optional feature**. Not everyone wants things to just switch because the mouse hovers over.

I wish the OP would expand on exactly what the use case is.

**Comment by conradwt** [comment]
For me, this is a feature that I have been looking for since working with X11.  It speeds up window selection for me because I'm removing the extra step of having to click before typing.  In the default macOS Terminal.app, one can enable this functionality using:

```zsh
defaults write com.apple.Terminal FocusFollowsMouse -string YES
```

Note:  I had to quit and restart the Terminal.app and this functionality worked like a charm.

To this diable this functionality, one must do the following:

```zsh
defaults write com.apple.Terminal FocusFollowsMouse -string NO
```

**Comment by peter-kehl** [comment]
FYI The ("ancient") X11 window managers have had this, because it's ergonomic: less mouse clicks.

(Yes, you may have an unintentional switch to a different window, or you may type a password/token/sensitive data into a wrong application or make it visible - but there are costs and disadvantages to every choice.)

GNOME supports this, too, with Tweaks application:
![image](https://github.com/user-attachments/assets/c4c0976c-c282-4eb7-8777-e9b7718172ef)

**Comment by zachlloyd** [comment]
<img width="701" alt="Screenshot 2024-11-29 at 8 21 03 PM" src="https://github.com/user-attachments/assets/16074bfa-00cf-484d-9247-0669e09f1f4d">

This is implemented - let me know if you see any issues.
