### ISSUE TITLE
AI Generated Command should be copyable 

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#2553]
### Describe the solution you'd like?

```text
"""
would be nice if one could mouse select-> copy the text in the suggested command.
"""
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
@karatekaneen as a stopgap to selecting only certain text, you can copy the entire response with the icon on the bottom right. 

![CleanShot 2023-03-29 at 17 02 05](https://user-images.githubusercontent.com/16809145/228686970-60a91e36-1a73-44a0-84b5-27ad75add4cc.png)

**Comment by karatekaneen** [comment]
@dannyneira Yes, that's what I'm currently using but sometimes the answers can be a bit to verbose and you only need a part of the description or the code. 
So my current workflow is just to copy everything into a new editor tab, grab the piece I need and discard the rest.

Super nice feature otherwise btw. Love having the integration within Warp

**Comment by dannyneira** [comment]
Hey Folks, We're working on improvements to the Warp AI chat experience, which would include the ability to select/copy the text. No firm eta, but we'll post any updates on this thread.

**Comment by dannyneira** [comment]
Hey folks it's possible to copy commands in agent mode. We're also working on improving the whole output to be copyable.

Closing as completed .
