### ISSUE TITLE
Support keyboard shortcuts for scrolling up/down terminal output

### ISSUE THREAD

**Issue by Integralist** [warpdotdev/Warp#2688]
### Describe the solution you'd like?

Keyboard shortcuts for scrolling up/down the terminal output like when using the mouse.

### Is your feature request related to a problem? Please describe.

I'm used to being able to scroll the terminal output using keyboard shortcuts (this is the defaul behaviour in both tmux and Zellij) and I just find it tedious to have to take my hands off my keyboard to scroll with my mouse.

I know I can use Command+<arrow up/down> to jump up to specific commands but I'm specifically looking for a way to easily scroll the output of a specific command (e.g. when running a program's test suite and you have lots of failing tests that scroll off the screen). Yes, I can use the mouse but I'd rather use keyboard shortcuts.

Thanks!

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request, I really like this idea and Warp doesn't currently have option to scroll with keyboard within a block output, only mouse.

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by robertarles** [comment]
I would love this feature. I miss the iTerm features fn+arrow to scroll through lines, and fn+shift+arrow to scroll through "chunks"

**Comment by jyrodrigues** [comment]
Would be amazing if one could set / customize how to do that (e.g. `ctrl+j`/`ctrl+k`)!

**Comment by dannyneira** [comment]
As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, you can now set keybinds for scrolling up/down one line in the terminal output.

![CleanShot 2023-09-21 at 13 22 13](https://github.com/warpdotdev/Warp/assets/16809145/5bf5dc34-ba62-48ad-acad-aea1463ae791)

Closing as completed, but please let us know if any issues.

**Comment by pavelloz** [comment]
How about scrolling one page? Scrolling test fail logs or logs in general line by line is not feasible.

**Comment by szgupta** [comment]
@pavelloz you should be able to scroll the terminal screen "page-by-page" via page-up/page-down. You'll need to make sure the blocklist is focused, rather than the input (which also supports page-by-page scrolling).

Here's a demo: https://www.loom.com/share/1e00324164514178846145d28988f398

**Comment by pavelloz** [comment]
Hey @szgupta ,

You are correct, in normal circumstances it works great!

It something to do with test runner (**[react test library](https://testing-library.com/docs/react-testing-library/intro/) in watch mode**) that makes it impossible to scroll. I dont know how its possible, because mouse scroll works, one line scroll works, but pgup/pgdn does not. 

For what its worth, pgup/pgdown is working correctly in this scenario in mac os built in terminal and i can only assume its also working in iterm.

**Comment by szgupta** [comment]
I see. Do you mind attaching a screen recording of the problem in Warp, as well as how it works in the MacOS Terminal app?

**Comment by pavelloz** [comment]
Sorry for the delay, i tried to find a good software that would show what keys im clicking... but failed. You have to trust me and imagine im pressing fn+up / fn+down to trigger pgup/pgdown on mac :)

Left side: Terminal
Right side: Warp

I didnt include iterm2 because i dont use it, but in default settings (i installed it and never configured it, so it might be causing that) it also fails to scroll up, for what its worth. 

https://github.com/user-attachments/assets/43b5d00c-0ca1-4604-a9c5-bfd7ba7c6b11

**Comment by sauron918** [comment]
> you should be able to scroll the terminal screen "page-by-page" via page-up/page-down

Yes, but how about scrolling using [Home], [End] keys? It will still scroll the entire terminal window, not the focused block. So the navigation in general is quite confusing

**Comment by timdp** [comment]
In iTerm, I personally use Shift+PgUp. I was thrown off by this not working in Warp.
