### ISSUE TITLE
Separate blocks for ssh, docker internal shell too.

### ISSUE THREAD

**Issue by wangmir** [warpdotdev/Warp#2715]
### Describe the solution you'd like?

```text
It's simple. When I logged in to the docker or ssh. Block separation of warp is not working.

If it is available, it will be much useful :)
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting, so when you enable the SSH Wrapper in Warp it should continue to show the blocks within SSH sessions. From the Command Palette (CMD-P) just 'Enable the SSH Wrapper', or by going to `Settings > Features` and enable it there. See more here: https://docs.warp.dev/features/ssh

Keep in mind some SSH sessions may not fully work with Warp, see more here: 
https://docs.warp.dev/help/known-issues#ssh
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

https://user-images.githubusercontent.com/16809145/221692730-c649081e-946f-4734-9e3b-c328c07a5756.mp4

Closing as completed since this feature is already in place.

**Comment by wangmir** [comment]
@dannyneira hmm yes, I thought that ssh will be similar to docker, but I'm facing this issue when I use shell k8s login or docker login like 

`kubectl exec -it ubuntu-test -- /bin/bash`
 
So, it is not supporting right?

**Comment by dannyneira** [comment]
@wangmir It's being worked on under the Subshell support issue here: https://github.com/warpdotdev/Warp/issues/64

Essentially we're trying to get all major subshells to retain Warp features like Blocks and Completions. Including Docket, Python, etc.
