### ISSUE TITLE
Search within a block

### ISSUE THREAD

**Issue by jonyen** [warpdotdev/Warp#2724]
### Describe the solution you'd like?

```text
It would be really convenient to right-click on a block, then do a search within just that block. As it is, I believe search only works for the entire terminal tab.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @jonyen Thanks for taking the time to submit. So Warp's find feature allows to "Find in selected block" which will only search on the Block you currently have selected. See my demo below and docs for more: https://docs.warp.dev/features/find

![CleanShot 2023-02-28 at 11 10 18](https://user-images.githubusercontent.com/16809145/221942712-9205f0f4-752a-4681-8b95-f6f45dbcf443.gif)

Closing as completed since the feature already exists.

**Comment by jonyen** [comment]
Thanks @dannyneira ! This is awesome! It is a little bit unintuitive, as I would like to see the find command when I right-click on the block, but this works.
