### ISSUE TITLE
Add the ability to highlight branch name

### ISSUE THREAD

**Issue by TylerKnvpp** [warpdotdev/Warp#2739]
### Describe the solution you'd like?

```text
It would be nice to be able to highlight and copy the directory line / git branch. The editor does not always predict the correct branch when pushing to git.
```

### Additional context

![Screenshot 2023-03-03 at 12 05 28 PM](https://user-images.githubusercontent.com/43887092/222783585-090636ab-2790-4ac5-8156-1b5ba9a878d7.png)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @TylerKnvpp Thanks for submitting! Warp already has the option to copy the git branch and working directory, unfortunately not via selection, but with a right-click. Please see more on this here: https://docs.warp.dev/features/prompt

![CleanShot 2023-03-03 at 12 59 57](https://user-images.githubusercontent.com/16809145/222816010-b487d17f-d2a0-4f11-ab70-f1690afb1aba.png)

![CleanShot 2023-03-03 at 13 12 18](https://user-images.githubusercontent.com/16809145/222818113-8573c353-17c3-4243-a71e-8bceec82ae7f.gif)

Closing since a feature already exists for this use case.

**Comment by elviskahoro** [comment]
You can also copy the git branch using the command palette
