### ISSUE TITLE
Failing command over SSH logs out the remote session

### ISSUE THREAD

**Issue by atillier** [warpdotdev/Warp#2745]
### Describe the bug

When logged in over an SSH session if a command fails I am logged out of it. 

### To Reproduce

SSH to any host and run a failing command. 

### Expected behaviour

I shouldn't be logged out

### Screenshots

<img width="596" alt="image" src="https://user-images.githubusercontent.com/14177484/223472584-59277c08-1721-414c-acb8-8b8fc8a2ad6d.png">

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

SZH 5.8.1

### Warp Version

v0.2023.02.28.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @atillier  Sorry to hear about this ssh issue, seems to be failing since the folder doesn't exist, is `ll` an alias for `ls -l`? type in `which ll` and comfirm this. If that's true using `ll` and still fails I suggest disabling the SSH wrapper in the `Settings > Features` as a workaround as it seems to be disconnecting on a failed command.

**Comment by atillier** [comment]
Thanks for your reply. 

After digging in it was a problem on my servers where errexit was turned on. Had to turn it off on my remote terminals and issue solved. Not a Warp problem at all!
