### ISSUE TITLE
Prompt should be selectable 

### ISSUE THREAD

**Issue by jake-sager** [warpdotdev/Warp#2770]
### Describe the solution you'd like?

```text
You should be able to highlight and copy the prompt like any other text on screen.
```

### Is your feature request related to a problem? Please describe.

```text
I often want to copy my git branch from the prompt, but can't in warp.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @jake-sager Thanks for submitting, there are some options when you right-click the prompt, which include things like `copy prompt` or `Copy Git Branch`. Please see more about Warps Default prompt in our docs. https://docs.warp.dev/features/prompt

![CleanShot 2023-03-13 at 16 39 42](https://user-images.githubusercontent.com/16809145/224848751-81dc9731-60e3-4b8c-931b-53d17c4bf5c3.png)


Given how Warps input editor and default prompt work differently than other Terminals, we've included these options to help with the use case you mentioned. I hope this helps! 

Closing as not planned since the use case is covered with the existing feature.

**Comment by kg-currenxie** [comment]
It's not very intuitive that its hidden in a right-click menu..
Also, i might not need my full git branch or full prompt. For example our branches have a ticket number in it. 
I often just wanna click-drag-select the number quickly

Example:
`~/some/folder git:(xx-12419-my-branch)`
