### ISSUE TITLE
Fig integration

### ISSUE THREAD

**Issue by git-GB** [warpdotdev/Warp#2826]
Warp is a great terminal and would be much better with fig integration. This is the only feature that’s holding me back from using warp on a daily basis.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Fig is an awesome project, kudos to them for building something that dramatically improves developer experience. https://github.com/warpdotdev/Warp#open-source-dependencies

In terms of the completions themselves, we actually implemented their specs (Dec 2021) into Warp (we had to generate a Rust equivalent). More contributions and dev tools have likely been added since then but we plan on creating our own open-source spec (in Rust).
https://docs.warp.dev/help/changelog

When it comes to the actual command entry experience, we definitely have lots of room to grow and are looking forward to improving it over the next few months. See here:
- https://github.com/warpdotdev/Warp/milestone/3

You're specific suggestion of being able to navigate through completions menu using the arrow keys is here:
- #192
