### ISSUE TITLE
"Insert suggested command" via command palette and/or keyboard shortcut

### ISSUE THREAD

**Issue by colinknebl** [warpdotdev/Warp#2841]
### Describe the solution you'd like?

```text
The "Insert suggested command" feature is great. A possible improvement is to insert the command via the command palette. Or maybe a keyboard shortcut that inputs and executes the command. 

Ideally, the user could insert and run the suggested command without using the mouse.
```

### Is your feature request related to a problem? Please describe.

```text
The problem is switching between the keyboard and mouse to run the suggested command.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @colinknebl, Thanks for this feature request! 

By some chance, you're referring to the AI Command Search or Auto-Suggestions? For those AI Command Search, you can press `CMD-ENTER` to accept then `ENTER` to run it. For Auto-Suggestions based on the history you can press the `RIGHT` arrow to accept and `ENTER`. 

For Warp AI, once you manually insert the command you can press `ENTER` to run it, but there are certainly some improvements we can make here to help users navigate the sections with KB instead of a mouse.

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by colinknebl** [comment]
Hi @dannyneira, thank you for your response! 

I'm referring to these types of suggestions (I think these are the Auto-Suggestions):
<img width="234" alt="Screen Shot 2023-04-03 at 10 02 20 AM" src="https://user-images.githubusercontent.com/24233575/229533054-181991ee-71ba-42df-bd03-f7408c169c61.png">

I just double checked, and I do find that I can press the `RIGHT` arrow to accept this suggestion immediately after it is suggested (i.e., as the next command). That seems to work well for the most part. I never noticed that - maybe I was on an older version? I'm on the latest now and it looks good! Thanks again!

**Comment by dannyneira** [comment]
Great! thanks for confirming, closing this one as resolved since the shortcut already exists.
