### ISSUE TITLE
Issue with PS1 message in Oh-My-Bash shell using Wrap app

### ISSUE THREAD

**Issue by ddhh8023** [warpdotdev/Warp#2858]
### Discord username (optional)

ddhh8023

### Describe the bug

I am currently using the Wrap app and have set oh-my-bash as my default shell. However, I have encountered an issue where the PS1 message persists even after executing a command in the bash shell. Whenever I enter a command, the next command line always starts with the PS1 message, which is not expected behavior.

### To Reproduce

1. Install the Wrap app and set oh-my-bash as the default shell
2. Open the terminal and enter any command
3. Observe that the next command line starts with the PS1 message.

### Expected behaviour

Upon executing a command, the PS1 message should disappear and the next command line should start fresh.

### Screenshots

The PS1 message persists even after executing a command, causing inconvenience and cluttering the terminal.
![Snipaste_2023-03-31_10-11-26](https://user-images.githubusercontent.com/28582728/229005159-d8b93715-2179-4601-9153-9840cb6515b6.png)

### Operating System

None

### OS Version

13.2.1

### Shell Version

5.2.15

### Warp Version

v0.2023.03.28.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @ddhh8023 Sorry this is a blocker for you, currently Warp only supports 3 shells, BASH, ZSH, and FISH.

Please see our docs for more info on how to set them up ( you can also set one of them up in just Warp, and keep oh-my-bash  as default for other terminals ) https://docs.warp.dev/getting-started/using-warp-with-shells

I'm closing as duplicate since we are tracking other shell support on this GH here https://github.com/warpdotdev/Warp/issues/880

Please 👍 and comment on that request to help us gauge interest in other shell support.
