### ISSUE TITLE
arrow up not working as expected with ipython

### ISSUE THREAD

**Issue by zhangyuz** [warpdotdev/Warp#2878]
### Describe the bug

run ipython in warp, arrow up not working as last expresion, but choosing last block.

### To Reproduce

ipython
Python 3.8.13 (default, Mar 28 2022, 06:16:26)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import openai

In [2]: completion = openai.Completion.create(model="ada", prompt="Hello world")

In [3]: completion
Out[3]:
<OpenAIObject text_completion id=cmpl-71aiT7ZRwzbGTQI6pEBn6Av3dmqTs at 0x7f9f238e3090> JSON: {
  "choices": [
    {
      "finish_reason": "length",
      "index": 0,
      "logprobs": null,
      "text": " to say this- my baby \u201cBehold thy son\u201d is even"
    }
  ],
  "created": 1680613821,
  "id": "cmpl-71aiT7ZRwzbGTQI6pEBn6Av3dmqTs",
  "model": "ada",
  "object": "text_completion",
  "usage": {
    "completion_tokens": 16,
    "prompt_tokens": 2,
    "total_tokens": 18
  }
}

press up key , not show last expression, but scroll last block

### Operating System

MacOS

### Warp Version

v0.2023.03.28.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by alokedesai** [comment]
Hey @zhangyuz, thanks for filing! Would you be able to send a video of this happening? When you hit the up arrow is there a border around the running block? If you hit `escape` before running does up arrow work properly?

**Comment by dannyneira** [comment]
Hey @zhangyuz Please see my example below, while running ipython, if the block you're in is selected (highlighted blue), `UP/DOWN` arrows will navigate thru the blocks. If the current ipython block isn't selected, then the `UP/DOWN` should navigate the previous commands within the current block. You can deselect(remove blue highlight) a block with `ESC` in order to enter the currently running ipython block.

https://user-images.githubusercontent.com/16809145/229845604-d400e5a7-916a-4ae4-9a83-b7aefca8157b.mp4

Also, we're working on subshell support which should bring more Warp features (like history) into subshells like ipython in the future, you can track the progress here #64 

Closing this as this is known behavior and being tracked in the issue above.
