### ISSUE TITLE
Load a different shell of choice in a new tab / window

### ISSUE THREAD

**Issue by Noffica** [warpdotdev/Warp#2920]
### Describe the solution you'd like?

[Tabby](https://github.com/eugeny/tabby) allows for (an installed) shell of choice, other than the default shell, to be loaded in a new tab / window. I would like this feature to be added to Warp.

See https://imgur.com/a/mOpcyXb for a screenshot of Tabby's relevant preferences section.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @Noffica Thanks for submitting! 

This feature already exists in Warp, just go to `Settings > Features > Session` and select the Startup Shell for new Sessions:

![CleanShot 2023-04-11 at 14 03 54](https://user-images.githubusercontent.com/16809145/231276303-98a29899-e318-49cd-99b9-83f284a322d8.png)

https://docs.warp.dev/getting-started/using-warp-with-shells#changing-default-shell

Closing as completed since this feature exists, but please let us know if any issues with the feature.

**Comment by Noffica** [comment]
This is definitely useful, thank you. However, this option forces the same shell for each new tab/window; whereas my intent is to allow the user to choose amongst bash/zsh/etc. for each new tab/window.
