### ISSUE TITLE
Custom auto-completion doesn't work in Warp

### ISSUE THREAD

**Issue by lubokkanev** [warpdotdev/Warp#2922]
### Describe the bug

Using the `complete` built-in, a custom auto-completion can be set up. In Warp this doesn't work.

### To Reproduce

Run `complete -W "warp" ls` then do `ls <Tab>`

### Expected behavior

"warp" should've been completed after the `ls` command, but the usual completions appear in Warp.

### Screenshots

![Screenshot 2023-04-11 at 15 34 32](https://user-images.githubusercontent.com/10982982/231163810-8e6816f2-9ce9-4a9a-b505-81d1118f9f78.png)
![Screenshot 2023-04-11 at 15 34 42](https://user-images.githubusercontent.com/10982982/231163813-d019aead-cd72-4e5e-b632-a1a403a7a2be.png)

### Operating System

MacOS

### OS Version

13.1

### Shell Version

5.2.15

### Warp Version

2023.04.04

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp-specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @lubokkanev At this time, [Warp doesn't support 3rd party or other autocompletion tools/plugins](https://docs.warp.dev/help/known-issues#list-of-incompatible-tools). In general, we've chosen to implement our own completions spec which we may be opening up for open-source contributions. For the time being, you can submit any missing completions here: https://github.com/warpdotdev/Warp/discussions/652

Please comment and 👍 those discussions so that we can gauge the impact/interest in these features.

And track the discussion on supporting shell completions like (zsh completions) here: https://github.com/warpdotdev/Warp/discussions/434

Closing as duplicate since there are existing discussions on the topic.

**Comment by lubokkanev** [comment]
Thanks. Can we setups custom completions in Warp somehow?
