### ISSUE TITLE
clear comman not work

### ISSUE THREAD

**Issue by bingheGT** [warpdotdev/Warp#2930]
### Describe the bug

I can't clear all content using 'clear' command when I swith to root user;

### To Reproduce

1. log in server;
2. do something in comman user;
3. sudo su;
4. clear;
5. the content produced in step 2 can not be cleared;

### Screenshots

<img width="827" alt="image" src="https://user-images.githubusercontent.com/23148383/231928849-165888e9-9b4c-4d36-80bc-fa184d0c147d.png">

### Operating System

None

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
@bingheGT Thanks for letting us know, I noticed you mentioned the same happens on other terminals, were you expecting different results in Warp? AFAIK when you're in `sudo` mode, the blocks don't function like normal so that may be why the `clear` isn't working as intended. similar to other subshells like `bash` for example.

We'll post any updates on this thread.
