### ISSUE TITLE
Unexpected appended string prompt

### ISSUE THREAD

**Issue by khiet-alt** [warpdotdev/Warp#2944]
### Describe the bug

I have used spaceship theme and I have this line in my .zshrc: 
source /opt/homebrew/opt/spaceship/spaceship.zsh
So whenever I have new command in warp, it always append this line as string like:
------------
(base) ~
~ via 🅒 base
➜

This is example in my terminal, 'base' is my virtual env in conda
So I must delete these unexpected string: 
~ via 🅒 base 
➜
in order to  write my own commands

### To Reproduce

- Use spaceship theme in zsh
- source /opt/homebrew/opt/spaceship/spaceship.zsh in ~/.zshrc

### Screenshots

<img width="852" alt="Untitled" src="https://user-images.githubusercontent.com/67104385/232329605-2ef4d126-a0d5-4187-8457-812f97413ddf.png">

### Operating System

MacOS

### OS Version

Ventura 13.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @khiet-alt This is a known issue due to Warp [not supporting multi-line prompts at this time](https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts). This may be something we support in the future, but for now, you'll have to use the workaround below.

For the spaceship theme in particular there is a workaround listed here and below:
This prompt can cause an [issue](https://github.com/warpdotdev/Warp/issues/1973) with typeahead in Warp's input editor.
To workaround the issue, run echo "SPACESHIP_PROMPT_ASYNC=FALSE" >>! ~/.zshrc

Please let us know if the workaround fixed the issue and close this one out. For not there aren't immediate plans to support multi-line prompts, but we're working on support for right-sided prompts in the near future so stay tuned.

**Comment by khiet-alt** [comment]
Thanks for @dannyneira solution, it has been solved !. Thanks a lot
