### ISSUE TITLE
option+backspace copies to clipboard the string being deleted

### ISSUE THREAD

**Issue by johnib** [warpdotdev/Warp#2945]
### Discord username (optional)

johnitravolta

### Describe the bug

Hey,

If I want to delete some piece of string using `option+backspace`, so a whole word is deleted -- then the current behavior of the terminal is to copy to clipboard the deleted string.

### To Reproduce

Write some command:

```bash
echo hello world
```

Make sure the prompt indicator is at the end of the `world`, and then click `option+backspace`.
Then, paste whatever you have on your clipboard somewhere, it would be the word `world`.

### Expected behavior

Just delete the string. Not override the clipboard.

### Operating System

MacOS

### OS Version

13.3.1 (22E261)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @johnib We're tracking this issue here #1785 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

As a workaround, you can try disabling the option keys as meta and see if that helps with the issue.
![image](https://user-images.githubusercontent.com/16809145/232617684-cc2a7459-0b57-4e7a-be85-9cdc3d5fa5c3.png)

Closing as duplicate.
