### ISSUE TITLE
Loading bars for brew not rendering correctly

### ISSUE THREAD

**Issue by empowerSean** [warpdotdev/Warp#2950]
### Describe the bug

Brew loading progress bar doesn't display on a single line. It works correctly on iTerm2 and the built-in Terminal app. Some other programs' loading bars also work correctly so this is just brew afaik.

### To Reproduce

1. Install or update something with `brew`
2. Observe it will not overwrite the loading progress on the same line regardless of window size.

### Expected behavior

Loading progress and percentage display on the same line and overwrite for new updates to percentage/progress.

### Screenshots

<img width="648" alt="Screenshot 2023-04-17 at 4 47 56 PM" src="https://user-images.githubusercontent.com/126516589/232607275-3187346c-54fb-4603-a93d-f767b076092c.png">

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.02.28.08.03.stable_01

### Additional context

I think it used to work correctly when I first got Warp in November 2022 but stopped working soon after.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @empowerSean thanks for submitting, I think this may have started around the [time when we enabled soft-wrapping text](https://docs.warp.dev/features/editor#soft-wrapping) in Mid Nov 2022, that's why you may be seeing the percentage and progress appear to be in different lines when using Brew or any other commands that produce overriding lines of text ( like progress bars ).

We'll post any updates to this issue on this thread.

**Comment by empowerSean** [comment]
@dannyneira Was doing some upgrades with brew just now and noticed that the loading bars are in a single line again so I'm going to close this.
