### ISSUE TITLE
SSH into a Windows server silently fails

### ISSUE THREAD

**Issue by lucianthorr** [warpdotdev/Warp#2968]
### Describe the bug

Hi.  I've set up a local ssh server on a windows laptop and found that when I login (from a Mac) while inside Warp, it immediately kicks back out into the client machine.  The same command works inside the Mac default Terminal and VSCode's terminal.  Since I've been using Warp as my default terminal and there's no error shown or anything so it took me a while to realize it wasn't an actual SSH issue so if nothing else, it could be good to have some logging there if there's an incompatibility.

I noticed that a `which ssh` shows a Warp script so maybe the bug is there?

### To Reproduce

Setup an OpenSSH server on windows and login with username and password.  (I haven't configured key management yet)

### Expected behavior

A powershell prompt

### Operating System

MacOS

### Shell Version

zsh 5.9

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @
We're tracking this issue here #1729 

Meanwhile, you can disable the SSH Wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabled, SSH should work as normal.

Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.
