### ISSUE TITLE
option to clear global hot key keybinds

### ISSUE THREAD

**Issue by lone1y-51** [warpdotdev/Warp#2973]
### Describe the solution you'd like?

```text
i want cancel command+H global hot key
```

### Is your feature request related to a problem? Please describe.

```text
i use command+H switch tab
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for letting us know @lone1y-51 We'll post any updates on this thread.

There is currently a way to clear keybinds in the Settings > Keyboard shortcuts menu, but not within the global hotkey keybinds in Settings > Features.

As a possible workaround you can try to set your global hotkey binding to something else besides `CMD-H`( or disable the feature), then in the Settings > keyboard shortcuts menu change your "Activate next Tab" to `CMD-H`.

Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by lone1y-51** [comment]
> Thanks for letting us know @lone1y-51 We'll post any updates on this thread.
> 
> There is currently a way to clear keybinds in the Settings > Keyboard shortcuts menu, but not within the global hotkey keybinds in Settings > Features.
> 
> As a possible workaround you can try to set your global hotkey binding to something else besides `CMD-H`( or disable the feature), then in the Settings > keyboard shortcuts menu change your "Activate next Tab" to `CMD-H`.
> 
> Please 👍 and comment if you're also seeing this issue as it helps us gauge impact.

I cant find `CMD-H` in keyboard shortcuts and i try to set my global hotkey binding to `F12` it's not useful, can't clear `CMD-H`

**Comment by dannyneira** [comment]
The issue with these shortcuts is that it's the default macOS shortcut for hiding windows, so when you press CMD-H in Warp to change the key bind, it will hide Warp. So you need to disable the CMD-H in macOS first before you can bind it within Warp. To disable the Command + H keyboard shortcut on macOS, you can follow these steps:

1. Open "System Preferences" by clicking on the Apple menu in the top-left corner of the screen and selecting "System Preferences".
2. Click on "Keyboard".
3. In the "Keyboard" tab, click on the "Shortcuts" tab.
4. In the left sidebar, select "App Shortcuts".
5. Click on the "+" button below the right pane to add a new shortcut.
6. In the "Menu Title" field, type "Hide" (without quotes).
7. Click on the "Keyboard Shortcut" field and press a different key combination that you want to use instead of Command + H. For example, you can use Command + Shift + H.
8. Click "Add" to save the new shortcut.

After following these steps, the Command + H shortcut will be disabled, and you can use the new key combination you set up to perform the "Hide" action.

**Comment by lone1y-51** [comment]
> The issue with these shortcuts is that it's the default macOS shortcut for hiding windows, so when you press CMD-H in Warp to change the key bind, it will hide Warp. So you need to disable the CMD-H in macOS first before you can bind it within Warp. To disable the Command + H keyboard shortcut on macOS, you can follow these steps:
> 
> 1. Open "System Preferences" by clicking on the Apple menu in the top-left corner of the screen and selecting "System Preferences".
> 2. Click on "Keyboard".
> 3. In the "Keyboard" tab, click on the "Shortcuts" tab.
> 4. In the left sidebar, select "App Shortcuts".
> 5. Click on the "+" button below the right pane to add a new shortcut.
> 6. In the "Menu Title" field, type "Hide" (without quotes).
> 7. Click on the "Keyboard Shortcut" field and press a different key combination that you want to use instead of Command + H. For example, you can use Command + Shift + H.
> 8. Click "Add" to save the new shortcut.
> 
> After following these steps, the Command + H shortcut will be disabled, and you can use the new key combination you set up to perform the "Hide" action.

![image](https://github.com/warpdotdev/Warp/assets/11805860/0d513995-5a8c-47d1-905b-e09b6b471a30)
system shortcut like this, but CMD-H not disabled.

**Comment by dannyneira** [comment]
@lone1y-51 I noticed your screenshot shows SHIFT-CMD-H, make sure you just type in CMD-h ( the H doesn't need to be capitalized when entering the shortcut ), and let us know if that helps.

**Comment by lone1y-51** [comment]
> @lone1y-51 I noticed your screenshot shows SHIFT-CMD-H, make sure you just type in CMD-h ( the H doesn't need to be capitalized when entering the shortcut ), and let us know if that helps.

![image](https://github.com/warpdotdev/Warp/assets/11805860/26101aa6-a7e7-4aeb-bcd8-3a0ec42d07fd)
like this, can't disable CMD-H.
I hope that the warp terminal can disable the shortcut key of CMD-H instead of modifying the system configuration

**Comment by dannyneira** [comment]
You can also try configuring the Hotkey shortcut to something other than the system shortcut ( `SHIFT-CMD-W` maybe a good option)

**Comment by dannyneira** [comment]
@lone1y-51 Are you still seeing this issue in Warp? You can also disable the hotkey shortcut, or override the current one with another shortcut if you want to replace the `CMD-H`. Also CMD-H is a mac os default keyboard shortcut to "Hide" the window in focus, so needs to be disabled from the Mac OS settings.

Closing as resolved since the ability to replace or disable the shortcut exists.

**Comment by poloxue** [comment]
I encountered this problem. iTerm2 works well in this scenario. I set this rule because I love switching panels using CMD+HJKL like Vim.

**Comment by poloxue** [comment]
<img width="628" alt="image" src="https://github.com/warpdotdev/Warp/assets/5935065/2f5d4300-fe58-4789-abb7-8f99f97d5943">
