### ISSUE TITLE
Fish abbreviation not expanded when chosen from autocomplete

### ISSUE THREAD

**Issue by canac** [warpdotdev/Warp#3007]
### Describe the bug

I'm excited that fish abbreviations are now expanded! However, I noticed that fish abbreviations aren't expanded when they are selected from the autocomplete menu.

### To Reproduce

1. Set up abbreviation: `abbr --add l 'ls -lah'`
2. Type `l`
3. Type `Tab`
4. Navigate to the `Alias for "ls -lah"` entry via the arrow keys if necessary
5. Type `Enter`

Result: `l ` is shown in the input box instead of expanding the abbreviation to `ls -lah`. Even worse, if I type `Enter` again, I get the error `fish: Unknown command: l` (just like `fish -c l` does).

### Expected behavior

I would expect that selecting the fish alias option from the autocomplete would expand it to the abbreviation so that fish doesn't error when running the command.

### Screenshots

https://user-images.githubusercontent.com/3740187/235717457-97da919e-4c15-4709-82a9-eaf5a37fa9e4.mov

### Operating System

MacOS

### Operating System and Version

macOS 13.3.1

### Shell Version

fish, version 3.6.1

### Warp Version

v0.2023.04.25.08.05.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @canac.

It appears that when since the alias is selected from the completion menu, a space gets added after the alias, and it's the space that is causing fish to not recognize the alias (since it appears to be reading the alias+space ). As a workaround, if you select an alias from the completion menu, make sure to delete the extra space and it should run as expected. I'll bring this up with the team and we'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by canac** [comment]
With the latest release, fish completions no longer show up in the autocomplete at all, despite the changelog entry stating, "Fish aliases are now supported in the completions menu".

**Comment by danielpeng2** [comment]
Hey @canac, I think what's happening is that while we've added support for fish aliases, fish abbreviations no longer show up in the completions menu. That was an unintended side effect of supporting fish aliases. We've made note of this issue and will let you know when it's fixed.

**Comment by canac** [comment]
This appears to work correctly now in v0.2023.06.13.08.03.stable_03. Thanks for the fix!
