### ISSUE TITLE
Switching Panes more conveniently with shortcuts (up/down/left/right)

### ISSUE THREAD

**Issue by poberherr** [warpdotdev/Warp#3039]
### Discord username (optional)

patrick#4677

### Describe the solution you'd like?

```Text
As a heavy user of panes, there is currently right now just the possibility to switch to the next pane. 

I'd like a feature where you can switch panes with additional shortcuts for 
- focus pane up
- focus down down
- focus left pane
- focus right pane
```

### Additional context

If you are used to tiling windows / vi shortcuts for switching panes are often 
- mod + [h,j,k,l] in an editor

I find it utterly convenient to mirror the same and just use something to navigate panes similar like
- mod2 + [h,j,k,l] in warp

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @poberherr There are a number of built-in shortcuts for switching pane focus, you can find them all in the Command Palette `CMD-P` by searching for "switch pane", these default to `OPT-CMD-UP/DOWN/LEFT/RIGHT` arrows. See here for more: https://docs.warp.dev/features/windows/split-panes

https://user-images.githubusercontent.com/16809145/236909419-4911697f-573f-43fb-bf72-d6d185e396da.mp4

All these shortcuts can be modified/deleted in the `Settings > Keyboard Shortcuts` menu. See here for more: https://docs.warp.dev/features/keyboard-shortcuts

![CleanShot 2023-05-08 at 12 56 37](https://user-images.githubusercontent.com/16809145/236908745-ff52b656-7a80-4844-a0ca-e4928a2ae62b.png)

Please close this request if the existing feature meets your use case, if not or any issues let us know.

**Comment by tompaz3** [comment]
Is there any chance for making the navigation with these keyaboard shortcut respect the directions?
As of today, when I create 4 panes and when I enter the Top-Right pane and use the Cmd + Opt + Arr Down shortcut, I get navigated to Bottom-Left pane instead of Bottom-Right pane, which would seem more natural to me.

Or if I go from Top-Left using Cmd + Opt + Arr Down, I go to Bottom-Left - this is expected. Buth then, when I use Cmd + Opt + Arr Up, I go to Top-Right pane instead of going back to Top-Left one.

This is driving me crazy and gets me every single time I use these shortcuts. 😅
