### ISSUE TITLE
ssh will create temparory files under remote server's /tmp directoy

### ISSUE THREAD

**Issue by EddyChina** [warpdotdev/Warp#3143]
### Describe the bug

After setting ssh authorization between my local and remote servers,  when you type any command on the remote server while sshing, it creates two 'tmp.******' files under /tmp folder.  It only happens using Warp.  iTerm2 and Terminal don't create this kind of file. 

### To reproduce

1. configure RSA authorization between your local mac and remote Linux Server (Say using root)
2. then ssh root@remoteserver, you will log into remote server without input password
3. execute any command (ls/ cd/ etc.), then see "  ls -l | grep 'tmp.* " to see what happened. 

### Operating system

MacOS

### Operating system and version

13.3.1 (a) (22E772610a)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
I suspect this is normal as in order to use features like Blocks, etc. in ssh sessions Warp bootstraps on the remote server. If you're using zsh on the remote host, we create a temp folder to act as the ZDOTDIR during the bootstrapping process and remove it when the shell is set up. https://docs.warp.dev/features/ssh

As a workaround, you can disable the SSH Wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabled, SSH should work as normal.

Closing as this is normal behavior of Warp in SSH sessions.

**Comment by EddyChina** [comment]
> 

However, those temp folders are not removed. How to change the output directory for those temp folders instead of '/tmp'? Or could those temp folders removed after ssh session closed?

**Comment by dannyneira** [comment]
Hello, @EddyChina!

The `/tmp` directory is commonly used by various programs for storing temporary data. Unfortunately, there is no option to change the location of the temp files generated by Warp from `/tmp` directory.

By default, the contents of the `/tmp` directory are cleared when the server restarts. This behavior ensures that temporary data is automatically removed when it is no longer needed.

If you have any further questions or concerns, please feel free to let us know. We're here to help!
