### ISSUE TITLE
Source command doesn't work

### ISSUE THREAD

**Issue by ichachy** [warpdotdev/Warp#3145]
### Discord username (optional)

Itay Chachy

### Describe the bug

I updated one of my aliases in my `.zshrc` file, and then I tried to update the current running terminal session with the new aliases using: `source ~/.zshrc` and it didn't work. I needed to start a new terminal session for it to update.

### To reproduce

1. Update or add a new alias in `.zshrc`.
2. Update the pointer using `source ~/.zshrc`.
3. Call the alias you just added/changed and see that the result isn't what you wanted.

### Expected behavior

To work with the new alias.

### Operating system

MacOS

### Operating system and version

13.2.1

### Shell Version

zsh 5.8.1 

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @ichachy What you may be seeing is that error underline the alias, even after the `source`. That is because newly installed apps or newly created aliases will trigger error underlining until you open a new Warp session (Window/Tab/Pane). You should still be able to run the alias regardless of the "[Error underlining](https://docs.warp.dev/features/editor/syntax-error-highlighting#what-is-error-underlining)" as with my example below you'll notice the alias runs, but only after opening a new session is it recognized as a valid alias:

https://github.com/warpdotdev/Warp/assets/16809145/e8a5cb51-6e14-49b3-a605-797a358c3cde

I hope this helped clear up your issue. Closing as this is resolved, but if the issues persist, even with a new session, please let us know.

**Comment by ichachy** [comment]
@dannyneira Thank you very much!
Just wanted to mention that I really enjoy using warp, keep up the good work!
