### ISSUE TITLE
I would like for the clear command to clear blocks

### ISSUE THREAD

**Issue by hwestman** [warpdotdev/Warp#3155]
### Discord username (optional)

hwestman

### Describe the solution you'd like?

```Text
I constantly write `clear` in order to clear my shell - When doing this in warp it looks like it pushes the content up instead of removing the blocks which is what I expected it to do. (I can't stand having the scrollbar visible after a clear, and let's be honest, I won't be able to rid the habit of writing `clear`)
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hello, @hwestman! Thank you for submitting this feature request. We appreciate your input and engagement.
Warp's clear works similarly to how the clear command works in other terminals by pushing the input/output up. We have maintained this default behavior to align with common terminal practices. However, one difference is that in other terminals, the scroll bars tend to disappear until they are used again.
Regarding the clear functionality in Warp, we do have a [keyboard shortcut](https://docs.warp.dev/features/keyboard-shortcuts#blocks), `CMD-K`, that clears all the blocks in a session and can be reconfigured in the Settings > Keyboard Shortcuts. 

Also, there is an existing feature request to address another difference, which you can find here: #2382. We encourage you to follow that thread for any updates or further discussions on this topic.

As there is already a command available to clear all blocks in a session, we will be closing this feature request.

Thank you again for your contribution. If you have any more suggestions or questions, please let us know.

**Comment by stuta** [comment]
Is there a way to send CMD-K to clear the blocks by printing some special characters? 

I'm using alias cls="clear && printf '\e[3J'" and then cls && ./run-app in iTerm. See: https://apple.stackexchange.com/questions/31872/how-do-i-reset-the-scrollback-in-the-terminal-via-a-shell-command

I want to clear the blocks and then start my program that prints data to console with every rest call. I must use warp classic mode to see the latest text at the bottom of the screen so that I can see also previous calls.

**Comment by d-kja** [comment]
This is an actual pain, I don't know which terminal you were using to call it default behavior, but even the standard terminal clears the screen, and to make it worse the `clear blocks` command only shows up as an option in certain conditions. At least give us an option to toggle this behavior

**Comment by Enteleform** [comment]
@dannyneira

> Warp's clear works similarly to how the clear command works in other terminals by pushing the input/output out of the view with space. **We have maintained this default behavior to align with common terminal practices.**

This is incorrect, the current implementation deviates from expected default behavior.

-----

[This article](https://nickjanetakis.com/blog/clear-vs-ctrl-l-in-your-shell) describes the difference:

> `CTRL + L` vs `clear` is one of those cases, **there’s a subtle difference on what they do:**
> 1. `CTRL + L` clears the visible output on the screen so your prompt is back on line 1 but you can still scroll up in your buffer and see the previous output
> 2. `clear` does the same as `CTRL + L` except it will also clear your buffer so if you scroll up there won’t be any previous output

-----

Warp is currently providing behavior `1` for both `Ctrl + L` and `clear`, which does not have parity with standard terminal implementations.

**Comment by dannyneira** [comment]
@Enteleform heard, as a workaround to clear command you can delete all the blocks with CMD-K on Mac or CTRL-SHIFT-K on Linux. This should be similar to what you expect for 2.

**Comment by JohnSBarden** [comment]
This behavior breaks custom commands for me, as well.  In attempting to execute a shell startup script that updates local repos and prints the output, the view scrolls down past and shows me a blank view rather than the output of my script.  It's very simple, and works in every other terminal I've tried.

```zsh
alias morning='wd work && clear && neofetch && echo Good morning! Setting up your repos... && $HOME/scripts/auto_pull.sh'

```

You can see the echo isn't visible in the quick video below. The behavior of `clear` is _not_ equivalent, and I'd rather be able to have one script work everywhere than have to account for Warp's broken behavior here.


https://github.com/user-attachments/assets/a8d5ff10-53e5-4da5-8ab8-51e02b1ba3a3

**Comment by LucHermkens** [comment]
Please reopen this issue. I would like `clear; bun test` to clear the scrollback from previous test runs, which is the expected behavior.

**Comment by omkar-aiplanet** [comment]
on windows in context Menu there is option "clear block" which clears all  blocks .
