### ISSUE TITLE
Text Rendering / Line height weird

### ISSUE THREAD

**Issue by apfelbox** [warpdotdev/Warp#317]
### Describe the bug

```shell
Text rendering in Warp doesn't look great yet.

There is no emoji support yet (yeah, sorry 😄)

But especially the line height seems off. The line height is a lot higher than the text and the text is positioned at the top.

Same font, same font size in iTerm 2 looks more balanced.
Also there is sometimes a small gap between the lines, which doesn't look great when for example rendering tables
```

### To Reproduce

Steps to reproduce:
1. Use Font `FireCode NF` / medium / font-size 14
2. then you should be able see the issues

### Expected behaviour

```shell
You should be able to draw beautiful UIs in your CLI
```

### Warp:

![Capture 2021-10-27_16-53-12](https://user-images.githubusercontent.com/1032411/139091067-0ee81eb8-57f6-4402-adc7-7fa149cd3b1f.png)

### iTerm 2:
![Capture 2021-10-27_16-54-22](https://user-images.githubusercontent.com/1032411/139091161-a7309961-0401-4892-a0f8-2e1e76f15ba5.png)

### Line height visualization in Warp:
![Capture 2021-10-27_16-56-13](https://user-images.githubusercontent.com/1032411/139091559-164c4a9d-2e5d-4e07-84bd-cfd926c1fe8b.png)

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
Related:
- #261

**Comment by elviskahoro** [comment]
### Describe the solution you'd like?

```shell
To configure the text line height.
Discord - feature-requests - 2021.11.03:
"FR: Reduce the line-height (or add an option). I don't mind the UI taking up more space than a normal terminal, but you lose too much space to each line. I would accept whatever line-height: normal is for the current font. Based on the Fira Code repo, it's still substantially tighter than in Warp."
```


### Is your feature request related to a problem? Please describe.

```shell
N/A
```


### Additional context

https://discord.com/channels/851854972600451112/852249738002956311/905494119076474891

**Comment by elviskahoro** [comment]
From @pf1gura via #352

I like to set my line height to something bigger than the standard. I find too much text in one view to be distracting. In iTerm, my preferable value is 200. I suppose I am not alone in this and it would be nice to have that option.

![CleanShot 2021-11-05 at 21 13 52](https://user-images.githubusercontent.com/41795518/140572835-296d4e60-6d92-4056-8c86-dddf871ec0f6.png)

**Comment by elviskahoro** [comment]
From @argai via #352

I've just downloaded warp and have the same issue, line height needs to be configurable.

![image](https://user-images.githubusercontent.com/8986004/144688428-4b65c2c4-90f9-4e51-998d-4592b20ae3ec.png)
On the left there is warp, on the right iterm. While this might be ok on a desktop and big screen, on a 13" laptop its way too  much space wasted.

**Comment by elviskahoro** [comment]
From @lnking81 via #352

Not only the line height but also all font rendering options: name, size, the interval between letters, ligatures, anti-aliasing, etc.

**Comment by Theo-Steiner** [comment]
The extreme line height in combination with the font being positioned at the very top with ``FiraCode Nerd Font Mono`` is also problematic when using a custom status line in vim / neovim, as there is a huge padding like space below the text.
<img width="200" alt="スクリーンショット 2022-03-26 13 22 10" src="https://user-images.githubusercontent.com/40017636/160224501-6c8bf6af-35b1-42cb-8874-7863f38ea935.png">

**Comment by samurai00** [comment]
![截屏2022-04-20 15 43 44](https://user-images.githubusercontent.com/685874/164182140-42544002-504b-4a3b-8bc1-c92a2bc4ae4b.png)

**Comment by eyeKill** [comment]
Same issue here.

Left warp, right iTerm2:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/7934322/165272574-7dcd6380-73f9-43db-aa61-da54f51f1565.png">

**Comment by SebDanielsson** [comment]
Came here for the same. Line height needs to be configureable and also it would be nice to be able to get some of that iTerm 2 anti aliasing.🤓

**Comment by Theo-Steiner** [comment]
There seems to have been some sort of line height related issues with Warp v0.2022.04.25.09.59.stable_03, although it is still not configurable

**Comment by samurai00** [comment]
version v0.2022.04.25.09.59.stable_03 seems a bit normal?
<img width="1147" alt="截屏2022-05-02 15 53 11" src="https://user-images.githubusercontent.com/685874/166202400-e71c8c91-eccf-46e7-96d7-07005b848c7f.png">

**Comment by apfelbox** [comment]
Can confirm that it looks way better now. The line height is pretty narrow now though, so it would be great if we could configure it.

The important part however is that the text should be centered in the line height and not at the top of it. Otherwise we will just reproduce the issue from before.

**Comment by SebDanielsson** [comment]
It's much better. Still would like more options for fonts. I would like to have some AA + configure font weight.

**Comment by vorporeal** [comment]
Yeah, line height was fixed but there were a couple other issues introduced so it got temporarily rolled back.  I'm actively working on font rendering issues, so things should be improving soon.

One note about anti-aliasing, since many people seem to comment on it - we do actually use AA for font rendering, and my pixel-level comparisons with iTerm on both retina and non-retina displays indicates that both terminals render glyphs the same way (Courier New, 13pt, with "Use thin strokes for anti-aliased text" in iTerm set to "Never"), with a couple notable differences that I'm working on:
 * Warp computes cell sizes differently (this is the line height issue y'all have been discussing, and can be seen in the horizontal spacing of glyphs in the screenshots below)
 * Warp cuts the top row of pixels off of some glyphs (you can see this in the "l" below)
 * Warp occasionally renders glyphs at fractional y-values, leading to different/fuzzy glyph rendering
 * Warp doesn't render glyphs with thinner outlines on retina displays (hence disabling that in iTerm to make pixel-level comparisons)
 * Warp doesn't allow users to customize font metrics (e.g.: line density/spacing) - this is something I'd like to fix but will likely come after fixing core rendering issues

Screenshots of Warp (top, blue bg) and iTerm (bottom, black bg) on a non-retina external display:
![image](https://user-images.githubusercontent.com/211194/167028739-0bb423ce-4abb-4bfa-8d38-2165ac15cd8d.png)
![image](https://user-images.githubusercontent.com/211194/167028769-1e411bcf-f765-4053-9a79-7b4022f5ebcd.png)

If you're finding that Warp and iTerm have different pixel-level glyph rendering, I'd love it if you would reply with the following info:
 * A screenshot or two highlighting the differences
 * Which version of Warp you're running
 * Which font you're using and which font size
 * Whether you're using Warp on your laptop screen (which model?) or an external monitor (what resolution?)

Getting this right is important to us (and all of you, clearly!) :)

**Comment by samurai00** [comment]
Not OK on v0.2022.05.02.09.00.stable_01 again 😂

**Comment by vorporeal** [comment]
@samurai00 As mentioned above, the fix for line height was rolled back temporarily while we fix a regression.  A handful of font rendering improvements should go out next week. :)

**Comment by vorporeal** [comment]
Update: today's release (now live) re-introduces the fix for too-large line heights.  We're working on adding customizable vertical/horizontal spacing to settings; should be live in the next week or two.

Please let me know if you still encounter issues with incorrect line heights after updating!

**Comment by luxus** [comment]
the line-height looks good now. lunarvim looks normal now.. except that the text doesn't hide behind menus (not related to the line-height)

**Comment by luxus** [comment]
@vorporeal i created a issue about it https://github.com/warpdotdev/Warp/issues/1386

**Comment by ronisbr** [comment]
The vertical problem does not happen if you use the default font, but if you change to Monaco, for example, it starts to happen:

Default font
<img width="1136" alt="Captura de Tela 2022-06-11 às 10 41 10" src="https://user-images.githubusercontent.com/1068295/173190383-3b794bf2-2e35-4e50-896e-07b5a0050808.png">

Monaco
<img width="1136" alt="Captura de Tela 2022-06-11 às 10 41 28" src="https://user-images.githubusercontent.com/1068295/173190391-2534c158-9747-4fdf-95a2-0e7516488ea2.png">

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
