### ISSUE TITLE
ipython presentation bug

### ISSUE THREAD

**Issue by shuhaohe** [warpdotdev/Warp#3171]
### Describe the bug

ipython -> clear -> input new command

**The first line is hidden**

<img width="854" alt="image" src="https://github.com/warpdotdev/Warp/assets/35570117/87fe8499-5337-4b52-bbe0-736516a6a147">

### To reproduce

ipython -> clear -> input new command

### Operating system

MacOS

### Operating system and version

13.4.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.30.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @shuhaohe This is a known issue with the [Sticky command header](https://github.com/warpdotdev/Warp/issues/2915), which was recently resolved for other commands like `less`, but I'll bring this up with the team as a continuing issue with ipython. We'll post any updates on this thread.

**Comment by dannyneira** [comment]
Hey @shuhaohe so, the fix for this issue is not something that may no be fixed for some time, so instead I recommend you use `CMD-K` to [clear blocks](https://docs.warp.dev/features/keyboard-shortcuts#blocks) instead of `clear` and it should work properly with the sticky command header enabled. Otherwise, you can disable the [sticky command header](https://docs.warp.dev/features/blocks/sticky-command-header) as a workaround.

**Comment by dannyneira** [comment]
We'll be tracking this issue over at #3214  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
