### ISSUE TITLE
DUP: Duplicate of #066 - Support zsh-syntax-highlighting

### ISSUE THREAD

**Issue by apfelbox** [warpdotdev/warp#318]
### Describe the solution you'd like?

```shell
I really like using `zsh-syntax-highlighting`, but it doesn't seem to be supported.
```
https://github.com/zsh-users/zsh-syntax-highlighting

### Is your feature request related to a problem? Please describe.

```shell
Syntax highlighting is great, so who doesn't want it 😄
```

**Comment by Advait-M** [comment]
Hey @apfelbox 👋 ! 

Super excited to let everyone know that we just launched **Syntax Highlighting and Error Underlining on Warp yesterday** 🎉 ! By default, Warp will highlight each part of a command in a different color denoting arguments, options/flags, variables, etc. and underline invalid commands with a dashed red line. You can toggle these features on/off via the Command Palette or Settings > Features.

Note that these features are built into Warp itself and will be active within Warp's [custom input editor](https://docs.warp.dev/features/editor). Plugins such as `zsh-syntax-highlighting` will continue to apply to past commands (in the block grid), since they function by using ANSI escape sequences for coloring text. We may explore adding Warp syntax highlighting to past commands as well, in the future.

Please download the latest release (`v0.2022.10.11.08.13.stable_01`) to get access to these features! The screenshot below shows the features in action:

![Syntax Highlighting and Error Underlining Demo](https://user-images.githubusercontent.com/12927474/195830313-e3eab7b1-84c7-4118-896d-443215c1e3b5.png)

Check out our [user documentation](https://docs.warp.dev/features/editor/error-syntax-highlighting) for more details!

Let us know if you have any comments/feedback on these features!

**Comment by apfelbox** [comment]
@Advait-M thanks for the update, that is really looking great.
Would it be possible to keep the syntax highlighting in already executed blocks?

Currently it only highlights in the prompt.

**Comment by Advait-M** [comment]
> @Advait-M thanks for the update, that is really looking great.
> Would it be possible to keep the syntax highlighting in already executed blocks?
> 
> Currently it only highlights in the prompt.

Hey ! Thanks for bringing this up! This was a topic we actively thought about when designing this feature. However, due to the fact that the input editor within Warp is a real text editor, it’s rendered quite differently from the past commands block grid (which is similar to a traditional terminal). For the initial launch of this feature, we’ve decided that syntax highlighting is most relevant when a user is typing a command and not as useful afterwards so we’ve held off on this due to the additional complexity. 

We may revisit this in the future - useful to know that you'd find this helpful 😀 ! Could you perhaps open a new issue for tracking purposes and link back to this (for us to gauge how popular this request is)?

Note that the block grid uses ANSI escape sequences for text coloring i.e. you'll see plugins such as `zsh-syntax-highlighting` are active in the block grid.
