### ISSUE TITLE
Please let me disable blocks (the big red squares)

### ISSUE THREAD

**Issue by jakeonrails** [warpdotdev/Warp#3189]
### Describe the solution you'd like?

1. When I click my mouse into the terminal I want to just start typing and have input go into wherever the cursor is.
2. When I drag to select text, I want to (sometimes) hold shift and extend my text selection
3. When I focus my terminal (with a click) I want to always see a blinking cursor where keyboard input will go
4. When I am using Rails console, I just want to have one unobstructed area to work. Instead the blocks get mouse input when I'm switching to Warp and then I have to "unblock" myself before I can continue.

I have no idea what blocks are for. They have offered no benefit to me so far, and I would like to turn them off.

#### Reproduce item 1:

1. Type a command and hit enter
2. Start to type a new command
3. Click on the block of the previous command
4. Now try to delete text from the half typed command
5. Keyboard input goes into the ether

#### Reproduce item 2: 

1. Try doing something with lots of output, like `cat some-large-file.csv`
2. Now try to select that text, but stop short of selecting all of it, and release your mouse button.
3. Now hold shift to select the remainder and it unselects everything

#### Reproduce item 3:

1. Use ssh to go into a shell
2. Tab away from warp
3. Use mouse to click into warp, such that a block is selected
4. The cursor is not blinking, there is in fact no cursor

#### Reproduce item 4:
1. I cannot exactly specify the conditions this one is triggered by. I think it is the fact that a Rails console is some kind of subshell that warp doesn't understand, and so it gets broken. I would say if you're a frequent Rails console user, Warp is just painful to use - I don't know where my cursor is, deleting text doesn't work, and I frequently have to hit → to get the cursor back before I can start typing. Item 4 is probably a combination of all the previous 3 issues, plus the fact that warp doesn't understand how to "blockify" `rails c`.

### Solution:

Just let me disable blocks in the preferences and have a "normal" terminal, where there is only one block that you can never turn red by clicking. 

### Importance:

VERY. Honestly the only thing preventing me from not switching to iTerm2 is that it takes a long time to configure so that the editing shortcuts work. I really like Warp, it works out of the box pretty dang well, but this is wearing me down, I feel like I'm constantly fighting these dang red squares that don't provide any value.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @jakeonrails Thanks for submitting, in order to [focus terminal input](https://docs.warp.dev/features/keyboard-shortcuts#blocks) you can use `CMD-L` or click directly on the input editor. 

Unlike other terminals, Warp organizes input and output into Blocks, this core functionality allows a host of other features you can learn more about here https://docs.warp.dev/features/blocks and I don't see if going away any time soon.

Please add a :+1: to the original post at the top to signal that you want this feature to disable blocks entirely, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hey Folks, after internal discussion, we've decided to close this request as we will most likely not disable one of the integral features in Warp. Taking advantage of Blocks can be a bit of a learning curve so we hope our docs can help clear up the value and functions they provide. https://docs.warp.dev/features/blocks

Thanks for your interest in using Warp!

**Comment by x48115** [comment]
I agree with this. If there were another terminal emulator with text input features as good as warp I would stop using warp because I have no need for blocks.

**Comment by sanjay51** [comment]
This is indeed the most annoying part of Warp, and the mute response just adds to the pain. Please add a way to disable the blocks - I love warp but hate the blocks - they are quite useless to me, and the big reason they are annoying is poor design - they make it hard to focus on key part of the terminal - the command line at the bottom.

**Comment by dannyneira** [comment]
@sanjay51 As far as I'm aware, this request would be very difficult to implement without a significant refactoring of Warp so sorry to hear about this blocker, maybe enabling input at the top could help with focusing on the command line input. https://docs.warp.dev/appearance/input-position

**Comment by sanjay51** [comment]
> @sanjay51 As far as I'm aware, this request would be very difficult to implement without a significant refactoring of Warp so sorry to hear about this blocker, maybe enabling input at the top could help with focusing on the command line input. https://docs.warp.dev/appearance/input-position

Ok sure Danny, thanks for the kind response!

**Comment by gadelkareem** [comment]
> @sanjay51 As far as I'm aware, this request would be very difficult to implement without a significant refactoring of Warp so sorry to hear about this blocker, maybe enabling input at the top could help with focusing on the command line input. https://docs.warp.dev/appearance/input-position

@dannyneira, would it be possible to update the highlight block functionality so that clicking set the focus on the prompt while click+CMD selects the block?

**Comment by wong2** [comment]
Blocks are annoying..

**Comment by maao666** [comment]
Blocks are great until I open an SSH connection with tmux. Then the entire screen would be highlighted (bacause the block is indeed the entire screen in this case). A possible workaround might be "auto disabling block highlighting when the block is fullscreen" or "disabling block highlighting when SSH wrapper is turned off". Anyway, the experience of connecting to remote tmux is not great at this moment.

<img width="760" alt="Screenshot of Warp connecting to remote tmux" src="https://github.com/warpdotdev/Warp/assets/20357428/b25af09f-31cd-429f-a86b-d247bddd875c">

**Comment by henricook** [comment]
Would an alternative to this be "when I click a block the focus remains/goes to the prompt instead of the block"? It's also my biggest nag as a new warp user that I can click the terminal, start typing, and the typing goes nowhere because I accidentally clicked a block

**Comment by zachbai** [comment]
Hey @maao666, totally agree that's an annoying experience -- the highlighting of the active block (where you're running tmux) isn't intentional. Will file a ticket for this to be addressed by the team.

@Allerby what kind of interactive shells are you using? If they're running bash fish or zsh under the hood our [subshells feature](https://docs.warp.dev/features/subshells) might help you out. For other interactive shells/REPLs (e.g. python, pgsql etc) we have an open issue [here](https://github.com/warpdotdev/Warp/issues/4082) for building support.

@henricook @Allerby (re: having to 'enter the terminal via mouse' dozens of times a day) -- this is also definitely something we can take a look at. Agree that having to go to the mouse is annoying!

**Comment by Allerby** [comment]
> @Allerby what kind of interactive shells are you using? If they're running bash fish or zsh under the hood our [subshells feature](https://docs.warp.dev/features/subshells) might help you out. For other interactive shells/REPLs (e.g. python, pgsql etc) we have an open issue [here](https://github.com/warpdotdev/Warp/issues/4082) for building support.

Thanks for the prompt reply @zachbai, as you state psql, python, rails console, irb, or REPLs (I use '[pry](https://github.com/pry/pry)' when writing ruby quite a bit). Nice to see you have an open issue that covers most of these - I hadn't stumbled across that thread yet.

> @henricook @Allerby (re: having to 'enter the terminal via mouse' dozens of times a day) -- this is also definitely something we can take a look at. Agree that having to go to the mouse is annoying!

I might be misinterpreting this, but I don't mind using the mouse to change windows - I sometimes stick to keyboard navigation and sometimes opt to use the mouse to change screens. But when I find myself clicking into Warp, I find myself accidentally clicking blocks as @henricook put it.

**Comment by zachbai** [comment]
Ah I see.

Warp does have logic in place that ensures the first click into an unfocused Warp window focus the input no matter where you click. On an already-focused window, however, clicking a block will focus it. 

Is it possible that the Warp window is already focused in these cases where blocks are unexpectedly highlighted?

**Comment by MikkieMuis** [comment]
I'm a sloppy typist and my screen is completely red most of the time. It's like is yelling at me that i'm stupid.
Please make an option to turn it off. A less in your face option must  be possible !

**Comment by jcoutinhopt** [comment]
I understand the pain of refactoring and QAying, specially when is such a differentiate point against other terminals, but the truth is that it does not feel right, its annoying and impacts my daily work. I am really trying because wrap has such useful features like cmd completion, the find and the filter, this really makes a difference for me. But at the end of the day is that, when I need to be quick and assertive (like under pressure) I am going back to terminator instead of forcing me to get used to warp and blocks.
In any case, kudos for you guys for the great work you did on warp.

**Comment by raylillywhite** [comment]
> > @sanjay51 As far as I'm aware, this request would be very difficult to implement without a significant refactoring of Warp so sorry to hear about this blocker, maybe enabling input at the top could help with focusing on the command line input. https://docs.warp.dev/appearance/input-position
> 
> @dannyneira, would it be possible to update the highlight block functionality so that clicking set the focus on the prompt while click+CMD selects the block?

>  It's something I might use once or twice a week (at most), however I enter my terminal via my mouse dozens of times per day if not per hour, and using interactive shells within Warp means having to 'exit' blocks, I feel like I'm battling the terminal.

Yes, this was the exact issue I was looking for a solution for. I want the block support. But I use it once a month or less even. But I'm constantly struggling to get warp to accept my input because the block got selected. I just want to select the blocks with a right click, double click, cmd click, or via the ... button, something like that. I never want them to be selected by a single left click and would love a way to disable that.

**Comment by raylillywhite** [comment]
> Is it possible that the Warp window is already focused in these cases where blocks are unexpectedly highlighted?

Yes, the reason that happens is because I have multiple monitors, and so just becomes something is visible doesn't mean it's in focus, so I click before typing out of habit. Sometimes it's already in focus and sometimes it's not. But no other app has this problem because no other app disables text input when you click on the area that you want to type.

**Comment by unlocomqx** [comment]
And the blocks cover the prompt sometimes

https://github.com/user-attachments/assets/1f923efe-df12-492a-8069-96833a38e3ef

**Comment by dannyneira** [comment]
@unlocomqx Thats the sticky command header. You can disable this for that session or entirely. Please see how in our docs. https://docs.warp.dev/features/blocks/sticky-command-header

**Comment by CamBrown101** [comment]
> > > @sanjay51 As far as I'm aware, this request would be very difficult to implement without a significant refactoring of Warp so sorry to hear about this blocker, maybe enabling input at the top could help with focusing on the command line input. https://docs.warp.dev/appearance/input-position
> > 
> > 
> > @dannyneira, would it be possible to update the highlight block functionality so that clicking set the focus on the prompt while click+CMD selects the block?
> 
> > It's something I might use once or twice a week (at most), however I enter my terminal via my mouse dozens of times per day if not per hour, and using interactive shells within Warp means having to 'exit' blocks, I feel like I'm battling the terminal.
> 
> Yes, this was the exact issue I was looking for a solution for. I want the block support. But I use it once a month or less even. But I'm constantly struggling to get warp to accept my input because the block got selected. I just want to select the blocks with a right click, double click, cmd click, or via the ... button, something like that. I never want them to be selected by a single left click and would love a way to disable that.

I agree with this. I have been using warp for quite awhile now and really like a lot of the features. I do the same thing with multiple monitors. I often use the arrow keys to run previous commands and often end up scrolling blocks instead of commands. It is really annoying. I have never used blocks and wish I could just hide the feature behind a different command then left click.

**Comment by jackyliang** [comment]
Let us disable Blocks. When I am in psql, Blocks prevents me from using up/down arrow keys to go through old commands.. I disabled the keyboard shortcut but it still does this. Might have to go back to Hyper because this is super annoying.

**Comment by leafonsword** [comment]
Switch to Kitty Terminal because of annoying block

**Comment by alex190291** [comment]
> > [@sanjay51](https://github.com/sanjay51) As far as I'm aware, this request would be very difficult to implement without a significant refactoring of Warp so sorry to hear about this blocker, maybe enabling input at the top could help with focusing on the command line input. https://docs.warp.dev/appearance/input-position
> 
> Ok sure Danny, thanks for the kind response!

why would that require a significant refactor? you just have to make one block permanent and route all output streams to it. 
The only thing that then would be needed is a small adjustment so that clicking this block focuses the input field. i will have a look at your codebase and see if i can do it myself....

**Comment by 0xFlo** [comment]
It's not even the blocks. It's the highlighting of the entire block on click that's driving people away from warp.

**Comment by 0xFlo** [comment]
@jakeonrails

**Comment by jakeonrails** [comment]
> It's not even the blocks. It's the highlighting of the entire block on click that's driving people away from warp. 

Yes! Honestly if warp used double click to select blocks, so I could reliably click on the terminal and just start typing this issue would go away. It's the annoyance of warp not doing the default, expected behavior that makes blocks annoying instead of useful.

**Comment by qunahui** [comment]
Block highlight whole terminal screen, something I accidentally press Esc hope it will disappear but it cancel the process I am running inside terminal instead (When using with Claude Code). Really annoying.

**Comment by jackyliang** [comment]
Unfortunately, leaving Warp due to Blocks. It breaks SSH (a key part of using the CLI) and it highlighting the entire window is pretty annoying. Using it for Claude Code right now, and it's quite distracting. 

I understand this is a deep product decision and part of the identity of Warp, but I guess this isn't for me.

**Comment by ddura** [comment]
Blocks aren't the problem it is the interaction method for selecting them. Its making me move away from Warp even though i love most of the functionality. By just adding an option to ctrl+click to select the block or some other thing other than single click would solve the interaction issues.

**Comment by paulpreibisch** [comment]
The blocks are a problem for me because I want to run claude code in each one, and the blocks screw the view up!  should be able to turn them off. or atleast have them stay out of view unless you scroll up. Currently,  they reduce the amound of screen available for next entry.

**Comment by ronilaukkarinen** [comment]
Chiming in: I dislike blocks. Disappointed that there is no "Disable blocks" feature or not even a "Disable focusing on blocks". I click my terminal all the time and now getting huge "selected" area that obstructs the text. I have to constantly re-click the terminal. Annoying behaviour.

**Comment by edwin-anderson** [comment]
I'm having a bad experience using Claude Code in Warp, honestly, it's pretty depressing. The first issue is that shift+enter doesn't work, so I need to use Karabiner Elements as a workaround to remap shift+enter to ctrl+j. The second issue is that it gets super annoying when I accidentally click on blocks, and this is unforgivable. Using Claude Code in Warp is just depressing overall.

**Comment by jackyliang** [comment]
It's very clear that Warp devs are out of touch with what their users needed

**Comment by seePatCode** [comment]
Chiming in as yet another person that is leaving to leave warp due to blocks especially within Claude Code.

**Comment by chen-rn** [comment]
+1 for the claude code + warp thing!

**Comment by lebe-dev** [comment]
Read a blog post about warp 2.0 (with AI features) recently, but removed again after annoying blocks again :) Blocks are visual mess and makes UI unusable.

**Comment by flosrn** [comment]
Honestly, it's just a shame, I can't use Warp because of this horrible big highlight that covers my entire window every time I click inside it while using Claude Code. It's seriously driving me crazy, what a mess...

Do you know of any better terminal alternatives that work well with Claude Code?
