### ISSUE TITLE
Pin Tab

### ISSUE THREAD

**Issue by jasjs1** [warpdotdev/Warp#3220]
### Describe the solution you'd like?

```Text
When I am using npm start. The VSCode tab goes away and I have to go back and launch the Warp terminal again.
```

### Is your feature request related to a problem? Please describe.

```Text
I'm always frustrated with how sometimes it stays but then the second time I do npm start it goes away. And I think that a pin tab feature would be a good one for Warp.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @jasjs1 Thanks for submitting this. If you could please provide a video or screenshots of the issue you're seeing with a tab closing. This will help us better understand the use case and problem you're trying to solve with this request. I tried `npm start` with a very simple example and didn't see the tab close on my end.

https://github.com/warpdotdev/Warp/assets/16809145/3210f415-b64f-4e08-b8df-4d2fd2b3462f

**Comment by jasjs1** [comment]
The tab didn't close but it would get replaced by npm. I can show provide a video.

https://github.com/warpdotdev/Warp/assets/97198910/6a6eb38f-29b4-478b-a4e3-841c6dfabc00

I am not sure if you guys will be able to make this a feature, or if it would be something that npm is controlling the tab taking over to be npm.

Thanks, and keep up the great work with Warp! ❤️

**Comment by dannyneira** [comment]
Thanks for clarifying, I think I see the issue here is just Warp tab name behavior. When you don't explicitly name a Tab, it will change its name dynamically to either the cwd (current working directory), or a running process (in my example it's `sleep`, but it could be `npm`, `vim`, `ipython`, etc. anything that takes over the session).

https://github.com/warpdotdev/Warp/assets/16809145/7bff7635-6382-485b-8bff-e4a12eda29e5

Also, please take a look at the terminal tip here and see some ways you could programmatically set your tab names with a function in your rc files. https://docs.warp.dev/features/windows/tabs#how-to-use-it

I hope this helps with your use case, lets us know if you have any issues with the above.

**Comment by dannyneira** [comment]
@jasjs1 any luck with the above steps?
