### ISSUE TITLE
Escape+period does not work

### ISSUE THREAD

**Issue by lifesoccult** [warpdotdev/Warp#3260]
### Describe the bug

The escape+period `esc+.` keyboard combo is generally used to cycle through your previous commands' last argument. This functionality is not being honored.

Example:

### To reproduce

Setup
`mkdir /tmp/blah`

Use `esc+.` to reference `/tmp/blah`
`chown root. <esc+.>`

Result
`chown root. .`

And if you continue to cycle via `esc+.` you get:
`chown root. .......`

### Expected behavior
`chown root. /tmp/blah`

### Operating system

MacOS

### Operating system and version

12.6.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Appreciate you letting us know @lifesoccult. I gather since the input editor wrapper works like an IDE, some escape codes for shortcuts like `ESC-PERIOD` may not be working as intended. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.
