### ISSUE TITLE
Copy git branch not working

### ISSUE THREAD

**Issue by yotam-manne-hs** [warpdotdev/Warp#3266]
### Describe the bug

So far when I right-clicked a pane I had an option to copy the current git branch. This option now doesn't exist and also a keyboard shortcut that I configured to do it copies nothing (I made sure the the cwd is in a git repo)

### To reproduce

right click on the command line and see the options

### Expected behavior

I expect to see the option "copy git branch"

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/74211945/81f320fa-fdf2-4701-bc93-5e52deacffa8)
### Operating system

MacOS

### Operating system and version

13.2.1

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

last week for sure

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting, marking this as related to #3229 

I can't seem to reproduce this on my end. There are a few questions that may help us narrow down the root of the issue.

Is there any custom prompt you're using or [Warp default prompt](https://docs.warp.dev/features/prompt)? If default, as a workaround, you can try using a custom prompt like Starship.rs so that you can see the git branch.
When you right-click on the prompt and "Copy git branch", then paste it into the input editor, does it paste the branch or nothing?
Also, care to share your redacted (make sure to not include any personal information on these files. i.e. logins, IPs, etc.) gitconfig or rcfiles so that we can try and reproduce this issue?

**Comment by yotam-manne-hs** [comment]
I use this option for the promt: 
![image](https://github.com/warpdotdev/Warp/assets/74211945/0a73bacf-54f4-4dad-8591-ad80d77df72f)

this is what it looks like:
![image](https://github.com/warpdotdev/Warp/assets/74211945/da3aba85-8936-424b-8c28-a23661768a9a)

and no copy git branch option:
![image](https://github.com/warpdotdev/Warp/assets/74211945/97640e8e-dfc2-4290-a292-007ef38c1993)

and this is the default promt:
![image](https://github.com/warpdotdev/Warp/assets/74211945/3194c040-58de-479b-9dc4-3a38cbb98c0e)

it doesn't show the current branch and also doesn't have the copy git branch option:
![image](https://github.com/warpdotdev/Warp/assets/74211945/c4b290d4-5c01-4e6e-a4a8-00a04b8988a9)


I'm not familiar with the term 'redacted' what does it mean in this context and how do I share it?

**Comment by dannyneira** [comment]
Redacted means you remove any sensitive information like IP addresses, logins, emails, etc. Then just post the RC file in a comment. 

Also, afaik we're working on a fix for the git prompt in general which may address this issue as well. See #3229 for updates on the git prompt bug status.

**Comment by wagenet** [comment]
The latest release resolved the problem for me.

**Comment by dannyneira** [comment]
Hi @yotam-manne-hs, this issue should be resolved in the latest release. Please update Warp and let us know if the issue persists.

**Comment by yotam-manne-hs** [comment]
The issue is fixed. thanks! :)

**Comment by dannyneira** [comment]
Thanks for confirming! Closing as resolved, but if any related issues come up let us know.
