### ISSUE TITLE
Does not support CJK characters

### ISSUE THREAD

**Issue by LitoMore** [warpdotdev/warp#327]
### Describe the bug

```shell
CJK characters cannot be displayed correctly.
```

### To Reproduce

Create a file `cjk` with this content below:

```
English:
Warp is a blazingly fast, Rust-based terminal that makes you and your team more productive at coding and DevOps.

Simplified Chinese:
Warp 是一个极快的、基于 Rust 的终端，可让您和您的团队在编码和 DevOps 方面更有效率。

Traditional Chinese:
Warp 是一個極快的、基於 Rust 的終端，可讓您和您的團隊在編碼和 DevOps 方面更有效率。

Japanese:
Warpは、コーディングとDevOpsであなたとあなたのチームの生産性を高める、非常に高速なRustベースのターミナルです。

Korean:
Warp는 코딩 및 DevOps에서 귀하와 귀하의 팀을 보다 생산적으로 만들어주는 매우 빠른 Rust 기반 터미널입니다.
```

Try to `cat` the content:

```sh
cat cjk
```

The Result will be:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/8186898/139374149-22d8a1d8-688d-4ead-a80e-c2e013fad016.png">

### Expected behaviour

<img width="792" alt="image" src="https://user-images.githubusercontent.com/8186898/139374277-deb88471-23e4-4ad3-b902-284844c0c604.png">

### OS Version

11.6

**Comment by kevinyang372** [comment]
This should be fixed in the latest release of warp! 
![image](https://user-images.githubusercontent.com/30107576/140180090-710b0e4e-9f6b-4bc6-bb57-6f645822a083.png)

**Comment by mmmulani** [comment]
the rendering in Japanese looks a bit off for me

it should look like this
![image](https://user-images.githubusercontent.com/192928/140563626-0abc8a70-b1f7-4b40-a4ca-0e3affe2c4d2.png)

but in your rendering, it's different.

it could be a matter of NSLocale preferredLanguages though?

**Comment by kevinyang372** [comment]
@mmmulani The is because we use Apple's default font fallback list for rendering glyphs unsupported by the current user font (See [CTFontCopyDefaultCascadeListForLanguages](https://developer.apple.com/documentation/coretext/1509992-ctfontcopydefaultcascadelistforl)). Right now we hard-coded the `languagePrefList` to be english and that's why 非常 gets rendered in a Chinese font first. Ideally in the future we should open this up to user settings:

Iterm also seems to have the same issue:
![image](https://user-images.githubusercontent.com/30107576/140565158-c8597a42-3be8-4f15-99bb-90003f38ea05.png)

**Comment by mmmulani** [comment]
iTerm seems to not have the issue for me:
![image](https://user-images.githubusercontent.com/192928/140566645-ceacaf3d-1b46-45f5-8cc1-0138966a3a43.png)

my [NSLocale preferredLanguages] are:
```
(
    "en-GB",
    "ja-JP"
)
```

presumably you could pass that into the font fallback list instead of making it a user setting?
