### ISSUE TITLE
Getting an issue when trying to subshell rails console

### ISSUE THREAD

**Issue by Marc-Armillas** [warpdotdev/Warp#3294]
### Describe the bug

I add the rails console command in settings/subshells/commands
<img width="746" alt="image" src="https://github.com/warpdotdev/Warp/assets/90630153/33a0d438-1861-4ef9-b1f3-267fab28680c">

When I run the `rails c` command and I click on 'Wrapify subshell' appears this code instead of wrapifying the subhsell.
<img width="1721" alt="image" src="https://github.com/warpdotdev/Warp/assets/90630153/a4dfaa4b-a7e6-498f-93cd-457455898368">

### To reproduce

1. Add the command in settings/subshells/commands

2. Click on Wrapify subshell

### Expected behavior

Wrapify the rails console as a subshell

### Screenshots

<img width="1711" alt="image" src="https://github.com/warpdotdev/Warp/assets/90630153/722f57fe-acf9-4f33-8019-fec1a022515b">

### Operating system

MacOS

### Operating system and version

13.4.1 (22F82)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by zachbai** [comment]
Hey @Marc-Armillas, the issue here is that rails consoles aren't supported subshells in Warp. The feature provides support for bash,fish, or zsh subshells (e.g. those backed by a unix shell) as opposed to a non-shell REPL. You can follow #64 for progress on support for non-shell REPLs like `rails` and the `python` interpreter, but its a tricky technical challenge and unlikely to be implemented in the near term.
