### ISSUE TITLE
Option to flip the terminal flow

### ISSUE THREAD

**Issue by EslamElHusseiny** [warpdotdev/Warp#3306]
### Describe the solution you'd like?

```Text
It would be nice to have an option to flip the terminal flow to be top to bottom instead of the current one.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @EslamElHusseiny There are options for starting or pinning the input to the top which you can learn more about here: https://docs.warp.dev/appearance/input-position

Essentially, the pinned at-the-top behavior is what you're describing in this request so I'll close this one out as completed since the feature already exists, but feel free to let us know if any issues with the feature.
