### ISSUE TITLE
The global hotkey not work untill  reopen the warp

### ISSUE THREAD

**Issue by JasonLamv-t** [warpdotdev/Warp#3325]
### Describe the bug

Same as the title.

### To reproduce

I set the global hotkey 'Ctrl + space' to show/hide all windows in the feature.

### Operating system

MacOS

### Operating system and version

13.4.1 (22F82)

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @JasonLamv-t This repros, but in general Hotkey Window shortcut doesn't open Warp for the first time, it must always be opened first before you can use the feature. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by JasonLamv-t** [comment]
> Thanks for letting us know @JasonLamv-t This repros, but in general Hotkey Window shortcut doesn't open Warp for the first time, it must always be opened first before you can use the feature. We'll post any updates on this thread.

I know that. Actually, I am saying that it will work if you newly launch the warp, but the hotkey will not work after a while. You have to exit the warp app and launch it again.

**Comment by dannyneira** [comment]
Closing as not planned.

**Comment by lljxww** [comment]
😩 That's why I use iTerm.

**Comment by JasonLamv-t** [comment]
> 😩 That's why I use iTerm.

It seems to be working well recently, u can try it back @lljxww .

**Comment by AlexisZankowitch** [comment]
I have a similar issue, the global hotkey set up to show/hide all window stops working properly, but for me this is happening when I open a new warp terminal. To make it work again I have to quit warp and reopen it again. 

I like to open one warp terminal per desktop because I would have one code editor per desktop (I'm one of those guys who are not using any other screens than the one of their laptops). So it happens quite often that I open a new project (I'm a consultant therefore working for several customers every day 😬) and then this is when this issue occurs.

I made a video that showcases the issue, perhaps it's more understandable than my words:
- I use the hotkey to hide warp ✅
- I use the hotkey to show warp ❌
- I do previous steps multiple times
- I quit warp and use the hotkey again and hide and show are working fine

https://github.com/user-attachments/assets/b8ad8887-b081-4535-9bdd-1763aa429198
