### ISSUE TITLE
Wrong aligment of warp in full screen

### ISSUE THREAD

**Issue by maver1ck** [warpdotdev/Warp#3369]
### Describe the bug

Top bar of Warp should be aligned to left after full screen. 
Currently it leaves free space.
![image](https://github.com/warpdotdev/Warp/assets/4006010/5733dc0e-e1df-4799-81e0-5c933019375c)

### To reproduce

Maximize Warp to full screen.

### Operating system

MacOS

### Operating system and version

13.4.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for the callout @maver1ck, I suspect those elements may have the gap so that they don't overlap with the close/min/max buttons, but I agree that ideally, they should move over and fill the empty space. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Thanks for the callout @maver1ck, I suspect those elements may have the gap so that they don't overlap with the close/min/max buttons, but I agree that ideally, they should move over and fill the empty space. We'll post any updates on this thread.

Please add a 👍 to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Fix released in Warp `v0.2023.12.12.08.02.stable_04` and above. Thanks for reporting @maver1ck!

![CleanShot 2023-12-28 at 13 36 19](https://github.com/warpdotdev/Warp/assets/16809145/a4a3f156-483f-47b7-b200-876726241a46)
