### ISSUE TITLE
Prompt issue with oh My Zsh and PowerLevel10k

### ISSUE THREAD

**Issue by sfxandy** [warpdotdev/Warp#3387]
### Describe the bug

Zsh prompt begins on a new line when using Powerlevel10k plugin for Oh My Zsh!

If i run `p10k configure` and select "One line" for the "**Prompt Height**,  after configuration is saved and applied the prompt beings on a second line.

If i run `p10k configure` and select "Two lines" for the "**Prompt Height**,  after configuration is saved and applied the prompt beings on a third line.

However, to complicate matters, using either the "One line" or "Two lines" configuration above, if I issue the command `exec zsh` then the prompt appears to obey the configuration correctly.

As an unfortunate side effect of the `exec zsh` command, the Unicode rendering colours seem to break and the cursor no longer flashes.

### To reproduce

Pre-requisites:

- A suitable font with Powerline glyphs installed. I personally use the [JetBrainsMono Nerd Font](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip)

1. Configure Oh My Zsh! to use Powerlevel10k as the Zsh theme
2. Run the command `p10k configure`
3. Respond to the 4 prompts regarding font selection and display cahracteristics - a response of `y` is valid when using the font outlined above.
4. At the **Prompt Style** screen, select "(3) Rainbow"
5. At the **Character Set** screen, select "(1) Unicode" 
6. At the **Show current time?** screen, select "(2) 24-hour format" 
7. At the **Prompt Separators** screen, select "(1) Angled"
8. At the **Prompt Heads** screen, select "(1) Sharp"
9. At the **Prompt Tails** screen, select "(1) Flat"
10. At the **Prompt Height** screen, select either "(1) One line" **OR** "(2) Two lines"
11. At the **Prompt Connection** screen, select "(1) Disconnected"
12. At the **Prompt Frame** screen, select "(1) No frame"
13. At the **Prompt Spacing** screen, select "(2) Sparse"
14. At the **Icons** screen, select "(2) Many icons"
15. At the **Prompt Flow** screen, select "(1) Concise"
16. At the **Enable Transient Prompt** screen, select "(n) No"
17. At the **Instant Prompt Mode** screen, select "(1) Verbose"

Save/overwrite the configuration so the above configuration reloads.
 

### Expected behavior

As per the screenshot of my terminal in Kitty, the prompt should begin on the second line immediately after the green chevron character.

### Screenshots

![CleanShot 2023-07-18 at 14 11 08@2x](https://github.com/warpdotdev/Warp/assets/137955820/b10650f9-41d7-4e9e-b7f8-42ce969428ca)

![CleanShot 2023-07-18 at 14 10 19@2x](https://github.com/warpdotdev/Warp/assets/137955820/9ad904e0-b394-40be-a602-d474fa2be6b6)

![CleanShot 2023-07-18 at 14 12 10@2x](https://github.com/warpdotdev/Warp/assets/137955820/10664582-91bd-4d54-bfca-e985a7491e55)

### Operating system

MacOS

### Operating system and version

Ventura 13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.07.11.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @sfxandy The reason for this is if you run `exec zsh`, it enters zsh in [subshell](https://docs.warp.dev/features/subshells) mode, without Warp features. Since Warps input editor behaves [like an IDE](https://docs.warp.dev/features/editor) ( multiple cursors, completions, etc.), there is a wrapper around it that keeps it separate from the [prompt](https://docs.warp.dev/features/prompt). I hope this clears up the different between the prompt and input, and why they are separate in Warp, vs other terminals (or `exec zsh`).

So in essence, this isn't so much a bug, but an implementation and design decision to keep the prompt and input separate for the sake of improved functionality. As a possible workaround, you can set up p10k to be one line, then the input will be in the second line (this is normal and necessary for Warp features). I hope this helps.

Closing as this isn't a bug.
