### ISSUE TITLE
Tab should autocomplete single suggestion

### ISSUE THREAD

**Issue by jpeyper** [warpdotdev/Warp#340]
### Describe the solution you'd like?

```shell
When you refine the auto complete suggestion window down to a single item, pressing tab should complete the suggestion the same as if you had typed that much and pressed tab.
```

### Is your feature request related to a problem? Please describe.

```shell
Coming from iterm2, it breaks my flow to switch to use enter and use arrow keys in the auto complete suggestion window. I prefer to continue typing and use tab.

In warp, tab does not autocomplete when there is only 1 item in the auto complete, I have to use enter. It feels inconsistent to me compared to if I had typed enough the first time.

Let me explain (or attempt to)...

type: cd dev<tab>

It autocompletes to "development" if it's the only suitable match.

type: cd de<tab>

The autocomplete suggestion window shows:

demonstration
development

type: v

autocomplete suggestion window just shows "development" now

type: <tab>

Nothing happens.
```

**Comment by elviskahoro** [comment]
Should have been fixed. Comment or reopen if not!

**Comment by lexicondigitalchallenge** [comment]
I dont see any change to behaviour on v0.2021.11.16.20.05.stable_01

am i waiting for a particular version?

**Comment by jpeyper** [comment]
I dont see any change to behaviour on v0.2021.11.16.20.05.stable_01

am i waiting for a particular version?

**Comment by elviskahoro** [comment]
@jpeyper no you were right! I accidentally had this linked to a similar but different issue internally.

**Comment by meredian** [comment]
@elviskahoro I have very similar request - I think they could be generalised together.

Clicking tab should autocomplete to the largest common part of all available suggestions right away. And suggest list if >1 suggestions. (Liked experience from iTerm)

1. If only one suggestion - it works exactly as @jpeyper mentioned.
2. If there's > 1 suggestions - it fills largest common part & opens suggestion link (so I could type distinct part on my own or use suggestion).

Real usecase:
When working logs, they usually have similar long prefix, but date part is different:
```
system_logs_with_some_service_depfinition-production.2021.06.23T15:00:00-15:05:00.log
system_logs_with_some_service_depfinition-production.2021.06.23T15:05:00-15:10:00.log
system_logs_with_some_service_depfinition-production.2021.06.23T15:10:00-15:15:00.log
system_logs_with_some_service_depfinition-production.2021.06.23T15:15:00-15:20:00.log
system_logs_with_some_service_depfinition-production.2021.06.23T15:20:00-15:25:00.log
.... (a lot of other files)
```
So workflow is
1. You click `tab` to complete whole `less system_logs_with_some_service_depfinition-production.2021.06.23T15:` part
2. You manually start typing exact timeframe, e.t. `05`
3. Complete with `tab` again to get full file name

Since there could be hundreds of files with similar names in a folder, showing full list right away is not really helpful.

**Comment by elviskahoro** [comment]
From @fishcharlie via #619

### Describe the solution you'd like?

```shell
See attached screenshot.

In that instance, with only 1 item in the list, hitting `Tab` should be identical to `Enter` and should select that item from the list.
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

<img width="364" alt="Screen Shot 2022-01-17 at 2 44 34 PM" src="https://user-images.githubusercontent.com/860375/149840155-86a82881-9380-4316-9da8-55d406e24280.png">

Possibly Related: #618

**Comment by fishcharlie** [comment]
Since @elviskahoro marked my issue as a duplicate. I'd like to post my related comment here as well.

https://github.com/warpdotdev/Warp/issues/618#issuecomment-1016848409

**Comment by elviskahoro** [comment]
Thanks @fishcharlie

**Comment by juno-w** [comment]
Yes, I'm coming from iTerm2 and pressing Tab should serve as Enter.

**Comment by StevenLi-DS** [comment]
I need this so bad. It seems like there are a couple of opened issues for this. Could you guys consider adding a toggle to let users use a TAB to select/enter autocompletion, like in vscode?

**Comment by OneComputerGuy** [comment]
There's another scenario that is currently not being contemplated (or at least I haven't seen any issue for it):

There are certain commands that don't need any parameters or additional information, i.e.: `cd` when you're going from any folder to the home folder or a simple `ls`.

As of right now, when you type the command, the auto-suggestion box shows up automatically when you hit space after the command, which is inconvenient since it forces the user to hit Escape before hitting Enter (If you hit Enter right away, you will fill the first auto-suggestion shown instead of executing the command). 

I know this could be a niche use case, but the auto-suggestions should have at least a toggle like "show on tab" that will allow showing the box after hitting tab for us that hit space after single commands 😅

**Comment by szgupta** [comment]
@OneComputerGuy could you confirm if you have the `Open completions menu as you type` feature turned on? If so, disabling it should give you the behaviour you'd like!

<img width="708" alt="Screen Shot 2022-11-15 at 3 05 04 PM" src="https://user-images.githubusercontent.com/39461854/202014894-8651cead-2fe7-454e-b2c3-f5c1cdca62c8.png">

**Comment by szgupta** [comment]
@OneComputerGuy just to confirm, the setting you're proposing is to show the completions menu after hitting tab? If so, that's actually the default behaviour! (e.g. `cd <tab>`)

**Comment by OneComputerGuy** [comment]
@szgupta Ah! I see what you mean now! User error was the source of the issue 😅. It does work as expected.

Thanks for the help!
