### ISSUE TITLE
aliases like "..." and "...." in zsh/ohmyzsh would be incorrectly underlined with red lines

### ISSUE THREAD

**Issue by Saafo** [warpdotdev/Warp#3409]
### Discord username (optional)

Saafo

### Describe the bug

aliases like "..."(for "../..") and "...."(for "../../..") would be incorrectly underlined with red lines

### To reproduce

1. install zsh and ohmyzsh
2. type "..." or "...."
3. it will be incorrectly underlined

### Expected behavior

The word is green and no underline

### Operating system

MacOS

### Operating system and version

13.4

### Current Warp version

v0.2023.07.18.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @Saafo Thanks for letting us know. I was able to reproduce this issue with the underlines in oh-my-zsh. As a workaround, I recommend you disable the [error underlining](https://docs.warp.dev/features/editor/syntax-error-highlighting#what-is-error-underlining). We'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by Saafo** [comment]
Fixed in the latest release!

**Comment by AlecRust** [comment]
Looks like e.g. `npm` still underlines
<img width="158" alt="image" src="https://github.com/warpdotdev/Warp/assets/247634/c16f0a35-4a77-4fa2-b64e-9039edd4d263">

**Comment by Saafo** [comment]
npm works fine for me
<img width="181" alt="image" src="https://github.com/warpdotdev/Warp/assets/46736350/bad64e81-54b0-4248-80fd-a6a63dac55b1">

**Comment by dannyneira** [comment]
@AlecRust If npm has been recently installed, you need to open a new session for the underlines to go away. https://docs.warp.dev/features/editor/syntax-error-highlighting#what-is-error-underlining

**Comment by AlecRust** [comment]
@dannyneira thanks, but I've had npm installed for a while.

I see it works for some people like @Saafo, where `npm` is not underlined as an invalid command, and the syntax highlighting is even working. It looks like these issues are connected, and neither is working for me. I created #3772 about the command highlighting specifically.

My npm/Node is installed via rtx instead of Homebrew, that's the only difference I'm aware of though.

![image](https://github.com/warpdotdev/Warp/assets/247634/0af85a15-4b6e-400d-9d62-8c66f994c6f6)

The npm command works fine, Warp just doesn't seem to recognize it.
