### ISSUE TITLE
Completions Support MacPorts 

### ISSUE THREAD

**Issue by Gregory-Gelfond** [warpdotdev/Warp#343]
### Describe the solution you'd like?

```shell
Ideally we could have support for completions of `port` and `brew` provided by the [MacPorts](https://www.macports.org) and [HomeBrew](https://brew.sh) package management projects respectively.
```

**Comment by Gregory-Gelfond** [comment]
Maybe even parse a command's manpage to learn it's command completions and options.

**Comment by elviskahoro** [comment]
We're actually scoping out completions this week and next so that we can really think through the UX and design something that scales, like your idea mentions. I'm working on mapping out our autocompletion coverage so we can get a holistic idea of what we're missing. I'll circle back with updates in this issue: https://github.com/warpdotdev/warp/issues/212

**Comment by elviskahoro** [comment]
@Gregory-Gelfond we added brew but haven't added macport yet

**Comment by elviskahoro** [comment]
Moved to:
- #434

**Comment by elviskahoro** [comment]
@Gregory-Gelfond Moved to #652 instead!
