### ISSUE TITLE
Add keyboard shortcut for closing Warp Drive

### ISSUE THREAD

**Issue by sannajammeh** [warpdotdev/Warp#3483]
### Describe the solution you'd like?

```Text
I can only find an `Open Warp Drive` keyboard shortcut. I'd like one for toggling the `Warp Drive` instead. I use Arc browser so I'm very used to being able to toggle side panes in VSCode and Arc with a single shortcut, but there's only a way to open the drive not closing it.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request @sannajammeh! You're 100% correct, we have a toggle for Warp AI, but not for Warp Drive so that would make sense as an enhancement. We'll post any further updates on this thread.

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hey Folks, we're closing this one as resolved as the feature has been built into Warp and Warp Drive side-panel can be toggled with `CMD-\`. https://docs.warp.dev/features/warp-drive#how-to-access-it
