### ISSUE TITLE
Show timestamps for history items

### ISSUE THREAD

**Issue by ivant** [warpdotdev/Warp#3485]
### Describe the solution you'd like?

```Text
It would be really nice to have some idea of when I typed some particular command when I am choosing it in the Command Search popup. A timestamp (preferably, in `%F %T` format) would be nice.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @ivant Thanks for this feature request! We're working on a richer history that should help with this request. Stayed tuned to our changelog for any changes in this area. 

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by zachbai** [comment]
@ivant Closing this out as timestamp is now shown in Command Search (bound by default to ctrl-R) , as well as in a floating window next in "up-arrow" history.

**Comment by ivant** [comment]
While it indeed now shows when the command was run, it is not a timestamp, but only an approximate time/date reference, and doesn't serve the purpose of establishing exactly when I ran some command (e.g. if I need to correlate that time to some other event when debugging or writing a postmortem).

I understand the need to keep the UI visual node down, but could you provide a full timestamp in addition to the current information (e.g. in the floating window)?

**Comment by myrison** [comment]
The current feature is definitely lacking.  Here is why it doesn't work well as implemented.  If I am running a history of several multi-line commands where the content differs only slightly within the command, scrolling up through the command history, I cannot determine which command was run at which time, because they all look the same.   Also, the approximate date/time reference is not good enough when troubleshooting something.  This fairly basic lack of a feature has me moving on to another terminal for now even though I really like everything else about Warp.  I'll stay subscribed in the hopes that something changes.

**Comment by ansonkao** [comment]
+1 why not have a timestamp at least on hover over the relative time? or just adjacent

**Comment by ansonkao** [comment]
Turns out there IS a tooltip with timestamp, it's just not easily discoverable https://github.com/warpdotdev/Warp/issues/2415
