### ISSUE TITLE
Unable to get fish shell suggestions that contain but do not start with given string

### ISSUE THREAD

**Issue by gerardsimons** [warpdotdev/Warp#3500]
### Describe the bug

I actually added it as a comment to another issue about the history not being available, but turns out that was not the issue:

https://github.com/warpdotdev/Warp/issues/3476#issuecomment-1666159876

So when you type `Desktop` and then up `ls Desktop` does not appear, but when I do `ls` it does.

It works on iTerm and Terminal. It also works when I do not use a warpified shell, as shown in GIF, by typing `fish` again in Shell.

### To reproduce

Not sure how to reproduce ... This was not default behavior I think?

### Expected behavior

I was expecting substring matching to work even when the command does not begin with the string typed. 

### Screenshots

There is a video attached to the issue comment

### Operating system

MacOS

### Operating system and version

Ventura 13.2.1

### Shell Version

fish, version 3.6.1

### Current Warp version

v0.2023.08.01.08.05.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Not sure

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @gerardsimons Thanks for submitting this. As shell-based completions isnt supported i suspect this may be why the partial history search in fish isn't working as with other terminals. As a stopgap you can use the [Command Search (CTRL-R)](https://docs.warp.dev/features/entry/command-search) feature to look for history commands containing the work desktop, you can even filter for history only otherwise it will show everything that contains desktop including workflows, etc..

https://github.com/warpdotdev/Warp/assets/16809145/0f1b6aff-5f40-46db-859a-18d78d0c20c7

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by gerardsimons** [comment]
@dannyneira : Thanks for the quick reply and the work-around for now! Will use that until hopefully support comes for the fish suggestions :)
