### ISSUE TITLE
Missing command output

### ISSUE THREAD

**Issue by cwee005** [warpdotdev/Warp#3554]
### Describe the bug

The output of a command (e.g, ls, pwd) is not displayed the first time the command is used. Subsequent use will displayed the output but the behavior is repeated after a different command is used. The command without the output is also missing from the bash command history.

https://github.com/warpdotdev/Warp/assets/49134310/ca373e37-8cea-4de4-a3d0-934bfe3be87b

### To reproduce

See attached file for behavior. 

### Operating system

MacOS

### Operating system and version

Ventura 13.5

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.08.15.08.03.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this only happened in Warp. This behavior does not manifest in macOS Terminal

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @cwee005 Sorry you're facing this issue. Did this start happening recently for you in Warp or was it always an issue? Also, could you please review your `~/.zshrc` file for [unsupported plugins/tools](https://docs.warp.dev/help/known-issues#list-of-incompatible-tools)(the most common culprit for this issue is the `iterm2_shell_integration`)? If found, you can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

**Comment by cwee005** [comment]
I figured out what was causing the problem in the .zshrc file:

PROMPT='%F{yellow}%n@%m:%/ %#>%f%'

The issue went away once I remove the line above.
