### ISSUE TITLE
Allow to disable ↑ bringing up history

### ISSUE THREAD

**Issue by peczony** [warpdotdev/Warp#3587]
### Describe the solution you'd like?

```Text
I’d want an option to disable up arrow bringing up command history pane.
```

### Is your feature request related to a problem? Please describe.

```Text
I use atuin (https://github.com/ellie/atuin) and want to keep using it. I’d love to try out great features Warp offers, but don’t want to give up atuin.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @peczony Sorry about this, but don't think we're likely to implement this any time soon, so marking it as canceled. atuin isn't compatible with Warp's input, but we've recently added [rich history information](https://docs.warp.dev/features/entry/command-history) which should help some. 

![CleanShot 2023-08-31 at 14 51 27](https://github.com/warpdotdev/Warp/assets/16809145/5f19581d-c252-47e8-a59b-bf9c35e0701c)

Warp also has Command Search which you can use to filter through the history as well.

I hope this helps some with your use cases.

**Comment by curtisbelt** [comment]
@zachbai recently said this about supporting Atuin:
> I think there's something we can get working here. I have a ticket for us to track this internally,

(from https://github.com/atuinsh/atuin/issues/1405#issuecomment-1912594520)

Can we re-open this for tracking purposes?

**Comment by zachbai** [comment]
@curtisbelt Could you provide some more detail on why disabling up-arrow history is desirable if you're using atuin?  Is it because up-arrow is bound to some other atuin action?

**Comment by curtisbelt** [comment]
@zachbai Hello! Hmm.

From https://github.com/atuinsh/atuin/issues/1405#issuecomment-1912594520:

> Re: https://github.com/atuinsh/atuin/issues/1405#issuecomment-1823952133, that makes sense and I think there's something we can get working here.

I took your comment to mean that the up arrow may be possible to implement and that you're tracking an internal ticket for that? After I saw that, I searched Warp issues ([warpdotdev/Warp/issues?q=atuin](https://github.com/warpdotdev/Warp/issues?q=atuin)) to see if there was something "more official" I can follow for updates.

I can just follow that issue on Atuin, since you mentioned you would follow up there if/when progress is made. I also just noticed the issue was created by someone on the Warp team so that's pretty official. Sorry for the distraction 😄

**Comment by zachbai** [comment]
No worries at all, was just looking to clarify! So my impression is that default up-arrow behavior in Warp (to bring up our command history UX) conflicts with atuin? If/when we get around to tackling better compatibility for atuin, the right behavior for up-arrow will definitely be considered (possibly configurable?)

**Comment by ellie** [comment]
> So my impression is that default up-arrow behavior in Warp (to bring up our command history UX) conflicts with atuin

Correct - by default Atuin binds to both the up arrow and ctrl-r. For full compatibility, disabling Warp's history UI keybindings would be required.

**Comment by anirudhsama** [comment]
Even when after launching Atuin with `atuin search -i` and selecting a command, it doesn't put it on the current block to be executed. We have to manually copy it. Can this behaviour be fixed as a workaround?

**Comment by aronchick** [comment]
I am really interested in Warp, but like Atuin enormously. If forced to choose, I'd choose the latter. Please don't make me choose :)

**Comment by silverjam** [comment]
I love a lot of the features in Warp too (especially notebooks and workflows), but I can't use Warp because it breaks fish shell completion... I would suggest an alternative mode of interacting with the interactive shell command line that integrates more tightly with the shell (similar to what atuin does) itself rather than completely replacing it with a GUI thing.

**Comment by zachtrong** [comment]
Can I just simply disable Rich History popup, it's quite annoying since it block my recent commands output.

**Comment by hawktang** [comment]
if atuin can not be use, at least make it is searchable with up.

ctrl-R will interrupt the work flow

**Comment by lukas-pierce** [comment]
Please reopen.

After the latest update, this annoying behavior with Warp has appeared again.
In general, all popups and overlays should be optional and allow the user to disable them.

There are two reasons why this must be configurable:

1. The history may contain authorization keys that I use for connections, and when I share my screen I don't want anyone to see them.
2. Any popup is distracting.
