### ISSUE TITLE
DUP: Duplicate of #159 - vi (vim) mode

### ISSUE THREAD

**Issue by lak** [warpdotdev/warp#361]
### Describe the solution you'd like?

```shell
I would like vi mode in the shell, like I do in every other terminal. E.g., escape-K to search through history, escape to edit the current shell command, escape + v to open the current command in a terminal. This is all built into the shell, not the terminal, right? So I don't see why it would be changed.
```

### Is your feature request related to a problem? Please describe.

```shell
I'm being generous in calling this a feature request, IMO, given it's built into the shell, not the terminal, and it's been a part of shells going back to at least ksh.
```

**Comment by elviskahoro** [comment]
The very same design and architecture that enables a modern input editor, blocks, future features is the same reason that vi-mode does not work automatically via the shell. This is something that we will have to build natively. I use vi-mode myself so you can trust it'll be pushed for, but realistically speaking we're still very early in the product roadmap.

**Comment by JasonTheAdams** [comment]
Just started testing it out and this is my first desired feature. Honestly, it wouldn't need to be crazy vim support (i.e. macros), but just basic things like the Visual and Insert mode, vertical selection, basic key support, and so forth. Since it's ground up I'm sure it would be quite a bit of work. Still, it would be awesome.

**Comment by elviskahoro** [comment]
@JasonTheAdams IKR! it would be so much fun.
