### ISSUE TITLE
[Change wording] Change wording of "Copy both"

### ISSUE THREAD

**Issue by muescha** [warpdotdev/Warp#3656]
### Discord username (optional)

Muescha#3499

### Describe the solution you'd like?

there is in context menu the menu items:

```
Copy command
Copy output
Copy both
```

The menu item 'both' was a long time unclear for me what this means.

Better rename it to 'Copy command and output'

```
Copy command
Copy output
Copy command and output
```

### Additional context

<img width="438" alt="Bildschirmfoto 2023-09-12 um 21 54 36" src="https://github.com/warpdotdev/Warp/assets/184316/a57594d9-aaf4-4ec4-bebe-83f45e8f4bc3">

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @muescha We've updated the wording on the block menu to say "Copy" instead of "Copy both".  This will copy the entire block ( command and output ) by default, but if a specific text is selected, it will only copy the selected text. Hope this helps with clearing up your request.

![CleanShot 2023-12-11 at 15 40 22](https://github.com/warpdotdev/Warp/assets/16809145/d9031499-942d-4b2f-9e14-38e47cd0e3bd)

We'll be closing this feature request as complete, but please do let us know if any issues.

**Comment by muescha** [comment]
great :)

I like the shorter `copy` - less text is better :)
