### ISSUE TITLE
using homebrew to install warp on linux based distros?

### ISSUE THREAD

**Issue by daUnknownCoder** [warpdotdev/Warp#3664]
### Describe the solution you'd like?

```Text
hey guys, @WarpWing, can we try installing warp with homebrew on linux based distros?
```

### Is your feature request related to a problem? Please describe.

```Text
no support for linux ...
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

Ignore

**Comment by SilentGlasses** [comment]
Should close this out as done since there is no Linux version as yet.

Keep in mind that even tho Homebrew is available on Linux, not all apps on it are installable due to the app not being a Linux app or the tap not being written for Linux.

I had the same issue a while back with Nerd Fonts as the tap is totally different than the macOS one.
