### ISSUE TITLE
Ability to disable Enter to accept autosuggestions

### ISSUE THREAD

**Issue by LauraLangdon** [warpdotdev/Warp#3767]
### Discord username (optional)

737336038372016269

### Describe the solution you'd like?

```Text
I'd love to have the option to not have Enter accept autosuggestions.
```

### Is your feature request related to a problem? Please describe.

```Text
I don't want Enter to accept autosuggestions, because when I type `git add .`, for instance, I can't just hit Enter to send the command; instead that will accept an autosuggestion to add a specific file instead of all files, which is what I'm trying to do. Hitting Esc before Enter works, but it's annoying to have to use an extra keystroke. But also! I enabled Vim bindings (😍), which of course means Esc switches me into Normal mode. So now instead of being able to just type `git add .` and hit Enter, I have to type `git add .`, then Esc, then i. 😭

In Settings -> Features -> Editor I've set the Tab key behaviour to accept autosuggestions, which I thought/hoped would mean Enter would no longer accept autosuggestions, but it actually means both of those keys accept autosuggestions.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @LauraLangdon thanks for submitting. So your issue may be due to the fact that "Completions as you type" is enabled, so when you see the completion menu, ENTER, accepts the current suggestion on the list. You can [disable that in the settings](https://docs.warp.dev/features/command-completions/completions#how-to-access-it), or you can also rebind the behavior for opening the completion menu. The "Tab key behavior" setting under Features > Editor can change the action that Tab is bound to. If Tab is not bound to open the completions menu, ctrl-space will be assigned as the default keybinding.

Please let me know if this helps with your use case, or what you're like to see differently.

**Comment by LauraLangdon** [comment]
Hmm, but I do want the completion menu to show up as I type. 😁 I just checked how Fig handles this, and '.' is actually the default suggestion in the `git add .` case, so I do get to have the completion menu show up as I type *and* hitting Enter results in the expected behaviour:

![CleanShot 2023-10-12 at 19 35 46@2x](https://github.com/warpdotdev/Warp/assets/48335772/f9ab4379-6d3d-4f72-a31f-fced4ca98692)

Whereas in Warp the default suggestion is '.idea':
![CleanShot 2023-10-13 at 09 26 43@2x](https://github.com/warpdotdev/Warp/assets/48335772/c9cef033-84dd-4a70-aaf0-94fb135a22d0)

**Comment by dannyneira** [comment]
We will be tracking this request over at https://github.com/warpdotdev/Warp/issues/1806 since we would need to allow the ability to remap the ENTER key to accept suggestions.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
