### ISSUE TITLE
"clear" command not working with other commands

### ISSUE THREAD

**Issue by michael-lucas-net** [warpdotdev/Warp#3776]
### Describe the bug

i have created an alias for listing all files in a directory:

`alias lst="clear && tree -L 1"`

i noticed that this command only clears the editor, but does not use the command tree.

I tried it with other commands like 

`echo "hi" && ls`

this works.

But `clear && echo "hi" `

does not work!

### To reproduce

just write linked commands like `clear && ls` it will only clear.

### Expected behavior

it should also execute the second command

### Operating system

MacOS

### Operating system and version

Sonoma (14)

### Shell Version

zsh 5.8 (arm-apple-darwin21.1.0)

### Current Warp version

v0.2023.10.10.08.06.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I asked a friend of mine who also uses warp. he could reproduce.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @michael-lucas-net There is a related known issue in Warp where clear runs alongside any others you have in the same command (i.e. run `clear ; ls`) and the block with the output is the same as the block with the clear instead of running after.

We have a related feature request to track this here: https://github.com/warpdotdev/Warp/issues/2382

We'll post any updates on that thread when we have them. Closing this one as a duplicate.
