### ISSUE TITLE
Hold down key to scroll not working?

### ISSUE THREAD

**Issue by wallyfaye** [warpdotdev/Warp#3803]
### Describe the bug

I have an issue and i don't know  if it's been asked before (although I've searched for a while now)

When I do something like git diff and hit j to scroll down, i can't hold down j like i do when I use my regular Terminal app that comes with Mac. I have to keep pressing j repeatedly which only goes one line at a time. Obviously I can use other vim commands, but I want to know why i can't just hold down j. What do I need to do?

### To reproduce

make a big change to a document so that you can scroll and do `git diff` and hit j to scroll down. note that you can't hold down j like the regular Terminal app that comes with Mac

### Operating system

MacOS

### Operating system and version

13.6 (22G120)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.10.17.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment]
Terminal.app overrides the default macOS behavior of press-and-hold opening a accented character picker dialog.  We added a similar override to Warp at some point, but only for new users (to avoid breaking expected behavior for existing users).  I'm guessing you first installed Warp before we added that logic.

You can override it yourself by running the following command: `defaults write dev.warp.Warp-Stable "ApplePressAndHoldEnabled" -bool false`.  Run that and restart Warp, and it should work the way you expect. :)

**Comment by wallyfaye** [comment]
Thanks @vorporeal - you know, I recently updated my Warp and it just started magically working without me even having to do anything! Thanks very much!

**Comment by untoldone** [comment]
As an aside, I just installed from scratch for the first time on a clean installed mac and had this same issue. The same fix suggested fixed it -- I'm guessing that default changed again at some point since the posted fix.
