### ISSUE TITLE
starship formatting over ssh in subshell

### ISSUE THREAD

**Issue by alexdauenhauer** [warpdotdev/Warp#3819]
### Operating System

Linux

### Operating System and Version

Debian GNU/Linux 10 (buster)

### Local Shell Version

fish, version 3.6.1

### Remote Shell Version

fish, version 3.6.1

### Warp Version

v0.2023.10.17.08.03.stable_02

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

you can ignore the above checkbox, that is irrelevant. locally I have this in my `config.fish` file
```fish
if test "$TERM_PROGRAM" = "WarpTerminal"
    set -x STARSHIP_CONFIG $XDG_CONFIG_HOME/starship_warp.toml
end
```
and that works great because I want format my starship prompt differently if I use iterm2. If I put that same line in my remote `config.fish` file it does not detect that I am using warp when I do "warpify subshell". I am wondering if there is a way to modify that line to make this work on my remote machine?

### Include shell xtrace output

no idea what this is

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @alexdauenhauer You can try putting those line in your fish config.fish toward the end of the file, or before the other if statement to see if that helps with your issue. 
```
if status is-interactive
  printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "fish"}}\x9c'
end

if test "$TERM_PROGRAM" = "WarpTerminal"
    set -x STARSHIP_CONFIG $XDG_CONFIG_HOME/starship_warp.toml
end
```
or
```
if test "$TERM_PROGRAM" = "WarpTerminal"
    set -x STARSHIP_CONFIG $XDG_CONFIG_HOME/starship_warp.toml
end

if status is-interactive
  printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "fish"}}\x9c'
end
```

Please let us know if that helps, you can also try using adding `/usr/bin/ssh` to you Settings > Subshell menu and use that to connect.

**Comment by zachbai** [comment]
Hey @alexdauenhauer it looks like we're actually missing setting `TERM_PROGRAM` in the remote subshell case -- I'll take a look at getting a fix in for this

**Comment by zachbai** [comment]
This is actually trickier than I thought at first glance, because `config.fish` is executed prior to any command that Warp runs as part of Warpifying the session, so even if Warp sets `TERM_PROGRAM` as part of Warpifying the session, the relevant prompt config has already be set.

AFAIK there is no straightforward way for the remote session spawned upon SSH-ing to have $TERM_PROGRAM prior  to execution of config files short of setting `SetEnv` in your `ssh_config` (https://man7.org/linux/man-pages/man5/ssh_config.5.html), but for your use case that seems insufficient because the value should be a function of the terminal emulator not that config file.

The only other obvious option I can think of is for Warp to source some Warp-specific shell config file upon warpifying (something like `warprc.fish`), and you'd be able to put the prompt config there, but that needs some more thinking through

**Comment by alexdauenhauer** [comment]
I think the main reason I wanted this functionality is because I am often connected to my VM in VS code and the terminal there looks funny if I format starship for Warp's requirements. So I think a workaround is that I just check `$TERM_PROGRAM = 'vscode'` instead and that should probably solve my particular issue

**Comment by zachbai** [comment]
@alexdauenhauer did that workaround work for you?

**Comment by alexdauenhauer** [comment]
the warpify subshell does work now. The command suggestions doesn't seem to be fully functional though (I realize this is a separate issue, just commenting on it)

**Comment by dannyneira** [comment]
Closing as the workaround was able to help with the issue. Please feel free to let us know if the issue persists, even with the workaround. Thanks!
