### ISSUE TITLE
view is jumping inside ssh

### ISSUE THREAD

**Issue by Anton6896** [warpdotdev/Warp#3848]
### Discord username (optional)

anton6896

### Describe the bug

view is jumping inside ssh if resizing or making ^l ...

https://github.com/warpdotdev/Warp/assets/33595542/17dda52c-0690-43c1-b08e-619f0ec78b55

### To reproduce

1. get ssh connection 
2. do some job 
3. push ^l or clear, try to resize window 

### Expected behavior

expected that the text is stay in visual area of work box start position on `^l` or `clear` command

### Screenshots

video adjusted in describe section

### Operating system

MacOS

### Operating system and version

14.1.0

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)

### Current Warp version

v0.2023.10.31.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Anton6896 Thanks for submitting. Sorry if this is a blocker for you, but it's related to the sticky command header. As a temporary workaround, you can disable [sticky command header](https://docs.warp.dev/features/blocks/sticky-command-header).

We're tracking this issue here https://github.com/warpdotdev/Warp/issues/3214, if you could, please subscribe to that issue for updates on the status of this bug.
