### ISSUE TITLE
Not work via jumpserver，

### ISSUE THREAD

**Issue by wonb168** [warpdotdev/Warp#3911]
Not work via jumpserver，
First，I use `ssh jump@jumpserver`,
then, `p`
then, `1`
then input username and password into the target server,
then all in one block,and can't use all warp features

<img width="544" alt="image" src="https://github.com/warpdotdev/Warp/assets/25274931/6298ad9c-2ad4-48b6-875a-c88c01fc757c">

HOW to use all feature in target server via jumpserver.

_Originally posted by @wonb168 in https://github.com/warpdotdev/Warp/issues/2100#issuecomment-1816081583_

**Comment by dannyneira** [comment]
Hey @wonb168 this is a known issue with jump servers, since the SSH wrapper is already enabled on the jump server, it treats any further ssh connections like a subshell. You can workaround this by adding the subshell line to your remote ssh server rc files.
```
# For zsh subshells, add to ~/.zshrc.
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'

# For bash subshells, add to ~/.bashrc or ~/.bash_profile.
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "bash"}}\x9c'

# For fish subshells, add to ~/.config/fish/config.fish.
if status is-interactive
  printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "fish"}}\x9c'
end
```
then, once you SSH into the remote server it should automatically warpify the subshell and enable Warp features. https://docs.warp.dev/features/subshells#automatically-warpify-subshells

Please let us know if this was helpful or if you continue to have the issue.

**Comment by wonb168** [comment]
can't work in byobu also， how to solve？
