### ISSUE TITLE
Text input in multi-byte Japanese doesn't appear until confirmation

### ISSUE THREAD

**Issue by shikata1112** [warpdotdev/Warp#3944]
### Describe the bug

Text input in multi-byte Japanese doesn't appear until confirmation

### To reproduce

Open Warp app
Input multi-byte Japanese character in command area or Warp AI

### Expected behavior

Displaying Japanese as it is typed before pressing enter.

![image](https://github.com/warpdotdev/Warp/assets/67092021/7e9bb592-8084-48c0-b6a8-52629f58ce70)

### Screenshots
bad:

![image](https://github.com/warpdotdev/Warp/assets/67092021/7a180bae-09ac-49e3-b068-d94905ac1dc7)

### Operating system

MacOS

### Operating system and version

Sonoma 14.1.2

### Current Warp version

v0.2023.11.28.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @shikata1112, this may be related to a known issue with rendering ligatures you can track here #239

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by odiak** [comment]
@dannyneira Hi, I'm also facing same problem.
Maybe it's not related to ligatures.
Inputting languages like Japanese, Chinese or Korean needs to type some keys and compose characters.

On Warp, characters while typing (and not yet finalized) is not displayed.
If there're some Chinese people in Warp Team, ask them about this problem.
Thanks.

**Comment by Sonnar1824ZA** [comment]
Still reproducible in Warp **v0.2026.07.08.17.54.stable_02** on **macOS 27.0.0**.

A specific context where I can reproduce it is while editing a `.md` file in Warp:

1. Open/edit any Markdown file in Warp.
2. Switch to the Japanese IME.
3. Type a phrase that requires kana-kanji conversion.
4. Before confirming the conversion, observe the composing (preedit/marked) text.

**Actual:** The composing text is completely invisible. The characters appear only after the conversion is confirmed.

**Expected:** The composing text should remain visible while typing and selecting a conversion candidate, so it can be reviewed and corrected before committing.

This appears to be the same underlying issue, so I am adding current-version and Markdown-editing context here instead of opening a duplicate.
