### ISSUE TITLE
Colors differ from Terminal & iTerm

### ISSUE THREAD

**Issue by nodinosaur** [warpdotdev/Warp#3951]
### Describe the bug

I also have iTerm2 and terminal
I use OMZ, Powerlevel10K and Galaxt.terminal theme.
Some how the path and prompt colors do not match the others

### To reproduce

Nothing to reproduce here

### Screenshots

iTerm2:
<img width="710" alt="iTerm2" src="https://github.com/warpdotdev/Warp/assets/2144571/616470eb-3fc3-456b-b405-e5919fac73da">

Warp:
<img width="688" alt="warp" src="https://github.com/warpdotdev/Warp/assets/2144571/7b31d823-c337-42c1-bb0c-b2b8f77defb9">

### Operating system

MacOS

### Operating system and version

Ventura 13.6 and Sonoma 14.1.2

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.12.05.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @nodinosaur bummer to hear about this issue. I recommend you try changing `Settings > Appearance > Enforce minimum contrast` to see if that helps with the issue. If not, it may be because the galaxy theme appears to be designed for iterm2 and the colors may not line up with Warps prompt rendering. If that's the case, you can disable parts of your dotfiles just for Warp by using this conditional statement:

```
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > galaxy theme code here <
fi
```

Please see more info on custom prompts we support here: <https://docs.warp.dev/features/prompt>

**Comment by nodinosaur** [comment]
Thanks for the reply. 
I should correct myself, I use the Galaxy.theme with the default Terminal & iTerm2 and the colors work fine. 
I tried your contrast tio and unfortunately it didn't make any noticeable difference.
Maybe one day this issue can be resolved, thankfully it isn't a show stopper.

**Comment by JasperSui** [comment]
Hey @nodinosaur, not sure if you're still using Warp but I'm facing the same issue here (same galaxy theme user ✨), and I've made a galaxy theme config for Warp ([PR](https://github.com/warpdotdev/themes/pull/112)), hope it helps!
