### ISSUE TITLE
When using an app in a non-full screen mode when using a split view, the app always appears at the top in any view.

### ISSUE THREAD

**Issue by tanobe** [warpdotdev/Warp#3956]
### Describe the bug

Sometimes I make a mistake in a command, and when that happens, I would like to be able to remove the block from my current session and the history.

### To reproduce

I have multiple views in a split view, and when I move the views around, the warp always appears on the screen, except for the view that is in full screen and using some application. However, if I use the warp in full screen, the warp does not appear when I move the view, no problem.

### Expected behavior

When using warp in non-full screen mode, it is not user friendly to have the app show up in any view.

### Screenshots

https://github.com/warpdotdev/Warp/assets/73284586/5a766ca9-d3c6-4805-bbf8-cff87409b6a8

### Operating system

MacOS

### Operating system and version

13.5.1

### Shell Version

3.2.57

### Current Warp version

v0.2023.12.05.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @tanobe Thanks for letting us know. I was only able to replicate this with the [Global Hotkey Dedicated window](https://docs.warp.dev/features/windows/hotkey-window#dedicated-window) enabled in Settings. What are your settings for that feature? Are you using the dedicated window or just a regular Warp window (not the global hotkey one)?

Please see my reproduction with the global hotkey dedicated window enabled ( this may not be a bug since the window should be persistent and above other windows ).

https://github.com/warpdotdev/Warp/assets/16809145/cd7e5f0f-25f1-4d13-b511-82501bcf2a38

**Comment by tanobe** [comment]
Sorry for the late reply. Thank you for your kind attention!
I tried your advice and others, but it seems that besides Warp's hotkey settings, it also had something to do with where the mac apps are assigned to the desktop. In other words, this issue was not a bug in Warp. I will close the issue as it was successfully resolved.
