### ISSUE TITLE
DUP: Duplicate of #096 - Broken handling of PS1 with

### ISSUE THREAD

**Issue by cam-narzt** [warpdotdev/warp#396]
### Describe the bug

```shell
I'm seeing a weird double prompt.


~                       # <-- not my prompt, probably added by warp?
camdennarzt@SECUR-T:~ $ # <-- my prompt, which warp is interpreting as a command, and i need to delete before I type a command
```
```


### To Reproduce

I'm guessing it's due to my use of https://github.com/magicmonty/bash-git-prompt for my prompt?

My dotfiles are here: https://github.com/CamJN/dot-files

### Expected behaviour

```shell
Just my prompt, and have it be an actual prompt, not part of the next command.
```

### Operating System

MacOS

### OS Version

11.6.1

### Additional context

```shell
There are other issues during the startup of my bash profile that don't happen in Terminal.app that might be contributing to this problem. But they're different enough that I'm going to file them as other bugs.
```

**Comment by elviskahoro** [comment]
Changing title so that it's linked for us internally as related to custom prompts!
Linking:
- #96

**Comment by elviskahoro** [comment]
Thanks for submitting the issue, you hit it straight on the head! It's probably bash-git-prompt (I was using this too before warp), we're not compatible at the moment because Warp renders the prompt natively. We're working on making the prompt customizable though (see #96). Meanwhile you can disable the the conflicting settings by making this change in your zshrc file:
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K
    # OH-MY-ZSH-THEMES
    # OH-MY-ZSH-PLUGINS

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

**Comment by cam-narzt** [comment]
I don't use zsh, however that syntax should also work in bash. Is there a list of bash features that Warp breaks, that I could use to disable those parts of my bash scripts?

**Comment by cam-narzt** [comment]
Also out of curiosity how does warp deal with programs that emulate a terminal and thus draw a prompt such as emacs' eshell or gnu screen?

**Comment by elviskahoro** [comment]
We'll just keep this discussion in custom prompts.
