### ISSUE TITLE
Copy on select not working while viewing `git diff`

### ISSUE THREAD

**Issue by Cmarl** [warpdotdev/Warp#3964]
### Describe the bug

"Copy on Select" is enabled in preferences, but when I select text while looking at `git diff` it doesn't copy it.

### To reproduce

1) turn on "Copy on Select"
2) Navigate to a git repo
3) Run `git diff`
4) Select some text
5) See that it is not copied
6) Wonder to yourself "what the heck, why isn't it copied?"

### Expected behavior

1) turn on "Copy on Select"
2) Navigate to a git repo
3) Run `git diff`
4) Select some text
5) See paste it somewhere, because selecting it copied it like you expected
6) Profit

### Operating system

MacOS

### Operating system and version

14.1.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.1.0)

### Current Warp version

v0.2023.12.05.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

not a blocked to me using, but it is annoying. thanks team, love the product

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Cmarl Sorry to hear about this issue. Please run `git config --get diff.tool` and let us know what the diff tool you are using. For example I'm using `difftastic`, and can't seem to reproduce the issue on my end. Also, if you can, provide a recording of the issue so that we can get a better idea of how to reproduce it. Hopefully, we can figure out what's going wrong and get you to the Profit.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by Cmarl** [comment]
no git diff tool per the config command


https://github.com/warpdotdev/Warp/assets/9871619/c524241a-1041-4226-baf0-821b3afd3aa2

**Comment by dannyneira** [comment]
@Cmarl We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/2758 and would appreciate it if you could 👍 and comment there for updates on the issue.

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/2758

**Comment by Cmarl** [comment]
Working now, thanks team
