### ISSUE TITLE
Global Hotkey not working when IME is enabled

### ISSUE THREAD

**Issue by wizcas** [warpdotdev/Warp#4021]
### Discord username (optional)

Wizcas Chen#4501

### Describe the bug

When an IME other than ABC is enabled, the global hotkey won't work for calling out the quake window or the global window. 

### To reproduce

1. Launch warp and set the global hotkey for any mode other than `disabled`
2. Select an IME other than ABC
<img width="261" alt="image" src="https://github.com/warpdotdev/Warp/assets/2867434/bffd0c1b-c391-445e-977d-ced1b35fb3d8">

3. Hit the hotkey to summon the window

### Expected behavior

The warp window should show up

### Screenshots

N/A

### Operating system

MacOS

### Operating system and version

13.6.3

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.12.19.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @wizcas Sorry about this blocker. Since other input sources, register different keypresses they may not work with sources other than ABC. We're tracking this issue over at #341  and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by wizcas** [comment]
@dannyneira Got it. thank you for the feedback! I'm closing this one.
