### ISSUE TITLE
Change the Bug Template: No code blocks for normal text 

### ISSUE THREAD

**Issue by muescha** [warpdotdev/Warp#4044]
### Describe the solution you'd like?

```Text
Because of the template all text is written as code.

On line line I need always scroll the long way to read long paragraphs

Don't enclose the text with the code block markup. I think the users know when to use code markers on Github ;)
```

### Is your feature request related to a problem? Please describe.

```Text
Frustrated when I reed Issues
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hey @muescha Thanks for letting us know. I [removed the textarea render settings](https://github.com/warpdotdev/Warp/commit/79aa03eea5c231a361f69878c8d4a0ca6af9ddb7) from the feature request template so that it will render normally and respect markdown for code blocks in the future.

Closing as resolved, but please feel free to let us know if any issues with the new template changes.

**Comment by muescha** [comment]
thx :)
