### ISSUE TITLE
"set -o vi" appears to have no effect

### ISSUE THREAD

**Issue by dexhorthy** [warpdotdev/Warp#4085]
### Describe the solution you'd like?

I'd like to use vim keybindings for shell navigation, for example, ESC+j,k to scroll up/down through command history

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hey @dexhorthy Thanks for submitting this. Since Warp has built a wrapper around the shell, the shell-based vi modes didn't work so we've built our own you can enable in the input editor. We've been able to not only match but beat the vi mode capabilities that are available in bash and zsh. To manually toggle Vim keybindings in Warp's input editor, open the Command Palette with `CMD-P` and type "Vim Keybindings". This setting is also available in the Settings modal, under `Features → Editor → Edit commands with Vim keybindings`.

You can learn more about this in our docs. https://docs.warp.dev/features/editor/vim

Closing as complete since this feature already exists in Warp, just isn't enabled by `set -o vi`.

**Comment by dexhorthy** [comment]
incredible 🤦 I searched existing issues but here's my daily reminder to RTFM 😂
