### ISSUE TITLE
Camera and Microphone permission

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#413]
### Describe the solution you'd like?

```shell
"The problem is they put into the list only apps that have asked for the access, you cannot add apps manually like in "screen recording" for example. I need it because I start an app that needs camera from terminal. iTems is there, but I cannot force Warp to appear there as well. It's a known Apple issue: https://discussions.apple.com/thread/251105857"

From Discord #help - 11.05.2021
I was woundering, would it be possible to make warp forward the mic/camera request the same way iTerm does it? Or just have the app note the permission to os always, no harm I think being able to grant it when needed.
```

**Comment by AroundKevin** [comment]
👍🏽  Adding a +1 on this request. I have a workflow that requires launching a video conferencing app via terminal. Normally, the terminal app requests mic and camera permissions so that the VOIP app can work. This is completely non-functional with Warp and thus the VOIP app doesn't work.

Will have to move back to iTerm for now.

Machine: M1 Max
OS: Monterey / OSX 12.0.1

**Comment by pavelserbajlo** [comment]
also bumping this, our team is hitting the exact same issue with Warp with no known workaround.

**Comment by elviskahoro** [comment]
![image](https://user-images.githubusercontent.com/29553206/150631115-1bc9678d-22e6-44e8-91b1-5b4e32b5d756.png)

**Comment by mdigruber** [comment]
Can confirm. I need camera permission for python/opencv and have to use the default terminal, since the camera won't open in Warp.

**Comment by dlmanning** [comment]
Same. I need av permissions because I use an ncurses app to capture live ascii art from my camera.

**Comment by kevinyang372** [comment]
This issue will be fixed in the next release!
