### ISSUE TITLE
Warp on Fedora does not update

### ISSUE THREAD

**Issue by mattboston** [warpdotdev/Warp#4192]
### Describe the bug

I'm using FC39 with Warp v0.2024.02.14.15.46.stable_00.  In the top right I get the "Update Warp" notification.  When I click it, it autopopulates the following command, but when I run it, no update is applied but Warp does restart.  It then still says that there is an update available and checking the Settings -> About it still says I'm on the same version. Doing any other dnf update/upgrade command works for both Fedora and 3rd party repos.

`sudo dnf --refresh --repo warpdotdev upgrade warp && warp_finish_update {random_code}`

### To reproduce

1. Click Update Warp in top right
2. Hit Enter to start command
3. App restarts but is not updated

### Operating system

MacOS

### Operating system and version

14.2.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.02.14.15.46.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

N/A

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey all!  Due to feedback from the community, we've decided to change the name of our `apt/rpm/pacman` packages from `warp` to `warp-terminal`.  Alongside this change, we're updating the name of our config and data directories to warp-terminal to match.

For all users: we recommend moving or copying your config folders to the new location, as the just-released app update will look for files in the new paths.  Specifically:
```
mv ~/.config/warp ~/.config/warp-terminal
mv ~/.local/state/warp ~/.local/state/warp-terminal
mv ~/.local/share/warp ~/.local/share/warp-terminal
```

If you've installed one of the non-AppImage packages, run one of the below commands (as appropriate for your system):
```
sudo apt remove warp && sudo apt update && sudo apt install warp-terminal
sudo dnf remove warp && sudo dnf --refresh install warp-terminal
sudo zypper remove warp && sudo zypper --refresh install warp-terminal
sudo pacman -R warp && sudo pacman -Sy warp-terminal
```

Sorry for the hassle, and thank you all so much for your valuable feedback throughout the private beta process!  We can't wait for the public launch on Thursday, Feb 22nd 2024! We couldn't have done it without you all. ❤️

**Comment by mattboston** [comment]
Excellent.  Worked perfectly.  Looking forward to the launch
