### ISSUE TITLE
Give hotkey terminal window a unique window class

### ISSUE THREAD

**Issue by LiteracyFanatic** [warpdotdev/Warp#4254]
### Describe the solution you'd like?

The hotkey/quake terminal window should have a different window class or some other way to tell it apart from regular terminal windows. More specifically, since `WM_CLASS(STRING)` is made up of two parts (an instance and a class), the class should be the same for all windows since they are part of the same application and just the instance name could be changed to indicate the special status of the hotkey window. Perhaps something like `WM_CLASS(STRING) = "dev.warp.Hotkey", "dev.warp.Warp"`.

### Is your feature request related to a problem? Please describe.

I use i3 as my window manager and I would like normal warp windows to tile while the hotkey/quake terminal should float. Currently there is no way to tell from the `xprop` output which window is the special hotkey window as they all have the same class `dev.warp.Warp` so I can't configure them to behave differently in my i3 config.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for this feature request @LiteracyFanatic! We're working on improved integration with window manager workflows in Warp which should help with this request.

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by acarl005** [comment]
Hi @LiteracyFanatic. Thanks for pointing this out. I'll look into it.

**Comment by acarl005** [comment]
To update this issue, the latest version of Warp will give the dedicated hotkey window a distinct window instance name. Furthermore, in next week's release (assuming all goes as planned) the dedicated hotkey window will have a different [_NET_WM_WINDOW_TYPE](https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html#:~:text=on%20all%20windows.-,_NET_WM_WINDOW_TYPE,-_NET_WM_WINDOW_TYPE%2C%20ATOM%5B%5D/32) so that it should float by default

**Comment by LiteracyFanatic** [comment]
Excellent, thank you!
