### ISSUE TITLE
Warp for Linux won't update

### ISSUE THREAD

**Issue by avrame** [warpdotdev/Warp#4404]
### Describe the bug

This is the update link I am clicking on:
![Screenshot from 2024-02-28 22-16-34](https://github.com/warpdotdev/Warp/assets/101489/31acf803-5fff-489f-9721-2affb0c1a595)

When I click the "Update Warp" link it inserts in this command:
`sudo apt update && sudo apt install warp && warp_finish_update aIkKOtQ`
It runs and restarts Warp, but I still see the "Update Warp" link in the title bar with the same version to upgrade to. When I just try typing in `sudo apt install warp` apt tells me this: `warp is already the newest version (0.2024.02.14.15.46.stable.00).`
So I guess apt doesn't know about the newer version.

### To reproduce

1. Click on the "Update Warp" link.
2. Press enter to run the inserted command
3. Warp restarts but still shows the same update link

### Operating system

Linux

### Operating system and version

Zorin OS 17 Pro (based on Ubuntu)

### Shell Version

bash 5.1.16(1)-release

### Current Warp version

v0.2024.02.14.15.46.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I'm using X11

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hey @avrame we changed the name of our package before launch to avoid conflicts with other packages named `warp`. The new name of the package is `warp-terminal`.

We recommend moving or copying your config folders to the new location, as the just-released app update will look for files in the new paths.  Specifically:
`mv ~/.config/warp ~/.config/warp-terminal`
`mv ~/.local/state/warp ~/.local/state/warp-terminal`
`mv ~/.local/share/warp ~/.local/share/warp-terminal`

Since you installed via `apt`, I'd also recommend running command below
`sudo apt remove warp && sudo apt update && sudo apt install warp-terminal`

Sorry for the hassle, and thank you all so much for your valuable feedback throughout the private beta process!

**Comment by alokedesai** [comment]
Closing this out. Please reopen if you are still experiencing issues!
