### ISSUE TITLE
Aliasing 'open' causes warp to hang

### ISSUE THREAD

**Issue by twleung** [warpdotdev/Warp#449]
### Describe the bug

```shell
I have an alias to yoink in my Zsh config
```

### To Reproduce

include 

alias yoink=“open -a Yoink”

in a .zshrc file.

Start Warp, warp will hang.

replacing the alias with a function seems to work

function yoink() {
  open -a Yoink $1
}

### Expected behaviour

```shell
I expect warp not to hang.
```

### Operating System

MacOS

### OS Version

12.0.1

### Additional context

```shell
zsh 5.8 via homebrew
```

**Comment by gagata** [comment]
hey @twleung it's been a while! we landed a fix to the hanging issue some time ago, actually!

the underlying issue was that the quotation mark you used `”` is actually a unicode character that underneath included a byte that would break Warp's bootstrapping...

it should be fixed now, and Warp should not crash / hang, but let me know if you experience any more issues.
