### ISSUE TITLE
Linux Workaround Tracker

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#4513]
### How does this workaround tracker work?
This tracker is meant to help us understand the most common issues and workarounds that fixed them so we can improve Warp for Linux.

We have a list of workarounds to common issues running Warp on Linux in our docs [here](https://docs.warp.dev/help/known-issues#warp-window-not-showing).

If any of the workarounds help, please comment on https://github.com/warpdotdev/Warp/issues/4513 with your Linux distro, installation (WSL, Baremetal or VM, x86 or ARM), the issue you had, the workaround that fixed it, and any other workarounds are not on the list.

**Comment by krazykelv** [comment]
I experienced the Warp window not showing, running Baremetal Linux Mint.  Tried updating drivers to no avail, but then was fixed with the Low Power GPU option.

**Comment by rezarajan** [comment]
### Specs
OS: Fedora Linux 39 (Workstation Edition)
Display Protocol: Wayland
Arch: x86_64 (baremetal)

### Issue
When _fractional scaling_ is enabled in Wayland, the warp terminal will display blurry. This is fixed by setting the `WARP_ENABLE_WAYLAND=1` variable and then launching warp in the terminal via `warp-terminal` (see [workarounds](https://docs.warp.dev/help/known-issues#linux-workarounds)). However, when launching via the **desktop application shortcut** this variable will not be set, and the application will launch blurry.

### Resolution
To fix the issue, we must ensure the desktop entry file sets the variable to launch warp with Wayland support. It can be done as follows:
1. Modify the existing desktop entry, or create a new file with a text editor. In this example the original entry will be modified.
```sh
# File ends with .desktop
sudo vi /usr/share/applications/dev.warp.Warp.desktop
```
2. In the `Exec` field, add the required environment variable, as follows
```yaml
[Desktop Entry]
# The version of the desktop entry spec this conforms to.
Version=1.0

Type=Application

Name=Warp
GenericName=TerminalEmulator

# Ensure wayland variable is set before launching warp
Exec=env WARP_ENABLE_WAYLAND=1 warp-terminal %U
StartupWMClass=dev.warp.Warp

Keywords=shell;prompt;command;commandline;cmd;

Icon=dev.warp.Warp

Categories=System;TerminalEmulator;

# Don't run this application within a terminal.
Terminal=false

# Register ourselves as the handler for warp:// URLs.
MimeType=x-scheme-handler/warp;

```

Notice the `Exec` field contains the environment variable to enable Wayland. If creating your own file, a minimal configuration would be

```yaml
# Create a file /usr/share/applications/warp-terminal.desktop
[Desktop Entry]
Name=Warp Terminal

# Enable Wayland support
Exec=env WARP_ENABLE_WAYLAND=1 /usr/bin/warp-terminal
Terminal=false
Type=Application
```

**Comment by Rhinogradentia** [comment]
Ubuntu 22.04 vi wsl2 on Windows11


SignIn opened a Web-Login Page where I could login, but this wasn't propagated to the Warp-Window running on WSL2.
Used the link for the Auth Token displayed on the  SignIn Page, copied it and pasted it into the AuthToken text field in the Warp Window. 

This worked fine but wasn't very obvious immediately. So maybe explain this option somewhere in the FAQs

**Comment by dannyneira** [comment]
Thanks @Rhinogradentia , this was noted in the Troubleshooting login page. https://docs.warp.dev/help/troubleshooting-login-issues#how-to-get-an-auth-token-to-login, we'll work on getting this added to the www.warp.dev/faq page as well.

**Comment by dannyneira** [comment]
closing, we'll continue tracking any issues or workarounds on the thread for WSL support. https://github.com/warpdotdev/Warp/issues/4240
