### ISSUE TITLE
Invalid input: export when connecting to a switch

### ISSUE THREAD

**Issue by fre4ki** [warpdotdev/Warp#4665]
### Operating System

MacOS

### Operating System and Version

14.4.1

### Local Shell Version

5.9

### Remote Shell Version

-

### Warp Version

v0.2024.03.26.08.02.stable_02

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

Hey guys,

i'm trying warp for my future use but i get an error when connecting to a ArubaCX Switch (in my example it is a virtual switch).

The base system is linux but they have no native linux commands.

I was reading somewhere that warp executing commands in the background after connecting, how can i disable this?

When i connect to my switch and enter the credentials i get an disconnect

<img width="663" alt="image" src="https://github.com/warpdotdev/Warp/assets/62788741/de29bff6-dc3f-4a84-8e8f-6b961b76cec3">

### Include shell xtrace output

-

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @fre4ki , it may be possible, even if the switch has `bash`/`zsh` as the default shell, if it doesn't have the necessary commands it will fail to bootstrap Warps SSH Wrapper. As a workaround, you can try using adding `command ssh` to your Settings > Subshell menu, then use `command ssh <user@server>` to connect to sessions, this will enable Warp features with the subshell method instead of the ssh wrapper.

Or, you can also try disabling the SSH wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH to the switch should work as normal.

https://docs.warp.dev/features/ssh
https://docs.warp.dev/features/subshells
