### ISSUE TITLE
Expansion of pane only works if a block is selected

### ISSUE THREAD

**Issue by jpninanjohn** [warpdotdev/Warp#4748]
### Describe the bug

Suppose I have 4 panes open. I am in the 4th pane and if i try to expand it to full screen it does not work. I have to select a block in the 4th pane and only then does it expand 

### To reproduce
[Screencast from 2024-04-13 12-22-31.webm](https://github.com/warpdotdev/Warp/assets/11459946/7a749f5a-1396-43b8-ae56-c886d8a53791)

### Operating system

Linux

### Operating system and version

OS: Fedora Linux 39 (Workstation Edition) x86_64

### Shell Version

bash --version GNU bash, version 5.2.26(1)-release (x86_64-redhat-linux-gnu)

### Current Warp version

v0.2024.04.02.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @jpninanjohn thanks for submitting this. Please search the Keyboard Shortcut menu for "alt enter" and see if any other keybinds conflict with that keybind. If so, you will have to change one so they don't conflict. Also I believe ALT-ENTER defaults to adding a new line and since some Warp shortcuts are contextually based, if your focus is on the input it will add a new line, but if the focus is on blocks, it will maximize the pane if that make sense. So you may want to add a SHIFT-ALT-ENTER to maximize the pane (or some other shortcut with no conflict). Hope this helps!
