### ISSUE TITLE
The ability to screenshot to a file or clipboard a Block.

### ISSUE THREAD

**Issue by mdurao** [warpdotdev/Warp#4759]
### Describe the solution you'd like?

Having a keybind or a block menu option to screenshot the current selected block to a file or to clipboard.
Would be nice to share with other people.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @mdurao Thanks for submitting. There are two features which may meet your use case. 

1. Block sharing allows you to share a selected block with others. This is better than screenshots because the text of a shared block is select/copyable. https://docs.warp.dev/features/blocks/block-sharing
2. Instead of clipboarding a block, you can Bookmark it for later use. https://docs.warp.dev/features/blocks/block-actions#bookmarking-a-block

hope these help!

**Comment by dannyneira** [comment]
If its okay with you, i'll close as a feature already exists for this use case. If any issues with the block sharing or bookmarks, please let us know.

**Comment by wpostma** [comment]
Am i understanding that block sharing takes the place of just flat copy of text? This is not friendly to users as what we want is not the ability to create a social media site to share blocks with others.  What we (or at least I) want is the same text copy features that we rely on since windows 3.0 days to copy from one program and paste in another, whether it's notepad, or our internal wikis.
