### ISSUE TITLE
Breaking the characters

### ISSUE THREAD

**Issue by JUKI-J** [warpdotdev/Warp#4819]
### Describe the bug

There is an error that breaks the directory or file name stored in Korean.
For example, the actual filename is "안녕.txt", there is an error on the screen that appears as " ㅇㄴ.txt".

<img width="1052" alt="image" src="https://github.com/warpdotdev/Warp/assets/24859462/b577280c-3b40-42aa-a6fd-fce15d4cc0b5">

### To reproduce

Same as above

### Operating system

MacOS

### Operating system and version

Sonoma 14.4.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @JUKI-J, I don't know of any workaround at this moment, maybe try another font may help? We'll post any updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by NunciosChums** [comment]
If I switch to the system default, Apple SD Gothic Neo, the symptoms are the same. Korean breaking has been an issue since the early days of Warp. Other languages also lose their accent markings, but all are visible in Terminal using the same font.


finder
![screenshot 2024-04-26 오전 10 06 17](https://github.com/warpdotdev/Warp/assets/1233318/49d42289-4400-4e77-90bd-ce6bcd88a0a5)

Warp
![screenshot 2024-04-26 오전 10 06 11](https://github.com/warpdotdev/Warp/assets/1233318/2686d732-5bd2-4530-9ad6-79110298f425)

Terminal
![screenshot 2024-04-26 오전 10 08 00](https://github.com/warpdotdev/Warp/assets/1233318/9ae0e106-57fd-4f02-bc7a-2fa73f7698b6)

**Comment by NunciosChums** [comment]
I think it's fixed, except for Arabic.

![screenshot 2024-06-10 오전 9 55 49](https://github.com/warpdotdev/Warp/assets/1233318/d0204f94-6dcb-4435-80fb-fd48724fd082)

**Comment by BSN4** [comment]
this is being fixed in PR #10809, before and after screenshots on the PR, tracking issue is #10355
