### ISSUE TITLE
Edit/Import/Convert themes within settings

### ISSUE THREAD

**Issue by nyteshade** [warpdotdev/Warp#4838]
### Describe the solution you'd like?

It would be ideal if iTerm2 or other shell themes could be imported. In any case, along the same lines, it would be ideal if themes could be edited. I created a theme from a picture (nice touch) but it didn't show me the 16 colors (normal and bright) nor did it allow me to adjust the opacity of the background image nor did it show me what `ls --colors=auto` or anything else might look like on top of the background image using those colors.

I had to do this very manually by hand in the file itself in the ~/.warp/themes/. Nor did it allow me to choose a name for my theme. 

All these would be a big step forward for showing how much more advanced the terminal is compared to others like iTerm

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for this feature request @nyteshade. As a possible stopgap to a built-in theme editor, you can try to use [Terminal-Themes](https://terminal-themes.com/) to create a custom theme and generate the appropriate RGB values for your custom theme. Once the YAML file is created, you can edit the file to add the background images or gradients.

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by shanebdavis** [comment]
This is turning out to be a big blocker to adoption for me. I'm still using iterm2 most the time mostly because I can't get the right colors in Warp. For example. I like the Dracula them pretty well, but I want the background color to be full black. There's no way to trace an existing theme and just correct one value as far as I can tell.

I'd prefer an in-app GUI for editing the theme. Or, since you are all in on AI, I could have a conversation with a bot to fine-tune the theme. But this "one-shot" theme AI is nearly useless to me. 

As a stop-gap, perhaps if there was a way to save an existing theme to ~/.warp/themes, then I could at least edit that file and update the values rather than having to start from scratch...
