### ISSUE TITLE
cdto warp

### ISSUE THREAD

**Issue by inspireyls** [warpdotdev/Warp#5048]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

cdto访达工具默认打开iterm2怎么默认打开warp？

### Is your feature request related to a problem? Please describe.

cdto warp

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
感谢您提交此信息 @inspireyls
您也可以在 Finder 中右键单击文件夹或文件，选择服务，然后“在此处打开新的 Warp 选项卡 | 窗口”。
请参阅我们的[文档了解更多信息](https://docs.warp.dev/features/files-and-links#files-and-links-1)。
希望对您有所帮助！由于此功能已存在，因此已解决，但如果有任何问题，请告知我们。

![CleanShot 2024-06-20 at 10 44 42](https://github.com/warpdotdev/Warp/assets/16809145/b8c3d331-1e2f-4aa6-be90-4ab8ab342313)

You can also right-click on a folder or file in Finder, select Services, and "Open new Warp Tab | Window here".
See our [documentation for more](https://docs.warp.dev/features/files-and-links#files-and-links-1).
I hope this helps! Closing as resolved since this feature already exists, but please let us know if any issues.
