### ISSUE TITLE
Clicking on terminal windows in same tab shouldn't move blocks up and down, it moves things around too much

### ISSUE THREAD

**Issue by ilyaGurevich** [warpdotdev/Warp#510]
### Describe the solution you'd like?

Don't move blocks around, just highlight the terminal you're working in like iterm2 to show you're working in it
![changingblocks](https://user-images.githubusercontent.com/19535560/145272157-69310155-32f0-49d8-b391-a1d86d622e9d.gif)

**Comment by elviskahoro** [comment]
We're gonna close this for now. The blocks move because the input editor was collapsed but opens when the new pane takes the focus. ATM it's a design decision.
CCing @zachlloyd

**Comment by rswerve** [comment]
Glad to see this reopened.  Layout shifting is a UI anti-pattern, and as @ilyaGurevich notes, iTerm's use of background color to show focus is better because it reduces layout shifting _and_ makes it easier to see at a glance which tab is in focus.

**Comment by ugrupp** [comment]
I'm also using panes a lot, and both the layout shift and the hidden prompt are a little irritating.
Especially when the prompt already has some content, that definitely shouldn't be hidden when switching the pane.

Perhaps make it configurable to hide the prompt?

(So far, it's literally the only thing that bugs me, everything else about Warp is fantastic!)

**Comment by rswerve** [comment]
> (So far, it's literally the only thing that bugs me, everything else about Warp is fantastic!)

Agreed.  I'm trying very hard to make Warp my daily driver, but the movement and the ever-so-slight difficulty of seeing which pane is active are challenges.

**Comment by rswerve** [comment]
I see that half of this was done, with the [release](https://github.com/warpdotdev/Warp/issues/304) of the dimmed inactive tabs.  🎉  Hoping that the shifting is up next, since that seems to be a [consistent annoyance](https://github.com/warpdotdev/Warp/issues/2436) for folks. 🙌

**Comment by kg-currenxie** [comment]
Same here. Would be great having the option to enable/disable this behavior in settings. Can't imagine a lot of effort? :) `if (settings.collapseWhenBlurred) { collapse() }` 😂

**Comment by simonst** [comment]
+1 for this, the only downside of warp as of right now - it does really distract when switching between split panes. Any chance to make this configurable?

**Comment by samv** [comment]
Yeah, I've been finding this behavior really irritating, and was looking for a config option but to no avail.  The current behavior I think is kind of broken. Making an input box change size, with non–local effects on the whole window because it is not focused is not how user interfaces work.  The one I'm typing in for instance, the Github Issues box.  If I press tab, a blue border around the text box moves to another location.  If I move to a user input with a flyout, that flyout flies _over_ the existing display, but it doesn't cause the whole window to move around.

The current behavior means that if you switch to a tab, run a command to look something up or get a result, and then switch back.  The information you got from the other tab moves right as you were looking at it.  It's jarring.

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, the input editor remains visible in inactive panes when using split panes. 

![CleanShot 2023-09-21 at 13 34 04](https://github.com/warpdotdev/Warp/assets/16809145/5b27a944-5add-4296-9166-1e502f70fab7)

Closing as completed, but please let us know if any issues.
