### ISSUE TITLE
ability to set one or both of option keys as alt key

### ISSUE THREAD

**Issue by NikosEfthias** [warpdotdev/Warp#512]
### Describe the solution you'd like?

```shell
Currently, its impossible to use the alt key when using many cli's however alt is vital.
Many terminals have an option to set one of the option keys as alt
```

**Comment by elviskahoro** [comment]
@NikosEfthias we have an option for this in the mac menu.
<img width="362" alt="Screen Shot 2022-01-16 at 9 06 18 PM" src="https://user-images.githubusercontent.com/29553206/149689690-ca715801-ff97-4c47-8b41-4b5e414c9959.png">

Reopen if this doesn't solve your use case.

**Comment by NikosEfthias** [comment]
Cool I Thought it would be in the settings

**Comment by NikosEfthias** [comment]
> @NikosEfthias Got it! Taking note. We'll try to improve our mac menu (add more items and select intuitive locations).

thanks for being so nice this is really not the case in many projects. When one comments to improve things members of certain projects take it the wrong way and start on the defensive. I really appreciate your attitude

**Comment by elviskahoro** [comment]
haha thanks! not a problem. 
https://twitter.com/warpdotdev/status/1484270674445156353​


Personally speaking (not representing Warp), I think Warp is a project that people across the whole open source spectrum can get behind since the terminal is so high in the funnel. Plus once there's a plugin and extension marketplace it'll become more of a platform.

--- original message ---
On January 22, 2022, 4:02 AM EST ***@***.*** wrote:



> @NikosEfthias Got it! Taking note. We'll try to improve our mac menu (add more items and select intuitive locations).


thanks for being so nice this is really not the case in many projects. When one comments to improve things members of certain projects take it the wrong way and start on the defensive. I really appreciate your attitude

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you modified the open/close state.Message ID: ***@***.***>
--- end of original message ---

**Comment by NikosEfthias** [comment]
> Personally speaking (not representing Warp), I think Warp is a project that people across the whole open source spectrum can get behind since the terminal is so high in the funnel. Plus once there's a plugin and extension marketplace it'll become more of a platform.

I used to use tmux for the extensibility and it has lots of shortcomings especially on mac for some reason.
Hyperterm tried to do what you mention but in my opinion failed due to wrong tech stack. I think warp can be something only issue so far is that its not open source

**Comment by elviskahoro** [comment]
The plan is to open source there's just a number of things that need to be figured out and built first. See here:

https://github.com/warpdotdev/Warp/discussions/400

**Comment by gavynriebau** [comment]
For anyone else looking for where the "Left/Right Option key is Meta" options are, in the latest version (0.2023.02.14.08.05.stable_01) it can be found using the top menu "Warp -> Preferences -> Settings" then the "Features" menu
