### ISSUE TITLE
Is there a way to open warp from my desktop via keyboard shortcut?

### ISSUE THREAD

**Issue by kurt-rhee** [warpdotdev/Warp#5226]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

In order to open my standard terminal i use control + alt + t on ubuntu.  I can map different command line functions to a keyboard shortcut but I am not sure what command would open warp from the terminal?

### Is your feature request related to a problem? Please describe.

Mapping to a keyboard shortcut would make opening warp faster for me.

### Additional context

![image](https://github.com/user-attachments/assets/7ad79025-4108-425f-976a-88d56734a364)

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @kurt-rhee Thanks for submitting this. You can set a custom keyboard shortcut in your Ubuntu Settings > Keyboard > View and Customize Shortcuts > Custom Shortcuts. Make sure to remove the existing "Launch Terminal" shortcut so that it doesn't conflict or set your new custom shortcut to something else. Please see my video for an example.

https://github.com/user-attachments/assets/75bd87fe-a1aa-4ca1-a044-7119a523e12c

I hope this helps! Closing as this feature already exists in Ubuntu.

**Comment by kurt-rhee** [comment]
Yes this is awesome thank you!

**Comment by Velkamhell97** [comment]
Does it work for Windows?

**Comment by alexzhaohong** [comment]
Ubuntu Settings > Keyboard > View and Customize Shortcuts > Custom Shortcuts `warp-terminal` creates a new terminal window.

If you want to persist a session, there is the Settings > Features > Keys > Global hotkey which gives a dedicated hotkey window. https://youtu.be/q_BVQcKBG8U?si=yt8jTex8U6cHz7Xt

Works in Ubuntu.
