### ISSUE TITLE
[Mac] Close button doesn't terminate process; page size anomaly on reopening

### ISSUE THREAD

**Issue by axliupore** [warpdotdev/Warp#5255]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When using the application on a Mac, clicking the close button (located at the top left corner of the window) does not terminate the application process as expected. Upon attempting to reopen the application, the window size appears abnormal, often bigger than the usual or intended size, which disrupts the user interface and usability. 

### To reproduce

1. Open Warp.
2. Click the close button at the top left corner.
3. Reopen Warp.
4. Observe that the page size becomes unusually large.

### Screenshots

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/80503282-da08-4fdd-846c-1e561ccac960">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/ca1c239d-bc37-4744-9d0c-ef693c16fc20">

### Operating system

MacOS

### Operating system and version

mac 14.6.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @axliupore sorry to hear about this. When you close Warp with the red button, it's still running in the background ready to open a new window so that's normal behavior. For the resize, I recommend you look into your Settings > Appearance > Window > [custom size to make sure that's disabled](https://docs.warp.dev/appearance/size-opacity-blurring). Also I recommend you check if [Session restoration is enabled](https://docs.warp.dev/features/sessions/session-restoration) as this will restore the previous size. Finally, please make sure you're not using any window manager like rectangle or something else that may override Warps window restoration/custom size features.

I hope this helps!

**Comment by axliupore** [comment]
> Hi @axliupore sorry to hear about this. When you close Warp with the red button, it's still running in the background ready to open a new window so that's normal behavior. For the resize, I recommend you look into your Settings > Appearance > Window > [custom size to make sure that's disabled](https://docs.warp.dev/appearance/size-opacity-blurring). Also I recommend you check if [Session restoration is enabled](https://docs.warp.dev/features/sessions/session-restoration) as this will restore the previous size. Finally, please make sure you're not using any window manager like rectangle or something else that may override Warps window restoration/custom size features.嗨，很抱歉听到这个情况。当你通过红色按钮关闭 Warp 时，它实际上仍在后台运行，随时准备打开新窗口，这是正常行为。关于窗口大小调整的问题，我建议你查看设置 > 外观 > 窗口 > 自定义大小，确保该选项已禁用。同时，建议检查会话恢复功能是否启用，因为这会恢复之前的窗口大小。最后，请确认你没有使用任何如 Rectangle 之类的窗口管理器，这些可能会覆盖 Warp 的窗口恢复/自定义大小功能。
> 
> I hope this helps!希望这能帮到你！

Thank you, I solved this problem with your method.
