### ISSUE TITLE
Add support for drop-down window

### ISSUE THREAD

**Issue by milanchanstveni** [warpdotdev/Warp#5265]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I would like to request a feature for Warp to have option to go from regular window-based application to drop-down application where it would go in background if it loses focus similar to [guake](https://github.com/Guake/guake) project

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @milanchanstveni We;ve got a feature called Global Hotkey Dedicated Window which is analogous to Quake Mode/Guake. Please learn more about this here. https://docs.warp.dev/features/windows/global-hotkey#dedicated-window

You can setup your own hotkey and the location of the window. Closing as resolved since the feature exists, but please feel free to let me know if any issues.
