### ISSUE TITLE
Auto focus prompt pane on widows focus

### ISSUE THREAD

**Issue by kilinkis** [warpdotdev/Warp#5419]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I'd like that after focusing on the Warp window, either by clicking it or using cmd+tab, 
the prompt panel auto focus.

### Is your feature request related to a problem? Please describe.

Now I need to click on the Warp window and then click again on the prompt area to be able to input commands.
I know that I could click the prompt area directly, but it is a very small target for the mouse so it needs a little more attention to do it.

### Additional context

I've been googling around for this and couldn't find a solution. I hope this feature doesn't exist and have a different name 😅

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @kilinkis There is a [new feature](https://github.com/warpdotdev/Warp/issues/699#issuecomment-2420112562) that may help here. Go to Settings > Appearance > Focus follows mouse. Toggle that on so that when you have multiple panes, the mouse will focus on whichever one is being hovered over. 

Also, note that to focus on the input area in any session (window, tab, or pane) you can either press CTRL-L or just start typing and the input will be in focus.

I've attached a demo of these in action and added the info to our Pane docs [here](https://docs.warp.dev/appearance/pane-dimming).

https://github.com/user-attachments/assets/7dfb4cf5-84f9-4b39-b576-4f71b4ed36bb

Please let me know if that helps with your request!

**Comment by dannyneira** [comment]
Closing as this feature exists, but please feel free to let me know if any issues with the feature.

**Comment by kilinkis** [comment]
oh that's very cool Danny! thanks for the video! also, I didn't know that I could simply start writing 🤦‍♂️ 

thanks again!
