### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by theVedanta** [warpdotdev/Warp#5635]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Neovim in warp has a problem with icon visibility. The icons are not visible in the nvimtree, the terminal ASCII icons, etc.

Here are the images:
<img width="413" alt="Screenshot 2024-12-28 at 9 20 27 PM" src="https://github.com/user-attachments/assets/92a3d48a-7b89-4f25-a0cf-df9f18d02032" />

And this is how it should've been:
<img width="380" alt="Screenshot 2024-12-28 at 9 20 39 PM" src="https://github.com/user-attachments/assets/5edf38a2-3679-4e00-8888-d64d468b83ca" />

### To reproduce

I'm using p10k and oh-my-zsh when it comes to the config. The neovim config is nothing special and does not contain the icons issue because warp by default shows no icons in the standard terminal commands.

### Expected behavior

<img width="79" alt="Screenshot 2024-12-28 at 9 22 51 PM" src="https://github.com/user-attachments/assets/d4993a7b-1238-4a17-9f82-e515cf9d96de" />

BUT INSTEAD:
<img width="40" alt="Screenshot 2024-12-28 at 9 23 12 PM" src="https://github.com/user-attachments/assets/06de9a41-9d70-4d51-bf07-3ab8a3420041" />

Same with neovim:

<img width="103" alt="Screenshot 2024-12-28 at 9 23 30 PM" src="https://github.com/user-attachments/assets/ac56884f-21fb-4bba-b3ad-724651aa05a8" />
<img width="78" alt="Screenshot 2024-12-28 at 9 23 49 PM" src="https://github.com/user-attachments/assets/a6ee6389-9a25-4678-8a83-7524883aa3d4" />

### Screenshots

Already added above

### Operating system

MacOS

### Operating system and version

Sequoia

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
@theVedanta thanks for submitting. This may be due to the fonts that you're using. By default Warp uses Hack Font, but not the Nerd font variant which contains many more icons. I recommend you try a Nerd font which does contain the icons and see if the issue persists. https://www.nerdfonts.com/

You may need to restart Warp after installing the font and check "View all available system fonts" in `Settings> Appearance > Text` to see the new fonts in the dropdown list. https://docs.warp.dev/appearance/text-fonts-cursor#text-and-fonts

Examples below:
Hack (Default)
![CleanShot 2024-12-30 at 11 01 53](https://github.com/user-attachments/assets/4eca4eec-beba-4d64-a75c-872e855133a7)
Hack Nerd Font
![CleanShot 2024-12-30 at 11 00 48](https://github.com/user-attachments/assets/dc856f5e-790b-4147-96ca-3d2c9781e3e9)

Please let me know if that helps with your icon issue.

**Comment by theVedanta** [comment]
This did help @dannyneira, Thank you.
It would be great if Warp ships with the standard Hack Nerd Mono font. Most of the terminals I have tried never faced the issue with nerd fonts so it would be great if it shipped with the Hack Nerd.

**Comment by dannyneira** [comment]
Thats not a bad idea, I forget the reason why we haven't done so in the past, but we typically like to give folks the lighter font to keep the binary sizes smaller, especially for the Web version of Warp. 

I'll close this as resolved since you're issue was the font, but will let the team know your feedback about the default fonts we ship with.
