### ISSUE TITLE
Differentiate between stdout and stderr

### ISSUE THREAD

**Issue by Alexndrrr** [warpdotdev/Warp#650]
### Describe the solution you'd like?

I'd like to be able to visually differentiate between stdout and stderr.

One option would be to render stderr as bold red, like the Pycharm console does (see screenshot) But this might cause conflicts with ANSI formatting.

Another option would be to have some red colored bar on the side to indicate stderr text.

### Additional context

Example from Pycharm console:
![image](https://user-images.githubusercontent.com/33378879/150398461-9b2b2b23-6e2a-4071-a08b-df3ba16c2f12.png)

**Comment by elviskahoro** [comment]
@Alexndrrr That's being talked about here:
- https://github.com/warpdotdev/Warp/discussions/632

Can you move this to there?

**Comment by Alexndrrr** [comment]
Thank you @elviskahoro ! I searched and couldn't find anything already for this, clearly I have more learning to do!

**Comment by elviskahoro** [comment]
@Alexndrrr It's in github discussions not github issues which is why! We're trying to proactively move the bigger ideas there because GitHub discussions supports threads. Also so we can send links like this:

[Roadmap](https://github.com/warpdotdev/Warp/discussions?discussions_q=label%3ARoadmap+sort%3Atop)
