### ISSUE TITLE
Prompt removes character instead of autocompletion on pressing Tab

### ISSUE THREAD

**Issue by meredian** [warpdotdev/Warp#695]
### Describe the bug

Tried to autocomplete some absolute paths and that resulted in removing entered string instead of autocompletion.

E.g. Autocompleting `cd /us` results in `cd /`, not `cd /usr` (command is not essential, but path is). That works for some other letters like `cd /v` & `cd /s`. _Maybe_ root cause is those characters actually trigger autocompletion, since there are folders starting with both paths (`/Users` and `/usr` for `/us`, `/System` & `/sbin` for `/s` and `/Volumes` & `/var` for `/v`). If you try `/va` for `/var`, it already behaves normally.

### To Reproduce

Write root path: `cd /us` & press `[tab]`. That results is `us` part being deleted & prompt looks like `cd /`

### Expected behaviour

```shell
On pressing `[tab]` path `cd /us` is completed til `cd /usr/`
```

### Operating System

MacOS

### OS Version

11.6.2

### Additional context

```shell
Version: v0.2022.01.24.08.55.stable_02
```

**Comment by elviskahoro** [comment]
From @mandel-macaque via #673

### Describe the bug

```shell
When working and trying to do a simple command like `code filename.cs` if the directory contains a lot of files there is a large lag. When you try to use tab the cursor goes back to the end of the directory name and removes all the chars already typed. It is better shown in the attached video.

The file count is 354, which is not that many:

ls src | wc -l    
     354
```


### To Reproduce

Steps to reproduce:
1. Find a directory with a large number of files. In the video I'm suing the src directory in GitHub.com/xamarin/xamarin-macios
2. Try to execute a command using one of the files in the directory and use tab to autocomplete.
3. Tab does not complete and deletes what was already typed.


### Expected behaviour

```shell
Tab completion works.
```


### Screenshots



https://user-images.githubusercontent.com/2190086/151050769-4a8b15d1-944e-4e76-8af2-99c205926952.mov





### Operating System

MacOS

### OS Version

12.1

### Additional context

_No response_

**Comment by elviskahoro** [comment]
@mandel-macaque is this still happening?
I think we fixed (i can't reproduce it anymore on my machine) but just wanted to check with you. Please comment if it's still bugged!
