### ISSUE TITLE
Fig Support

### ISSUE THREAD

**Issue by aw-0** [warpdotdev/Warp#704]
### Describe the solution you'd like?

```shell
One of my favorite terminal tools is https://fig.io/. It allows for incredibly complex autocomplete for tons of terminal commands (ranging from system commands to CLIs like yarn, npm, & gcloud). It would be great if Warp could reach out to the team @ Fig and possibly get an integration in the works.
```

### Is your feature request related to a problem? Please describe.

```shell
Fig increases my UX of any terminal 10-fold, and I'm sure others as well. It's easy to use arrow keys to navigate Fig's suggestions, along with its dynamic autocomplete as well (e.x. while running `npm i [packag_namee]`, it'll auto-suggest possible packages for you to install).
```

**Comment by elviskahoro** [comment]
@aw-0 
Fig is an awesome project, kudos to them for building something that dramatically improves developer experience. https://github.com/warpdotdev/Warp#open-source-dependencies

In terms of the completions themselves, we actually implemented their specs (Dec 2021) into Warp (we had to generate a Rust equivalent). More contributions and dev tools have likely been added since then but we plan on creating our own open source spec (in Rust).
https://docs.warp.dev/help/changelog

When it comes to the actual command entry experience, we definitely have lots of room to grow and are looking forward to improving it over the next few months. See here:
- https://github.com/warpdotdev/Warp/milestone/3

You're specific suggestion of being able to navigate through completions using the arrow keys is here:
- #192
