### ISSUE TITLE
Better full screen support / toggle full-screen

### ISSUE THREAD

**Issue by adamgotterer** [warpdotdev/Warp#710]
### Describe the solution you'd like?

```shell
In iTerm2 I hit cmd-enter to toggle in and out of full screen mode. The problem with fullscreen mode in Warp is that its using the native MacOs full screen mode which on multiple monitors goes into focus mode and hides windows on the other monitors. iTerm seems to have implemented their own full screen functionality to prevent this.
```

**Comment by ild0tt0re** [comment]
I have the same use case... I'm used to dividing the terminal into multiple panels and quickly expanding one of them based on the output of different commands.
This is one of the features that is not letting me fully enjoy Warp

**Comment by xhyumiracle** [comment]
speaking of cmd-enter, it would be great if warp can all 'full screen' keyboard shortcut, so that we can customize it to e.g.'cmd-enter'.

**Comment by roydigerhund** [comment]
> I'm used to dividing the terminal into multiple panels and quickly expanding one of them based on the output of different commands:

Yes, also what I use often in iTerm and I really miss this in Warp.

**Comment by elviskahoro** [comment]
We have a mac menu item for Zoom under Window. We can use Mac's keyboard shortcut manager to do this:
https://www.loom.com/share/3746ff9303fe43228d005e99393ad974

**Comment by elviskahoro** [comment]
We support maximing panes as well! Via right click or keybinding

**Comment by nicksergeant** [comment]
@elviskahoro I think one of the original asks in this issue is not just for a keyboard shortcut but to support non-native full-screen in macOS. Currently Warp only supports "native" full-screen mode where full-screening the app makes it appear in a macOS "Space".

The downside to doing full-screen in spaces is the animation delay when going from full-screen to non-full-screen, and the animation delay just switching from one full-screen app to another (since they are different spaces).
