### ISSUE TITLE
Previous command in SSH session

### ISSUE THREAD

**Issue by jijefj** [warpdotdev/Warp#822]
### Describe the bug

```text
When I login via SSH to server, I cant see previous executed commands in server via arrow UP key. When I press arrow UP, terminal highlights block above
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```text
When you press arrow UP key in SSH session, it must show previous executed command on server
```

### Operating System

MacOS

**Comment by jijefj** [comment]
Hey @vorporeal, so i opened terminal and ssh session to capture the gif and it works. I have tried in many ways but works. Was there some update during these 2 days?

**Comment by vorporeal** [comment]
No, we haven't pushed out a new version since you filed the bug.  I'm guessing it's an uncommon/hard to repro issue where the input field gets into a bad state?

Given that it's not a consistent issue, mind if we close this issue, and you can reopen with a screenshot and/or repro steps if it happens again?

**Comment by jijefj** [comment]
Ok. If it happens again, I will reopen issue
