### ISSUE TITLE
Would be helpful to have option to add custom keybindings for navigating command history

### ISSUE THREAD

**Issue by taranlu-houzz** [warpdotdev/Warp#851]
### Describe the solution you'd like?

```text
It would be great to have the following:
- Keybindings for "move selection up/down" for command history (and any other vertical popup menus as well).
- A toggle to disable `warp`'s builtin history search so that an external tool, such as `fzf` can be used instead.
```

### Additional context

Currently, I use `fzf` for fuzzy command history searching. The keybindings for that are `ctrl+j` and `ctrl+k` to move up and down, which is very ergonomic for `vim` users.

**Comment by elviskahoro** [comment]
Hey @taranlu-houzz it's pretty standard to use CTRL-N and CTRL-P. Which are originally from emacs. Lots of mac apps have native support for this e.g. Google chrome. Warp's built in history search supports fuzzy searching as well. I'll ask the team for their thoughts on this but my personal opinion is that once you get used to CTRL-N and CTRL-P you'll appreciate it, since it's so common.

I started using them like 6 weeks ago and I'm also a Vim user.

**Comment by taranlu-houzz** [comment]
Hey @elviskahoro, looking through the docs I also saw that. Fair enough, I will probably get used to it over time if I use `warp` more. Would still be nice to have. Thanks for the quick reply!
