### ISSUE TITLE
Core: Stuck at starting ZSH

### ISSUE THREAD

**Issue by ikusa** [warpdotdev/warp#86]
**Describe the bug**
Warp editor at the bottom of the screen stuck at the starting zsh and the results block became normal terminal instead

**To Reproduce**
1. open warp terminal

**Expected behavior**
the starting zsh finish and the results block are not editable / work like normal terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/18739325/127808576-e82aaaaf-5b84-45fb-8b00-6e01bbd4e33f.png)

**Desktop (please complete the following information):**
MacOS 11.4

**Comment by zheng** [comment]
It looks like you have powerlevel10k installed. It interferes with warp bootstrapping. We do want to either support it or add UI to warn users, but in the meantime, you could comment it out in your `.zshrc`, `.zprofile`, `.zlogin` to use warp.

**Comment by yehudamakarov** [comment]
@zheng 
> you could comment it out in your `.zshrc`, `.zprofile`, `.zlogin` to use warp.

Perhaps, offhand, you may know 
- How do I know what to comment out, any ideas?
- is there a less manual way to disable powerlevel10k?

**Comment by ahmedre** [comment]
for me, the message disappears when using powerlevel10k after hitting enter (for example), but because I am using the instant prompt feature, it complains about console output during zsh initialization.

if I disable instant prompt (but keep powerlevel10k), warp works fine.

@yehudamakarov - see https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-enable-instant-prompt for the lines to comment out to disable instant prompt.
