### ISSUE TITLE
Discussion - Make warp available on Setapp

### ISSUE THREAD

**Issue by mittalyashu** [warpdotdev/warp#95]
Can you make warp available on [Setapp](https://setapp.com/)?

That way we can even use warp premium features.

**Comment by donaldguy** [comment]
As a Setapp user myself, I would find appeal in this. 

But I also think, in practice, its asking Warp (or "Denver Technologies, Inc." per website footer) to unreasonably complicate their revenue model (as well as some aspects of product design and ~release management)—largely because only here in beta (while Metal is the only supported renderer) is Warp designed to be mac-exclusive app.

Warp's [stated](https://github.com/warpdotdev/warp/blob/ee65fdcf1286243d271aac6a7d58a99d6b17ee9b/README.md?plain=1#L43) plan is to have a free (gratis, libre) fairly fully-featured [cross-platform ](https://blog.warp.dev/how-warp-works/#looking-forward)client. 

They will, therefore, to survive and grow as a company (and recoup development costs), need to make up that lost-opportunity-cost from (enterprise) customers.

---

As such, planned premium features (logically, and those revealed to date) are tied to collaboration and distributed/shared workspaces. This means that each sale/subscription will have an associated COGS/opex to operate backends.

For features like infinite history (an example of one that would appeal to a Setapp-subscribing individual user), there will be a growing storage-cost over time. **_And_** that cost would be incurred every month regardless of whether or not you used Warp that month (something I have to imagine has some effect on how MacPaw splits Setapp revenue amongst apps). For good UX, it logically couldn't be vacated until you at least uninstall Warp in Setapp, and probably til you unsubscribe from Setapp entirely.

This isn't 100% untrod territory for Setapp<sup>1</sup> (c.f. [Timing's pricing](https://timingapp.com/pricing#)), and probably less so for [Setapp for Teams](https://setapp.com/teams)


But the trick, I think, for Timing, and many other apps on Setapp is that they are Mac and iOS exclusive and hang all their storage and sync functions onto CloudKit et al - and so any cloud storage costs are being paid by Apple (and in turn by the end-user to Apple if they are a hefty enough iCloud user)
 

---

With the notable exceptions (to my knowledge) of Timing and [Ulysses](https://ulysses.app/get/) (maybe there are others but I'm not sure), the trend seems to be that a monthly revenue share from Setapp is traded off against offering a one time<sup>2</sup> (license file or in-app) purchase. I kinda don't see that making sense for Warp.


---

It seems like, Timing, Ulysses, Session (as an example of a freemium app that offers Setapp or an in-app subscription for pro-features), etc. are finding that they can make the pricing tradeoff make sense because of Setapp's strict per-device licensing. 

For Timing, month-to-month you'd pay $8.40 for 3 macs (and in both cases they throw in limited web app for free)
for Ulysses $7/mo ($50/yr) to use on (unlimited but in practice) a mac or two + maybe an iPad
for Session, you'd pay $6/mo ($40/yr) to use (premium features, unlimited but in practice) on a mac or two + maybe an iPhone; 

Users pay those through Apple generally, so the developers only see 70% of that.

For Setapp, developers get whatever share of $10 (for 1st + $2.50/mo additional) per mac or iOS device per month

The economics can make sense, but it seems real tight - and pretty fundamentally reliant on being Apple ecosystem exclusive, which again, Warp isn't going to be.

---

So even ignoring the Mac exclusivity issue, it seem like Warp is akin to [CleanshotX](https://cleanshot.com/pricing) - where they go in on an individual user tier with a strict (and fairly low, for images) cloud usage cap.  

But at the level above that, or with more team features, for "Cloud Pro", they've judged even Setapp for Teams' $10/user/mo too low to trade off again first party ($8/usr/mo (annual, month-to-month: $10/user/mo))

---

So, with something like infinite history, or shared env vars, Warp could use iCloud, but they'd have to make it Apple clients exclusive, or they could support Dropbox sync maybe - but they'd still be incentivized to only let you use Apple clients where Setapp can enforce licensing - or otherwise find some way to make you pay separately if you want to use Warp (premium features) from Windows/Linux/etc.

It seems unlikely its worth the overhead of maintaining a separate (closed source) fork with the Setapp runtime authorization/licensing API (see e.g. https://github.com/MacPaw/Setapp-framework though that one is iOS specific?) and non-first-party-cloud, non-enterprise-backend (e.g. iCloud) support

---
<sup>1</sup> Nor is offering otherwise free(mium) app, e.g. [Meeter](https://trymeeter.com/) and [Session](https://www.stayinsession.com/pricing). 

Open source might be unprecedented though, I thought [Numi](https://github.com/nikolaeu/numi) was a counterexample, but now I look closer at the repo it seems more ~Sublime-esque: open source plugins, but fully closed source core)

<sup>2</sup>or in practice ~roughly annual "optional" upgrade purchase, per macOS release, for e.g. Dash and Bartender

**Comment by elviskahoro** [comment]
Moved to discussion:
- #400
